### ISSUE TITLE
Runtime Error: Event Loop is Closed

### ISSUE THREAD

**Issue by iSupakilla** [datawhores/OF-Scraper#125]
I've scraped a few accounts no issues, so far: 2 of them download a few images and then hang on "Pages Progress" and then complete and don't download anything else.

![2023-07-14_18-46-38](https://github.com/datawhores/OF-Scraper/assets/56417977/e9c082ed-a3b1-4b35-a1cc-a9a5a24711f9)

**Comment by datawhores** [comment]
Are you on python 3.10
Their seems to be an error on
version 3.10.1

**Comment by iSupakilla** [comment]
I'm actually back on 3.9, that an issue?

**Comment by datawhores** [comment]
It probably worth the effort to update as I know this issue has been tied to older python versions

**Comment by rciptv2019** [comment]
I have exactly the same problem. With python 3.10.2 it gives me that problem. Seeing the answers here under the version to 3.10 and it continues giving me exactly the same problem.

**Comment by rciptv2019** [comment]
[filters.dupefilter:50]  Removing duplicate media                                                        filters.py:50
 [filters.posts_type_filter:83]  filtering Media to images,audios,videos                                  filters.py:83
Exception ignored in: <function _ProactorBasePipeTransport.__del__ at 0x000001BAC1D80E50>
Traceback (most recent call last):
  File "C:\Users\rcpar\AppData\Local\Programs\Python\Python310\lib\asyncio\proactor_events.py", line 116, in __del__
    self.close()
  File "C:\Users\rcpar\AppData\Local\Programs\Python\Python310\lib\asyncio\proactor_events.py", line 108, in close
    self._loop.call_soon(self._call_connection_lost, None)
  File "C:\Users\rcpar\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 745, in call_soon
    self._check_closed()
  File "C:\Users\rcpar\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 510, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed
Exception ignored in: <function _ProactorBasePipeTransport.__del__ at 0x000001BAC1D80E50>
Traceback (most recent call last):
  File "C:\Users\rcpar\AppData\Local\Programs\Python\Python310\lib\asyncio\proactor_events.py", line 116, in __del__
    self.close()
  File "C:\Users\rcpar\AppData\Local\Programs\Python\Python310\lib\asyncio\proactor_events.py", line 108, in close
    self._loop.call_soon(self._call_connection_lost, None)
  File "C:\Users\rcpar\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 745, in call_soon
    self._check_closed()
  File "C:\Users\rcpar\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 510, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed

**Comment by datawhores** [comment]
What version of python are you on right now

**Comment by rciptv2019** [comment]
3.10.0

**Comment by datawhores** [comment]
I meant try to upgrade to the latest version of 3.10 or 3.11 
Like 3.10.11 or so

**Comment by rciptv2019** [comment]
With python 3.10.11 it doesn't give that error and seems to work correctly.
Thank you
