### ISSUE TITLE
dir_lock issue still present in 3.0.7

### ISSUE THREAD

**Issue by dpsbrdi** [datawhores/OF-Scraper#156]
it's still dying with

NameError: name 'dir_lock' is not defined

```
Traceback (most recent call last):
  File "C:\Users\xxx\AppData\Local\Programs\Python\Python311\Lib\site-packages\multiprocess\process.py", line 314, in _bootstrap
    self.run()
  File "C:\Users\xxx\AppData\Local\Programs\Python\Python311\Lib\site-packages\multiprocess\process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\xxx\AppData\Local\Programs\Python\Python311\Lib\site-packages\ofscraper\utils\download.py", line 237, in process_dict_starter
    asyncio.run(process_dicts_split(username,model_id,ele,log,p_logqueue_,pipe_))
  File "C:\Users\xxx\AppData\Local\Programs\Python\Python311\Lib\asyncio\runners.py", line 190, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "C:\Users\xxx\AppData\Local\Programs\Python\Python311\Lib\asyncio\runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\xxx\AppData\Local\Programs\Python\Python311\Lib\asyncio\base_events.py", line 653, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "C:\Users\xxx\AppData\Local\Programs\Python\Python311\Lib\site-packages\ofscraper\utils\download.py", line 336, in process_dicts_split
    setDirectoriesDate()
  File "C:\Users\xxx\AppData\Local\Programs\Python\Python311\Lib\site-packages\ofscraper\utils\download.py", line 872, in setDirectoriesDate
    with dir_lock:
         ^^^^^^^^
NameError: name 'dir_lock' is not defined
```

**Comment by datawhores** [comment]
Yes
I was able to trigger the error 

In the end it is easier to just set the directories in the main thread.
With that said it should be fixed in 3.0.9
