### ISSUE TITLE
Scraper crashes python on exit

### ISSUE THREAD

**Issue by BosonHair** [datawhores/OF-Scraper#159]
Hello,
Now that I got it to not crash python starting, it now seems to crash when the scraper exits. 

`Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/multiprocess/process.py", line 314, in _bootstrap
    self.run()
  File "/usr/local/lib/python3.10/site-packages/multiprocess/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.10/site-packages/ofscraper/utils/logger.py", line 336, in inner
    thread.join()
  File "/usr/local/Cellar/python@3.10/3.10.12_1/Frameworks/Python.framework/Versions/3.10/lib/python3.10/threading.py", line 1096, in join
    self._wait_for_tstate_lock()
  File "/usr/local/Cellar/python@3.10/3.10.12_1/Frameworks/Python.framework/Versions/3.10/lib/python3.10/threading.py", line 1116, in _wait_for_tstate_lock
    if lock.acquire(block, timeout):
KeyboardInterrupt
Exception in thread Thread-30 (queue_process):
Traceback (most recent call last):
Exception in thread Thread-28 (queue_process):
Exception in thread Thread-32 (queue_process):
Exception in thread Thread-29 (queue_process):
Traceback (most recent call last):
Exception in thread Thread-25 (queue_process):
Traceback (most recent call last):
Traceback (most recent call last):
  File "/usr/local/Cellar/python@3.10/3.10.12_1/Frameworks/Python.framework/Versions/3.10/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
  File "/usr/local/Cellar/python@3.10/3.10.12_1/Frameworks/Python.framework/Versions/3.10/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
Exception in thread Thread-31 (queue_process):
Exception in thread Thread-26 (queue_process):
Traceback (most recent call last):
  File "/usr/local/Cellar/python@3.10/3.10.12_1/Frameworks/Python.framework/Versions/3.10/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
Exception in thread Thread-27 (queue_process):
Traceback (most recent call last):
Traceback (most recent call last):
    self.run()
    self.run()
  File "/usr/local/Cellar/python@3.10/3.10.12_1/Frameworks/Python.framework/Versions/3.10/lib/python3.10/threading.py", line 953, in run
  File "/usr/local/Cellar/python@3.10/3.10.12_1/Frameworks/Python.framework/Versions/3.10/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
  File "/usr/local/Cellar/python@3.10/3.10.12_1/Frameworks/Python.framework/Versions/3.10/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
  File "/usr/local/Cellar/python@3.10/3.10.12_1/Frameworks/Python.framework/Versions/3.10/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
Exception in thread Thread-1 (logger_process):
Traceback (most recent call last):
    self.run()
    self._target(*self._args, **self._kwargs)
    self.run()
  File "/usr/local/Cellar/python@3.10/3.10.12_1/Frameworks/Python.framework/Versions/3.10/lib/python3.10/threading.py", line 953, in run
  File "/usr/local/Cellar/python@3.10/3.10.12_1/Frameworks/Python.framework/Versions/3.10/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
Traceback (most recent call last):
  File "/usr/local/Cellar/python@3.10/3.10.12_1/Frameworks/Python.framework/Versions/3.10/lib/python3.10/threading.py", line 953, in run
    self.run()
Fatal Python error: _enter_buffered_busy: could not acquire lock for <_io.BufferedWriter name='<stderr>'> at interpreter shutdown, possibly due to daemon threads
Python runtime state: finalizing (tstate=0x00007fc984904880)

Current thread 0x000000010f062600 (most recent call first):
  <no Python frame>

Extension modules: _brotli, multidict._multidict, yarl._quoting_c, aiohttp._helpers, aiohttp._http_writer, aiohttp._http_parser, aiohttp._websocket, cchardet._cchardet, _cffi_backend, frozenlist._frozenlist, lz4._version, lz4.block._block, xxhash._xxhash, numpy.core._multiarray_umath, numpy.core._multiarray_tests, numpy.linalg._umath_linalg, numpy.fft._pocketfft_internal, numpy.random._common, numpy.random.bit_generator, numpy.random._bounded_integers, numpy.random._mt19937, numpy.random.mtrand, numpy.random._philox, numpy.random._pcg64, numpy.random._sfc64, numpy.random._generator, google._upb._message, lxml._elementpath, lxml.etree, psutil._psutil_osx, psutil._psutil_posix (total: 31)`

and from Python crasher app:
`Process:               Python [27474]
Path:                  /usr/local/Cellar/python@3.10/3.10.12_1/Frameworks/Python.framework/Versions/3.10/Resources/Python.app/Contents/MacOS/Python
Identifier:            org.python.python
Version:               3.10.12 (3.10.12)
Code Type:             X86-64 (Native)
Parent Process:        Python [27357]
Responsible:           Terminal [25437]
User ID:               502

Date/Time:             2023-08-07 20:44:21.3912 -0400
OS Version:            macOS 12.6.8 (21G725)
Report Version:        12
Bridge OS Version:     3.0 (14Y910)
Anonymous UUID:        00A9284B-61F5-FA20-776E-F6A346FDA764

Sleep/Wake UUID:       4EDED723-8359-4BAD-BD6E-36722BEF604A

Time Awake Since Boot: 46000 seconds
Time Since Wake:       2 seconds

System Integrity Protection: enabled

Crashed Thread:        0  Dispatch queue: com.apple.main-thread

Exception Type:        EXC_BAD_ACCESS (SIGSEGV)
Exception Codes:       KERN_INVALID_ADDRESS at 0x0000000000000110
Exception Codes:       0x0000000000000001, 0x0000000000000110
Exception Note:        EXC_CORPSE_NOTIFY

Termination Reason:    Namespace SIGNAL, Code 11 Segmentation fault: 11
Terminating Process:   exc handler [27474]

VM Region Info: 0x110 is not in any region.  Bytes before following region: 140737486581488
      REGION TYPE                    START - END         [ VSIZE] PRT/MAX SHRMOD  REGION DETAIL
      UNUSED SPACE AT START
--->  
      VM_ALLOCATE              7fffffe4f000-7fffffe50000 [    4K] r-x/r-x SM=ALI  

Application Specific Information:
*** multi-threaded process forked ***
crashed on child side of fork pre-exec
`

What's weirder is my python version installed is 3.11.4. Not sure if it's related. I'm using 3.0.5 version of the scraper.

**Comment by datawhores** [comment]
It looks like you installed with python3.10
So you probably have multiple version on your system
