### ISSUE TITLE
bug: Exception raised after a few models

### ISSUE THREAD

**Issue by dunngitter** [datawhores/OF-Scraper#166]
When running with: `ofscraper --config /ofscraper/config/config.json --username ALL --posts all` I get the following after about 10 models scraped:

```python
Process ForkProcess-20:
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/multiprocess/process.py", line 314, in _bootstrap
    self.run()
  File "/usr/local/lib/python3.10/dist-packages/multiprocess/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/ofscraper/app/ofscraper/utils/download.py", line 237, in process_dict_starter
    asyncio.run(process_dicts_split(username,model_id,ele,log,p_logqueue_,pipe_))
  File "/usr/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/ofscraper/app/ofscraper/utils/download.py", line 336, in process_dicts_split
    setDirectoriesDate()
  File "/ofscraper/app/ofscraper/utils/download.py", line 873, in setDirectoriesDate
    set_time(ele,dates.get_current_time())
  File "/ofscraper/app/ofscraper/utils/download.py", line 838, in set_time
```

**Comment by datawhores** [comment]
What version are you running

**Comment by dunngitter** [comment]
Built from git, hash 87247b2692b

**Comment by datawhores** [comment]
Can you show the full traceback

**Comment by dunngitter** [comment]
Sure but this is all I'm seeing, how do I get the full traceback?

**Comment by datawhores** [comment]
You should probably run with --log debug 
That should help show the full traceback

**Comment by dunngitter** [comment]
Does this help at all? I'm not seeing any more of the python traceback... I deleted profile names and post ids

```
DEBUG     [paths._linux_truncateHelper:157]  path:                                                                  paths.py:157
         /ofscraper/data//Profile/Free/Images/avatar_01-05-2021.jpeg filename bytesize: 22
DEBUG     [paths._linux_truncateHelper:157]  path:                                                                  paths.py:157
         /ofscraper/data//Profile/Free/Images/avatar_01-05-2021_None.part filename bytesize: 27
DEBUG     [download.main_download_helper:375]  Media:None Post: Downloading with download.py:375
         normal downloader
DEBUG     [download.main_download_downloader:416]  Media:None Post: Attempting   download.py:416
         to download media avatar_01-05-2021 with
         https:/your_username/public.onlyfans.com/files/a/al/alt//
         /avatar.jpg
Progress: (0 photos, 0 videos, 0 audios, 0 skipped, 0 failed || 0/11||0 B/0.08 MB) ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━   0% 0:00:01
╭──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╮
DEBUG     [download.main_download_downloader:430]  Media:None Post: filename     download.py:430
         from config avatar_01-05-2021.jpeg
Progress: (1 photos, 0 videos, 0 audios, 0 skipped, 0 failed || 1/11||0.08 MB/0.08 MB) ━━╸━━━━━━━━━━━━━━━━━━━━━━━━━   9% 0:00:01
╭──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╮
╰──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/multiprocess/process.py", line 314, in _bootstrap
    self.run()
  File "/usr/local/lib/python3.10/dist-packages/multiprocess/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/ofscraper/app/ofscraper/utils/download.py", line 237, in process_dict_starter
    asyncio.run(process_dicts_split(username,model_id,ele,log,p_logqueue_,pipe_))
  File "/usr/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/ofscraper/app/ofscraper/utils/download.py", line 336, in process_dicts_split
    setDirectoriesDate()
  File "/ofscraper/app/ofscraper/utils/download.py", line 873, in setDirectoriesDate
    set_time(ele,dates.get_current_time())
  File "/ofscraper/app/ofscraper/utils/download.py", line 838, in set_time

```

**Comment by dunngitter** [comment]
Interesting, if I run interactively and scrape all users and all content, I get a similar exception almost immediately:
```python
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/multiprocess/process.py", line 314, in _bootstrap
    self.run()
  File "/usr/local/lib/python3.10/dist-packages/multiprocess/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/ofscraper/app/ofscraper/utils/download.py", line 237, in process_dict_starter
    asyncio.run(process_dicts_split(username,model_id,ele,log,p_logqueue_,pipe_))
  File "/usr/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
Exception in thread Thread-20 (logger_other):
  File "/ofscraper/app/ofscraper/utils/download.py", line 336, in process_dicts_split
    setDirectoriesDate()
  File "/ofscraper/app/ofscraper/utils/download.py", line 873, in setDirectoriesDate
    set_time(ele,dates.get_current_time())
  File "/ofscraper/app/ofscraper/utils/download.py", line 838, in set_time
    pathlib.os.utime(path, (timestamp, timestamp))
Traceback (most recent call last):
PermissionError: [Errno 1] Operation not permitted
  File "/usr/lib/python3.10/threading.py", line 1016, in _bootstrap_inner

```

**Comment by datawhores** [comment]
Yeah that might be the right way to fix this

**Comment by datawhores** [comment]
I pushed a fix for this
