### ISSUE TITLE
Forkprocess Error

### ISSUE THREAD

**Issue by BosonHair** [datawhores/OF-Scraper#171]
Got this new type of error:

Process ForkProcess-48:
Traceback (most recent call last):
  File "/Users/####/.local/pipx/venvs/ofscraper/lib/python3.11/site-packages/multiprocess/process.py", line 314, in _bootstrap
    self.run()
  File "/Users/####/.local/pipx/venvs/ofscraper/lib/python3.11/site-packages/multiprocess/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/####/.local/pipx/venvs/ofscraper/lib/python3.11/site-packages/ofscraper/utils/download.py", line 240, in process_dict_starter
    asyncio.run(process_dicts_split(username,model_id,ele,log,p_logqueue_,pipe_))
  File "/usr/local/Cellar/python@3.11/3.11.4_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/asyncio/runners.py", line 190, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "/usr/local/Cellar/python@3.11/3.11.4_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/Cellar/python@3.11/3.11.4_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/asyncio/base_events.py", line 653, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/Users/####/.local/pipx/venvs/ofscraper/lib/python3.11/site-packages/ofscraper/utils/download.py", line 311, in process_dicts_split
    medialist=seperate.seperate_avatars(medialist)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/####/.local/pipx/venvs/ofscraper/lib/python3.11/site-packages/ofscraper/utils/separate.py", line 19, in seperate_avatars
    return list(filter(lambda x:seperate_avatar_helper(x)==False,data))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/####/.local/pipx/venvs/ofscraper/lib/python3.11/site-packages/ofscraper/utils/separate.py", line 19, in <lambda>
    return list(filter(lambda x:seperate_avatar_helper(x)==False,data))
                                ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/####/.local/pipx/venvs/ofscraper/lib/python3.11/site-packages/ofscraper/utils/separate.py", line 22, in seperate_avatar_helper
    cache = Cache(getcachepath())
            ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/####/.local/pipx/venvs/ofscraper/lib/python3.11/site-packages/diskcache/core.py", line 478, in __init__
    self.reset(key, value, update=False)
  File "/Users/####/.local/pipx/venvs/ofscraper/lib/python3.11/site-packages/diskcache/core.py", line 2434, in reset
    ((old_value,),) = sql(

Have you seen this?

**Comment by datawhores** [comment]
Are you on a network drive

This is more of an issue with diskcache rather then of-scraper specially

**Comment by BosonHair** [comment]
Gotcha, thanks Data!
