### ISSUE TITLE
Program Opens then Immedietly Closes

### ISSUE THREAD

**Issue by AllenDuong** [datawhores/OF-Scraper#175]
```
Traceback (most recent call last):
  File "__main__.py", line 3, in <module>
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 385, in exec_module
  File "start.py", line 13, in <module>
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 385, in exec_module
  File "commands\scraper.py", line 35, in <module>
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 385, in exec_module
  File "utils\download.py", line 73, in <module>
  File "utils\config.py", line 42, in read_config
  File "utils\config.py", line 84, in get_current_config_schema
  File "utils\config.py", line 294, in get_threads
ValueError: invalid literal for int() with base 10: ''
[4824] Failed to execute script '__main__' due to unhandled exception!
```

**Comment by datawhores** [comment]
Fixed
