### ISSUE TITLE
Error in uvloop

### ISSUE THREAD

**Issue by dia-val** [datawhores/OF-Scraper#177]
After updating to 3.0.12+main.86a9b48 i get the following error trying to download a model (it doesn't download anything just throws this error):

2023-08-25 06:58:47 - TRACEBACK - failed with exception: list index out of range
2023-08-25 06:58:47 - TRACEBACK - Traceback (most recent call last):
  File "/home/your_username/app/your_username/commands/scraper.py", line 182, in normal_post_process
    combined_urls=OF.process_areas( ele, model_id)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/your_username/app/your_username/utils/of.py", line 264, in process_areas
    messages_dicts = process_messages( model_id,username)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/your_username/app/your_username/utils/of.py", line 40, in process_messages
    messages_ =asyncio.run(messages.get_messages(  model_id,username))
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/asyncio/runners.py", line 188, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/asyncio/runners.py", line 120, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "uvloop/loop.pyx", line 1517, in uvloop.loop.Loop.run_until_complete
  File "/home/your_username/app/your_username/api/messages.py", line 86, in get_messages
    if before>=oldmessages[1].get("date"):i=0
               ~~~~~~~~~~~^^^
IndexError: list index out of range

**Comment by datawhores** [comment]
Yes I added a fix for this
