### ISSUE TITLE
queue.Full error in 3.0.12

### ISSUE THREAD

**Issue by mmmzzzxxx** [datawhores/OF-Scraper#179]
Getting this error running `ofscraper_windows_3.0.12.exe`. I got a handful of media files downloaded once but most of the time it sits endlessly at a bar with 0 everything downloaded.
```
--- Logging error ---
Process SpawnProcess-2:
Traceback (most recent call last):
  File "logging\handlers.py", line 1475, in emit
  File "logging\handlers.py", line 1436, in enqueue
  File "multiprocess\queues.py", line 141, in put_nowait
  File "multiprocess\queues.py", line 93, in put
queue.Full

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "multiprocess\process.py", line 314, in _bootstrap
  File "multiprocess\process.py", line 108, in run
  File "utils\download.py", line 240, in process_dict_starter
  File "asyncio\runners.py", line 44, in run
  File "asyncio\base_events.py", line 649, in run_until_complete
  File "utils\download.py", line 272, in process_dicts_split
  File "logging\__init__.py", line 1465, in debug
  File "logging\__init__.py", line 1624, in _log
  File "logging\__init__.py", line 1634, in handle
  File "logging\__init__.py", line 1696, in callHandlers
  File "logging\__init__.py", line 968, in handle
  File "logging\handlers.py", line 1477, in emit
```

Here is my config file. I tried playing around with `download-sems` and `threads`, when they were higher I just got more error messages.
```
{
    "config": {
        "main_profile": "main_profile",
        "save_location": "D:\\Downloads\\ofscraper",
        "file_size_limit": 0,
        "file_size_min": 0,
        "dir_format": "{model_username}/{responsetype}/{mediatype}/",
        "file_format": "{filename}.{ext}",
        "textlength": 0,
        "space-replacer": " ",
        "date": "YYYY-MM-DD",
        "metadata": "{configpath}/{profile}/.data/{model_username}_{model_id}",
        "filter": [
            "Images",
            "Audios",
            "Videos"
        ],
        "threads": 1,
        "code-execution": false,
        "custom": "",
        "mp4decrypt": "D:\\Downloads\\ofscraper\\Bento4\\bin\\mp4decrypt.exe",
        "ffmpeg": "D:\\Downloads\\ofscraper\\ffmpeg\\bin\\ffmpeg.exe",
        "discord": "",
        "private-key": "",
        "client-id": "",
        "key-mode-default": "cdrm2",
        "keydb_api": "",
        "dynamic-mode-default": "deviint",
        "partfileclean": false,
        "backend": "aio",
        "download-sems": 1,
        "maxfile-sem": 0,
        "downloadbars": false,
        "responsetype": {
            "timeline": "Posts",
            "message": "Messages",
            "archived": "Archived",
            "paid": "Messages",
            "stories": "Stories",
            "highlights": "Stories",
            "profile": "Profile",
            "pinned": "Posts"
        }
    }
}
```

**Comment by datawhores** [comment]
Wait for a new release or try a commit version

**Comment by mmmzzzxxx** [comment]
Whatever changed between then and `ofscraper_windows_ed89d3e.exe` fixed it!
