### ISSUE TITLE
[Bug] PermissionError: [WinError 32] The process cannot access the file because it's being used by another process

### ISSUE THREAD

**Issue by ondrovic** [datawhores/OF-Scraper#18]
### OS
Windows 11 Pro Version 22H2 Build 22621.1413

### Python version
3.11.1

### Description of Problem

When attempting to download items throws the following error

```python
 Traceback (most recent call last):e843b52f.jpeg:   0%|                           | 0.00/180k [00:00<?, ?B/s]
  File "C:\Program Files\Python311\Lib\contextlib.py", line 222, in __aexit__   | 0.00/210k [00:00<?, ?B/s]
    await self.gen.athrow(typ, value, traceback)
  File "C:\Users\pyuser\AppData\Roaming\Python\Python311\site-packages\httpx\_client.py", line 1580, in stream
    yield response
  File "C:\Users\pyuser\AppData\Roaming\Python\Python311\site-packages\src\utils\download.py", line 141, in download
    pathlib.Path(temp).unlink(missing_ok=True)
  File "C:\Program Files\Python311\Lib\pathlib.py", line 1147, in unlink
    os.unlink(self)
PermissionError: [WinError 32] The process cannot access the file because it is being used by another process: '959x1280_ad243c3a4327cc313a7f7b06e843b52f.jpeg'

Traceback (most recent call last):
  File "C:\Program Files\Python311\Lib\contextlib.py", line 222, in __aexit__
    await self.gen.athrow(typ, value, traceback)
  File "C:\Users\pyuser\AppData\Roaming\Python\Python311\site-packages\httpx\_client.py", line 1580, in stream
    yield response
  File "C:\Users\pyuser\AppData\Roaming\Python\Python311\site-packages\src\utils\download.py", line 141, in download
    pathlib.Path(temp).unlink(missing_ok=True)
  File "C:\Program Files\Python311\Lib\pathlib.py", line 1147, in unlink
    os.unlink(self)
PermissionError: [WinError 32] The process cannot access the file because it is being used by another process: '959x1280_4d2e5960119034747f27da8372f06cd8.jpeg'
```

**Comment by datawhores** [comment]
Are you still facing this issue 
the test branch may fix it.

**Comment by trsmith78** [comment]
Hi,
I'm having this issue too.  Was there ever a resolution?
