### ISSUE TITLE
An existing connection was forcibly closed by the remote host

### ISSUE THREAD

**Issue by Arko109** [datawhores/OF-Scraper#180]
Getting an exception after which, the downloading is not progressing, only the timer ticks:

<details>
<summary>Traceback</summary>
Process SpawnProcess-5:
Traceback (most recent call last):
  File "C:\Users\username\.conda\envs\ofscraper\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\username\.conda\envs\ofscraper\lib\asyncio\proactor_events.py", line 165, in _call_connection_lost
    self._sock.shutdown(socket.SHUT_RDWR)
ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\username\.conda\envs\ofscraper\lib\logging\__init__.py", line 1100, in emit
    msg = self.format(record)
  File "C:\Users\username\.conda\envs\ofscraper\lib\logging\__init__.py", line 943, in format
    return fmt.format(record)
  File "C:\Users\username\.conda\envs\ofscraper\lib\logging\__init__.py", line 686, in format
    record.exc_text = self.formatException(record.exc_info)
  File "C:\Users\username\.conda\envs\ofscraper\lib\logging\__init__.py", line 636, in formatException
    traceback.print_exception(ei[0], ei[1], tb, None, sio)
AttributeError: 'function' object has no attribute 'print_exception'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\username\.conda\envs\ofscraper\lib\asyncio\base_events.py", line 1784, in call_exception_handler
    self.default_exception_handler(context)
  File "C:\Users\username\.conda\envs\ofscraper\lib\asyncio\base_events.py", line 1758, in default_exception_handler
    logger.error('\n'.join(log_lines), exc_info=exc_info)
  File "C:\Users\username\.conda\envs\ofscraper\lib\logging\__init__.py", line 1506, in error
    self._log(ERROR, msg, args, **kwargs)
  File "C:\Users\username\.conda\envs\ofscraper\lib\logging\__init__.py", line 1624, in _log
    self.handle(record)
  File "C:\Users\username\.conda\envs\ofscraper\lib\logging\__init__.py", line 1634, in handle
    self.callHandlers(record)
  File "C:\Users\username\.conda\envs\ofscraper\lib\logging\__init__.py", line 1704, in callHandlers
    lastResort.handle(record)
  File "C:\Users\username\.conda\envs\ofscraper\lib\logging\__init__.py", line 968, in handle
    self.emit(record)
  File "C:\Users\username\.conda\envs\ofscraper\lib\logging\__init__.py", line 1108, in emit
    self.handleError(record)
  File "C:\Users\username\.conda\envs\ofscraper\lib\logging\__init__.py", line 1022, in handleError
    traceback.print_exception(t, v, tb, None, sys.stderr)
AttributeError: 'function' object has no attribute 'print_exception'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\username\.conda\envs\ofscraper\lib\logging\__init__.py", line 1100, in emit
    msg = self.format(record)
  File "C:\Users\username\.conda\envs\ofscraper\lib\logging\__init__.py", line 943, in format
    return fmt.format(record)
  File "C:\Users\username\.conda\envs\ofscraper\lib\logging\__init__.py", line 686, in format
    record.exc_text = self.formatException(record.exc_info)
  File "C:\Users\username\.conda\envs\ofscraper\lib\logging\__init__.py", line 636, in formatException
    traceback.print_exception(ei[0], ei[1], tb, None, sio)
AttributeError: 'function' object has no attribute 'print_exception'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\username\.conda\envs\ofscraper\lib\site-packages\multiprocess\process.py", line 314, in _bootstrap
    self.run()
  File "C:\Users\username\.conda\envs\ofscraper\lib\site-packages\multiprocess\process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\username\.conda\envs\ofscraper\lib\site-packages\ofscraper\utils\download.py", line 240, in process_dict_starter
    asyncio.run(process_dicts_split(username,model_id,ele,log,p_logqueue_,pipe_))
  File "C:\Users\username\.conda\envs\ofscraper\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Users\username\.conda\envs\ofscraper\lib\asyncio\base_events.py", line 636, in run_until_complete
    self.run_forever()
  File "C:\Users\username\.conda\envs\ofscraper\lib\asyncio\windows_events.py", line 321, in run_forever
    super().run_forever()
  File "C:\Users\username\.conda\envs\ofscraper\lib\asyncio\base_events.py", line 603, in run_forever
    self._run_once()
  File "C:\Users\username\.conda\envs\ofscraper\lib\asyncio\base_events.py", line 1909, in _run_once
    handle._run()
  File "C:\Users\username\.conda\envs\ofscraper\lib\asyncio\events.py", line 94, in _run
    self._loop.call_exception_handler(context)
  File "C:\Users\username\.conda\envs\ofscraper\lib\asyncio\base_events.py", line 1791, in call_exception_handler
    logger.error('Exception in default exception handler',
  File "C:\Users\username\.conda\envs\ofscraper\lib\logging\__init__.py", line 1506, in error
    self._log(ERROR, msg, args, **kwargs)
  File "C:\Users\username\.conda\envs\ofscraper\lib\logging\__init__.py", line 1624, in _log
    self.handle(record)
  File "C:\Users\username\.conda\envs\ofscraper\lib\logging\__init__.py", line 1634, in handle
    self.callHandlers(record)
  File "C:\Users\username\.conda\envs\ofscraper\lib\logging\__init__.py", line 1704, in callHandlers
    lastResort.handle(record)
  File "C:\Users\username\.conda\envs\ofscraper\lib\logging\__init__.py", line 968, in handle
    self.emit(record)
  File "C:\Users\username\.conda\envs\ofscraper\lib\logging\__init__.py", line 1108, in emit
    self.handleError(record)
  File "C:\Users\username\.conda\envs\ofscraper\lib\logging\__init__.py", line 1022, in handleError
</details>

**Comment by Arko109** [comment]
Gone after an update
