### ISSUE TITLE
Download of individual post getting stalled and returning error.

### ISSUE THREAD

**Issue by tunalocura** [datawhores/OF-Scraper#197]
This is happening while attempting to download individual post as described in the gitbook documentation. In my case, a media of 1.1GB size is stalling after download around 50% followed by throwing the following list of exceptions in the terminal.

Command used:
`ofscraper manual --url <MY_LINK>`

Python Version: 3.11
Platform: MacOS Catalina (10.15.7) (Intel Based)
OF-Scraper version: 3.2.2
CDM using: key-db

`Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/logging/handlers.py", line 1498, in emit
    self.enqueue(self.prepare(record))
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/logging/handlers.py", line 1456, in enqueue
    self.queue.put_nowait(record)
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/multiprocess/queues.py", line 141, in put_nowait
    return self.put(obj, False)
           ^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/multiprocess/queues.py", line 93, in put
    raise Full
queue.Full

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/ofscraper/utils/download.py", line 555, in inner
    log.debug(f"{get_medialog(ele)} [attempt {_attempt.get()}/{constants.NUM_TRIES}] download temp path {temp}")
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/logging/__init__.py", line 1477, in debug
    self._log(DEBUG, msg, args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/logging/__init__.py", line 1634, in _log
    self.handle(record)
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/logging/__init__.py", line 1644, in handle
    self.callHandlers(record)
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/logging/__init__.py", line 1706, in callHandlers
    hdlr.handle(record)
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/logging/__init__.py", line 978, in handle
    self.emit(record)
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/logging/handlers.py", line 1500, in emit
    self.handleError(record)
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/logging/__init__.py", line 1032, in handleError
    traceback.print_exception(t, v, tb, None, sys.stderr)
    ^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'function' object has no attribute 'print_exception'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/logging/handlers.py", line 1498, in emit
    self.enqueue(self.prepare(record))
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/logging/handlers.py", line 1456, in enqueue
    self.queue.put_nowait(record)
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/multiprocess/queues.py", line 141, in put_nowait
    return self.put(obj, False)
           ^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/multiprocess/queues.py", line 93, in put
    raise Full
queue.Full

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/ofscraper/utils/download.py", line 190, in process_dicts
    pack= await coro
          ^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/asyncio/tasks.py", line 605, in _wait_for_one
    return f.result()  # May raise f.exception().
           ^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/ofscraper/utils/download.py", line 258, in download
    return await alt_download_helper(c,ele,pathlib.Path(".").absolute(),username,model_id,progress)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/ofscraper/utils/download.py", line 412, in alt_download_helper
    video=await alt_download_downloader(video,c,ele,path,progress) 
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/ofscraper/utils/download.py", line 588, in alt_download_downloader
    return await inner(item,c,ele,progress)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/tenacity/_asyncio.py", line 88, in async_wrapped
    return await fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/tenacity/_asyncio.py", line 47, in __call__
    do = self.iter(retry_state=retry_state)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/tenacity/__init__.py", line 325, in iter
    raise retry_exc.reraise()
          ^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/tenacity/__init__.py", line 158, in reraise
    raise self.last_attempt.result()
          ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/concurrent/futures/_base.py", line 449, in result
    return self.__get_result()
           ^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/concurrent/futures/_base.py", line 401, in __get_result
    raise self._exception
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/tenacity/_asyncio.py", line 50, in __call__
    result = await fn(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/ofscraper/utils/download.py", line 100, in inner
    raise E  
    ^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/ofscraper/utils/download.py", line 98, in inner
    return await func(*args,**kwargs) 
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/ofscraper/utils/download.py", line 581, in inner
    log.traceback(traceback.format_exc())
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/ofscraper/utils/logger.py", line 187, in inner
    self._log(level, message, args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/logging/__init__.py", line 1634, in _log
    self.handle(record)
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/logging/__init__.py", line 1644, in handle
    self.callHandlers(record)
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/logging/__init__.py", line 1706, in callHandlers
    hdlr.handle(record)
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/logging/__init__.py", line 978, in handle
    self.emit(record)
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/logging/handlers.py", line 1500, in emit
    self.handleError(record)
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/logging/__init__.py", line 1032, in handleError
    traceback.print_exception(t, v, tb, None, sys.stderr)
    ^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'function' object has no attribute 'print_exception'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/logging/handlers.py", line 1498, in emit
    self.enqueue(self.prepare(record))
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/logging/handlers.py", line 1456, in enqueue
    self.queue.put_nowait(record)
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/multiprocess/queues.py", line 141, in put_nowait
    return self.put(obj, False)
           ^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/multiprocess/queues.py", line 93, in put
    raise Full
queue.Full

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.11/bin/ofscraper", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/ofscraper/__main__.py", line 10, in main
    start.main()
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/ofscraper/start.py", line 112, in main
    raise E
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/ofscraper/start.py", line 109, in main
    raise E
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/ofscraper/start.py", line 62, in main
    manual.manual_download()
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/ofscraper/commands/manual.py", line 36, in manual_download
    misc.download_picker( username,
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/ofscraper/utils/misc.py", line 45, in download_picker
    return download.process_dicts(
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/ofscraper/utils/run_async.py", line 9, in inner
    tasks=loop.run_until_complete(coro(*args,**kwargs))
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/asyncio/base_events.py", line 653, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/ofscraper/utils/download.py", line 194, in process_dicts
    log.traceback(e)
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/ofscraper/utils/logger.py", line 187, in inner
    self._log(level, message, args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/logging/__init__.py", line 1634, in _log
    self.handle(record)
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/logging/__init__.py", line 1644, in handle
    self.callHandlers(record)
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/logging/__init__.py", line 1706, in callHandlers
    hdlr.handle(record)
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/logging/__init__.py", line 978, in handle
    self.emit(record)
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/logging/handlers.py", line 1500, in emit
    self.handleError(record)
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/logging/__init__.py", line 1032, in handleError
    traceback.print_exception(t, v, tb, None, sys.stderr)
    ^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'function' object has no attribute 'print_exception'`

**Comment by datawhores** [comment]
I made a change in 3.3.4 that should hopefully help with this

**Comment by dipankar-okcredit** [comment]
@datawhores I see the latest release is 3.3.3 I guess 3.3.4 will be released in some time.

**Comment by datawhores** [comment]
I think there might have been a bug fix here that was fixed

Anyways I'm closing this issue
please make a new issue if this persists
