### ISSUE TITLE
error downloading ffmpeg via script

### ISSUE THREAD

**Issue by reahari** [datawhores/OF-Scraper#203]
**Describe the bug**
When I run the script it checks to see if ffmpeg is installed. When it can't find it I instruct it to download it but then I get permissions issues and I can't tell if it has installed.

**Screenshots/Logs**
```
? What would you like to do? Download content from a user
You need to select path for ffmpeg


[Errno 13] Permission denied: ''
Traceback (most recent call last):
  File "/home/$USER/.local/pipx/venvs/ofscraper/lib/python3.11/site-packages/ofscraper/utils/paths.py", line 194, in ffmpegexecutecheck
    t=subprocess.run([x],stdout=subprocess.PIPE,stderr=subprocess.PIPE)
      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/subprocess.py", line 548, in run
    with Popen(*popenargs, **kwargs) as process:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/subprocess.py", line 1026, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.11/subprocess.py", line 1950, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
PermissionError: [Errno 13] Permission denied: ''

? ffmpeg not found would you like to auto install? Yes
```

**Desktop (please complete the following information):**
 - Ubuntu 23.04
 - Firefox
 - 116
- python 
- installed via pipx

**Comment by BosonHair** [comment]
What's your config look like? Maybe it doesn't have proper permissions.

**Comment by datawhores** [comment]
Oh does the script continue after that
> It is just an infinite loop so it should exit when the test fail

Could make the success statement more clear

**Comment by reahari** [comment]
The script does continue afterwards so I think it is just an infinite loop
