### ISSUE TITLE
Failed downloads 

### ISSUE THREAD

**Issue by Goku10101** [datawhores/OF-Scraper#220]
I’m on the latest release and have setup my CDM properly but I’m still getting tons of failed downloads.  It’s only for certain creators. What causes failed downloads

**Comment by dl8806** [comment]
been happening to me as well and my favorite ones at that. I've been using with no issue for  a minute now.  My CDM is properly installed as well. Not sure how it could be resolved.

**Comment by datawhores** [comment]
Please send a log

**Comment by dl8806** [comment]
Here's the most recent logs i've ran. I downgraded to 3.3.3 from 3.3.6.

**Comment by Goku10101** [comment]
I’m on 3.3.6 and get message at launch CDM seems to be working. Also just noticed it’s leaving temp audio and temp videos files behind where it fails. I saw the other closed ticket about this my cdm is discord.

**Comment by datawhores** [comment]
It just a network check

It still needs to be configured correctly
All the working  CDM require some user configuration at this point 
Would need a log and to see your config to know for sure

**Comment by dl8806** [comment]
So what do i need to do send another log and the config file that’s
currently setup?

**Comment by dl8806** [comment]
> It just a network check
> 
> It still needs to be configured correctly All the working CDM require some user configuration at this point Would need a log and to see your config to know for sure

[ofscraper_main_profile_2023-10-01.log](https://github.com/datawhores/OF-Scraper/files/12779453/ofscraper_main_profile_2023-10-01.log)
heres latest log and txt of my config

{
    "config": {
        "main_profile": "main_profile",
        "save_location": "C:\\Users\\dlama\\Downloads\\ofscraper",
        "file_size_limit": 0,
        "file_size_min": 0,
        "dir_format": "{model_username}/{responsetype}/{mediatype}/",
        "file_format": "{filename}.{ext}",
        "textlength": 0,
        "space-replacer": " ",
        "date": "MM-DD-YYYY",
        "metadata": "{configpath}/{profile}/.data/{model_username}_{model_id}",
        "filter": [
            "Images",
            "Videos"
        ],
        "threads": 15,
        "code-execution": false,
        "custom": "null",
        "mp4decrypt": "C:\\Users\\dlama\\.config\\ofscraper\\bin\\mp4decrypt.exe",
        "ffmpeg": "C:\\Users\\dlama\\.config\\ofscraper\\bin\\ffmpeg.exe",
        "discord": "",
        "private-key": "\"C:\\Users\\dlama\\Downloads\\device_private_key.pem\"",
        "client-id": "\"C:\\Users\\dlama\\Downloads\\device_client_id_blob.bin\"",
        "key-mode-default": "manual",
        "keydb_api": "",
        "dynamic-mode-default": "deviint",
        "partfileclean": false,
        "backend": "aio",
        "download-sems": 5,
        "maxfile-sem": 0,
        "downloadbars": true,
        "cache-mode": "sqlite",
        "responsetype": {
            "timeline": "Posts",
            "message": "Messages",
            "archived": "Archived",
            "paid": "Messages",
            "stories": "Stories",
            "highlights": "Stories",
            "profile": "Profile",
            "pinned": "Posts"
        }
    }
}

**Comment by misterscraper** [comment]
anyone fix the failed downloads issue?

**Comment by datawhores** [comment]
you have you private_key and client_id quoted
python seems to be taking the that as the literal name of the path

**Comment by dl8806** [comment]
ok let me try that and see. thx

**Comment by dl8806** [comment]
I removed the inner quote and got "Invalid control character at: Line 23 column 81 (char 880), when prompted how do i want to fix the issue, i did Reset Default. and run the of creator I had been having problems with and it worked with no issue. guess thats all it took. Thanks

**Comment by dl8806** [comment]
Spoke to soon lol. now it's letting all the downloads go through but all part audio/video files, i will try and setup cdrm again to see if that helps

**Comment by RobTuckfield** [comment]
I'm getting a lot of failures using both manual and keydb. Here's what I think the relevant error is (I can post more of the log if needed). This error gets thrown the same number of time as failed downloads. 

`2023-10-10 00:19:47:\[download.process_dicts:202]  local variable 'fileobject' referenced before assignment
 2023-10-10 00:19:47:\[download.process_dicts:203]  Traceback (most recent call last):
  File "C:\Users\Rob\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\ofscraper\utils\download.py", line 198, in process_dicts
    pack= await coro
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\asyncio\tasks.py", line 571, in _wait_for_one
    return f.result()  # May raise f.exception().
  File "C:\Users\Rob\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\ofscraper\utils\download.py", line 275, in download
    return await alt_download_helper(c,ele,pathlib.Path(".").absolute(),username,model_id,progress)
  File "C:\Users\Rob\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\ofscraper\utils\download.py", line 431, in alt_download_helper
    audio=await alt_download_downloader(audio,c,ele,path,progress)
  File "C:\Users\Rob\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\ofscraper\utils\download.py", line 608, in alt_download_downloader
    return await inner(item,c,ele,progress)
  File "C:\Users\Rob\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\tenacity\_asyncio.py", line 88, in async_wrapped
    return await fn(*args, **kwargs)
  File "C:\Users\Rob\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\tenacity\_asyncio.py", line 47, in __call__
    do = self.iter(retry_state=retry_state)
  File "C:\Users\Rob\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\tenacity\__init__.py", line 325, in iter
    raise retry_exc.reraise()
  File "C:\Users\Rob\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\tenacity\__init__.py", line 158, in reraise
    raise self.last_attempt.result()
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\concurrent\futures\_base.py", line 451, in result
    return self.__get_result()
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\concurrent\futures\_base.py", line 403, in __get_result
    raise self._exception
  File "C:\Users\Rob\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\tenacity\_asyncio.py", line 50, in __call__
    result = await fn(*args, **kwargs)
  File "C:\Users\Rob\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\ofscraper\utils\download.py", line 103, in inner
    raise E
  File "C:\Users\Rob\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\ofscraper\utils\download.py", line 101, in inner
    return await func(*args,**kwargs)
  File "C:\Users\Rob\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\ofscraper\utils\download.py", line 606, in inner
    if fileobject:await fileobject.close()
UnboundLocalError: local variable 'fileobject' referenced before assignment`

Relevant config:

`        "private-key": "C:/dumper-main/keys/device_private_key.pem",
        "client-id": "C:/dumper-main/keys/device_client_id.bin",
        "key-mode-default": "manual",
        "keydb_api": "<api_key_replaced_for_privacy>",`

**Comment by Robert-Botert** [comment]
I'm also getting a lot of failures using manual and keydb. 

This error in the log gets thrown the same number of times as failed download. I can post more of the log if it's helpful. 

```
 2023-10-10 00:20:13:\[download.process_dicts:202]  local variable 'fileobject' referenced before assignment
 2023-10-10 00:20:13:\[download.process_dicts:203]  Traceback (most recent call last):
  File "C:\Users\Rob\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\ofscraper\utils\download.py", line 198, in process_dicts
    pack= await coro
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\asyncio\tasks.py", line 571, in _wait_for_one
    return f.result()  # May raise f.exception().
  File "C:\Users\Rob\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\ofscraper\utils\download.py", line 275, in download
    return await alt_download_helper(c,ele,pathlib.Path(".").absolute(),username,model_id,progress)
  File "C:\Users\Rob\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\ofscraper\utils\download.py", line 431, in alt_download_helper
    audio=await alt_download_downloader(audio,c,ele,path,progress)
  File "C:\Users\Rob\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\ofscraper\utils\download.py", line 608, in alt_download_downloader
    return await inner(item,c,ele,progress)
  File "C:\Users\Rob\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\tenacity\_asyncio.py", line 88, in async_wrapped
    return await fn(*args, **kwargs)
  File "C:\Users\Rob\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\tenacity\_asyncio.py", line 47, in __call__
    do = self.iter(retry_state=retry_state)
  File "C:\Users\Rob\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\tenacity\__init__.py", line 325, in iter
    raise retry_exc.reraise()
  File "C:\Users\Rob\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\tenacity\__init__.py", line 158, in reraise
    raise self.last_attempt.result()
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\concurrent\futures\_base.py", line 451, in result
    return self.__get_result()
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\concurrent\futures\_base.py", line 403, in __get_result
    raise self._exception
  File "C:\Users\Rob\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\tenacity\_asyncio.py", line 50, in __call__
    result = await fn(*args, **kwargs)
  File "C:\Users\Rob\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\ofscraper\utils\download.py", line 103, in inner
    raise E
  File "C:\Users\Rob\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\ofscraper\utils\download.py", line 101, in inner
    return await func(*args,**kwargs)
  File "C:\Users\Rob\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\ofscraper\utils\download.py", line 606, in inner
    if fileobject:await fileobject.close()
UnboundLocalError: local variable 'fileobject' referenced before assignment
```

Relevant part of the config. Like I said, I've tried using manual and keydb. Both should be configured, I just switch "key-mode-default"

I've tried changing around the slashes in the path to the private key and client ID paths. // and \ primarily. 

```
        "private-key": "C:/dumper-main/keys/device_private_key.pem",
        "client-id": "C:/dumper-main/keys/device_client_id.bin",
        "key-mode-default": "manual",
        "keydb_api": "<api_key_replaced_for_github_comment>",
```

**Comment by Goku10101** [comment]
sorry about the late reply here is my config. I changed my key to XXX. Also I edited the config manually so i just tried doing to prompted version by going to advance config settings. I does a speed test and errors and pulls up json for me to change. not sure if its related. @datawhores 

{
    "config": {
        "main_profile": "main_profile",
        "save_location": "/Users/positano/Data/ofscraper",
        "file_size_limit": 0,
        "file_size_min": 0,
        "dir_format": "{model_username}/{responsetype}/{mediatype}/",
        "file_format": "{filename}.{ext}",
        "textlength": "0",
        "space-replacer": " ",
        "date": "MM-DD-YYYY",
        "metadata": "{configpath}/{profile}/.data/{model_username}_{model_id}",
        "filter": [
            "Images",
            "Audios",
            "Videos"
        ],
        "threads": 8,
        "code-execution": false,
        "custom": null,
        "mp4decrypt": "/usr/local/bin/mp4decrypt",
        "ffmpeg": "/usr/local/bin/ffmpeg",
        "discord": "",
        "private-key": null,
        "client-id": null,
        "key-mode-default": "keydb",
        "keydb_api": “XXX:XXx”,
        "dynamic-mode-default": "deviint",
        "partfileclean": false,
        "backend": "aio",
        "download-sems": 20,
        "maxfile-sem": 0,
        "downloadbars": false,
        "cache-mode": "sqlite",
        "responsetype": {
            "timeline": "posts",
            "archived": "archived",
            "pinned": "posts",
            "message": "messages",
            "paid": "messages",
            "stories": "stories",
            "highlights": "stories",
            "profile": "profile"
        }
    }
}

**Comment by fightcancer2** [comment]
Same issue here using versions 3.3.3 and 3.3.10.

**Comment by datawhores** [comment]
There were some changes to the code base upgrade to 3.4, and make an new issue if this persists
