### ISSUE TITLE
Error while scraping

### ISSUE THREAD

**Issue by dia-val** [datawhores/OF-Scraper#221]
I get this error since today. Any idea why? Up until yesterday it seemed to work fine and i am on latest docker version/commit main.

2023-09-30 07:43:50:\[scraper.normal_post_process:179]  Getting All for ------
Subscription Active: True
 2023-09-30 07:45:48:\[logger.inner:193]  failed with exception: 1
 2023-09-30 07:45:48:\[logger.inner:193]  Traceback (most recent call last):
  File "/home/ofscraper/app/ofscraper/commands/scraper.py", line 181, in normal_post_process
    model_id = profile.get_id( ele["name"])
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ofscraper/app/ofscraper/api/profile.py", line 108, in get_id
    return get_id_helper(c,username)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ofscraper/app/.venv/lib/python3.11/site-packages/tenacity/__init__.py", line 289, in wrapped_f
    return self(f, *args, **kw)
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/ofscraper/app/.venv/lib/python3.11/site-packages/tenacity/__init__.py", line 379, in __call__
    do = self.iter(retry_state=retry_state)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ofscraper/app/.venv/lib/python3.11/site-packages/tenacity/__init__.py", line 325, in iter
    raise retry_exc.reraise()
          ^^^^^^^^^^^^^^^^^^^
  File "/home/ofscraper/app/.venv/lib/python3.11/site-packages/tenacity/__init__.py", line 158, in reraise
    raise self.last_attempt.result()
          ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/concurrent/futures/_base.py", line 449, in result
    return self.__get_result()
           ^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/concurrent/futures/_base.py", line 401, in __get_result
    raise self._exception
  File "/home/ofscraper/app/.venv/lib/python3.11/site-packages/tenacity/__init__.py", line 382, in __call__
    result = fn(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^
  File "/home/ofscraper/app/ofscraper/api/profile.py", line 116, in get_id_helper
    cache = Cache(getcachepath(),disk=config_.get_cache_mode(config_.read_config()))
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ofscraper/app/.venv/lib/python3.11/site-packages/diskcache/core.py", line 537, in __init__
    query = EVICTION_POLICY[self.eviction_policy]['init']
            ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^
KeyError: 1

 2023-09-30 07:45:48:\[scraper.scrape_context_manager:380]  
===========================
Script Finished
Run Time:  0:01:58
===========================

**Comment by havingfun2500** [comment]
I have the same issue and I don't know how to fix it. Tried installing the 3.3.3 version but still get stuck without downloading anything.
