### ISSUE TITLE
ffmpeg binary fails to download on macOS

### ISSUE THREAD

**Issue by mooangus** [datawhores/OF-Scraper#226]
**Describe the bug**
The application fails when it tries to download ffmpeg and exits. Tested on two separate macOS devices.

**To Reproduce**
macOS on M1, new install, Python 3.9.6, 2023.10.09_00:17_main_809c9a8_package

Attempt to download content, when prompted to install ffmpeg, application fails with exit codes.

**Expected behavior**
For the application to download ffmpeg and continue.

**Screenshots/Logs**
? What would you like to do? Download content from a user
You need to select path for ffmpeg

[Errno 13] Permission denied: ''
Traceback (most recent call last):
  File "utils/paths.py", line 194, in ffmpegexecutecheck
  File "subprocess.py", line 548, in run
  File "subprocess.py", line 1026, in __init__
  File "subprocess.py", line 1950, in _execute_child
PermissionError: [Errno 13] Permission denied: ''

? ffmpeg not found would you like to auto install? Yes

Traceback (most recent call last):
  File "__main__.py", line 15, in <module>
  File "__main__.py", line 10, in main
  File "start.py", line 129, in main
  File "start.py", line 126, in main
  File "start.py", line 62, in main
  File "commands/scraper.py", line 416, in main
  File "commands/scraper.py", line 398, in main
  File "commands/scraper.py", line 429, in scrapper
  File "utils/exit.py", line 89, in inner
  File "utils/exit.py", line 82, in inner
  File "commands/scraper.py", line 57, in process_prompts
  File "commands/scraper.py", line 356, in check_config
  File "utils/config.py", line 229, in update_ffmpeg
  File "utils/binaries.py", line 35, in ffmpeg_download
  File "utils/binaries.py", line 170, in ffmpeg_mac
  File "httpx/_models.py", line 227, in __getitem__
KeyError: 'Content-Length'
[78957] Failed to execute script '__main__' due to unhandled exception!

**Desktop (please complete the following information):**
 - OS: macOS 14.0
 - Browser Firefox
 - Version 118.0.1
- binary ofscraper_macos_809c9a8

**Comment by Puk0** [comment]
Actuliza tu python 3.9.6 a 3.12.0
