### ISSUE TITLE
Not really an issue, so sorry if this is the wrong place!

### ISSUE THREAD

**Issue by tallgirlsfinishlast** [datawhores/OF-Scraper#229]
Is there a way that you can effectively clear all traces of the scraper from your system and do a fresh install?? I keep getting this error when I try to set my path to install ffmpeg and I believe its something I did, and so rather than drive myself nuts I feel like best course of action would be to just restart the install from the beginning.

Heres my terminal output, if anybody can guide me please lmk! Thank you.

 [start.startvalues:159]  config path:                              start.py:159
/Users/your_username/.config/ofscraper/config.json                              
 [start.startvalues:160]  profile path:                             start.py:160
/Users/your_username/.config/ofscraper/main_profile                             
 [start.startvalues:161]  log folder:                               start.py:161
/Users/your_username/.config/ofscraper/logging                                  
Welcome to OF-Scraper Version 3.3.10
CDM service cdrm2 timed out and seems to be down
This may cause a lot of failed downloads
Please confirm by checking the url:http://172.106.17.134:8080/wv
 Consider switching
https://of-scraper.gitbook.io/of-scraper/cdm-options

? What would you like to do? Download content from a user
You need to select path for ffmpeg

[Errno 2] No such file or directory: '/Users/christy/.config/ofscraper/bin/ffmpeg'
Traceback (most recent call last):
  File "/Users/christy/.local/pipx/venvs/ofscraper/lib/python3.10/site-packages/ofscraper/utils/paths.py", line 194, in ffmpegexecutecheck
    t=subprocess.run([x],stdout=subprocess.PIPE,stderr=subprocess.PIPE)
  File "/Users/christy/.pyenv/versions/3.10.12/lib/python3.10/subprocess.py", line 503, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/Users/christy/.pyenv/versions/3.10.12/lib/python3.10/subprocess.py", line 971, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/Users/christy/.pyenv/versions/3.10.12/lib/python3.10/subprocess.py", line 1863, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: '/Users/christy/.config/ofscraper/bin/ffmpeg'

? ffmpeg not found would you like to auto install? Yes

Traceback (most recent call last):
  File "/Users/christy/.local/bin/ofscraper", line 8, in <module>
    sys.exit(main())
  File "/Users/christy/.local/pipx/venvs/ofscraper/lib/python3.10/site-packages/ofscraper/__main__.py", line 10, in main
    start.main()
  File "/Users/christy/.local/pipx/venvs/ofscraper/lib/python3.10/site-packages/ofscraper/start.py", line 129, in main
    raise E
  File "/Users/christy/.local/pipx/venvs/ofscraper/lib/python3.10/site-packages/ofscraper/start.py", line 126, in main
    raise E
  File "/Users/christy/.local/pipx/venvs/ofscraper/lib/python3.10/site-packages/ofscraper/start.py", line 62, in main
    scraper.main()
  File "/Users/christy/.local/pipx/venvs/ofscraper/lib/python3.10/site-packages/ofscraper/commands/scraper.py", line 416, in main
    raise E
  File "/Users/christy/.local/pipx/venvs/ofscraper/lib/python3.10/site-packages/ofscraper/commands/scraper.py", line 398, in main
    scrapper()
  File "/Users/christy/.local/pipx/venvs/ofscraper/lib/python3.10/site-packages/ofscraper/commands/scraper.py", line 429, in scrapper
    process_prompts()
  File "/Users/christy/.local/pipx/venvs/ofscraper/lib/python3.10/site-packages/ofscraper/utils/exit.py", line 89, in inner
    raise E
  File "/Users/christy/.local/pipx/venvs/ofscraper/lib/python3.10/site-packages/ofscraper/utils/exit.py", line 82, in inner
    func(*args,**kwargs)
  File "/Users/christy/.local/pipx/venvs/ofscraper/lib/python3.10/site-packages/ofscraper/commands/scraper.py", line 57, in process_prompts
    check_config()
  File "/Users/christy/.local/pipx/venvs/ofscraper/lib/python3.10/site-packages/ofscraper/commands/scraper.py", line 356, in check_config
    config.update_ffmpeg()
  File "/Users/christy/.local/pipx/venvs/ofscraper/lib/python3.10/site-packages/ofscraper/utils/config.py", line 229, in update_ffmpeg
    config["config"]["ffmpeg"]=binaries.ffmpeg_download()
  File "/Users/christy/.local/pipx/venvs/ofscraper/lib/python3.10/site-packages/ofscraper/utils/binaries.py", line 35, in ffmpeg_download
    return ffmpeg_mac() 
  File "/Users/christy/.local/pipx/venvs/ofscraper/lib/python3.10/site-packages/ofscraper/utils/binaries.py", line 170, in ffmpeg_mac
    total = int(r.headers['Content-Length'])
  File "/Users/christy/.local/pipx/venvs/ofscraper/lib/python3.10/site-packages/httpx/_models.py", line 227, in __getitem__
    raise KeyError(key)
KeyError: 'Content-Length'

**Comment by Puk0** [comment]
1. instala o actualiza python a 3.12
2. borra la carpeta .config
3. Abre el programa
4. introduce los datos que te pide dentro del programa
5. cierralo
6. edita manualmente el config.json
- la ruta del directorio de mp4decrypt
- la ruta del directorio de ffmpeg
- y "key-mode-default"

En "key-mode-default" tienes 2 opciones:
- manual o keydb

- En manual ocupas los 2 archivos  y las rutas de las carpetas de: device_private_key y device_client_id_blob
- En keydb solo ocupas la "keydb_api" que esta en keysdb.net/api

**Comment by tallgirlsfinishlast** [comment]
> 1. instala o actualiza python a 3.12
> 
>     2. borra la carpeta .config
> 
>     3. Abre el programa
> 
>     4. introduce los datos que te pide dentro del programa
> 
>     5. cierralo
> 
>     6. edita manualmente el config.json
> 
> 
>     * la ruta del directorio de mp4decrypt
> 
>     * la ruta del directorio de ffmpeg
> 
>     * y "key-mode-default"
> 
> 
> En "key-mode-default" tienes 2 opciones:
> 
>     * manual o keydb
> 
>     * En manual ocupas los 2 archivos  y las rutas de las carpetas de: device_private_key y device_client_id_blob
> 
>     * En keydb solo ocupas la "keydb_api" que esta en keysdb.net/api
Muchas gracias. Te haré saber cómo funciona una vez que lo haga. Aparte de las cosas que tienen diferentes nombres y una estructura de archivos diferente, estos pasos serían los mismos si esto estuviera en MacOS? 
(Además, disculpas si mi español es terrible Im usando un traductor LOL)

**Comment by Puk0** [comment]
si, solo cambian las rutas de las carpetas y la extensión del programa:

C:\\Ffmpeg\\Shared\\ffmpeg.exe",
/Users/hero/.config/ofscraper/bin/ffmpeg
