### ISSUE TITLE
Seeing size mixmatch error

### ISSUE THREAD

**Issue by OpenFieldsOfOz** [datawhores/OF-Scraper#249]
Whenever I try to scrape, I end up with no new files (since end of Sept). The logs all this message, or something similar. This may be related to #246, though my current file doesn't *always* appear to be empty as in that issue.

```
2023-10-29 04:36:16:\[download.inner:410]  Traceback (most recent call last):
  File "/home/your_username/.local/lib/python3.10/site-packages/ofscraper/utils/download.py", line 401, in inner
    size_checker(temp,ele,total)
  File "/home/your_username/.local/lib/python3.10/site-packages/ofscraper/utils/download.py", line 250, in size_checker
    raise Exception(s)
Exception: Media:3039176427 Post:757801391 0hikhr0nboiuzzfifbmk8_source size mixmatch target: 1578018806 vs current file: 1577279602

 2023-10-29 04:36:16:\[download.inner:411]  Media:3039176427 Post:757801391 0hikhr0nboiuzzfifbmk8_source size mixmatch target: 1578018806 vs current file: 1577279602
 2023-10-29 04:36:22:\[download.inner:410]  Traceback (most recent call last):
  File "/home/your_username/.local/lib/python3.10/site-packages/ofscraper/utils/download.py", line 401, in inner
    size_checker(temp,ele,total)
  File "/home/your_username/.local/lib/python3.10/site-packages/ofscraper/utils/download.py", line 250, in size_checker
    raise Exception(s)
Exception: Media:3053390817 Post:772663217 0hiytgxosbrs5y8brxhtv_source size mixmatch target: 847115007 vs current file: 846798201
```

It looks like this error is thrown when the `content-length` reported in the request doesn't match the size on disk. Not sure why or when this would happen.

**Desktop (please complete the following information):**
 - OS: Ubuntu 22.04
 - Browser Chrome
- python version: Python 3.10.12
- ofscraper version: 3.3.11 (latest in github)

**Comment by icetail** [comment]
have the same problem. I went back to version 3.3.5. I don't have the problem with that version

**Comment by OpenFieldsOfOz** [comment]
This seems to be a partial solution. A fraction of the the files now download, instead of all failing. But some files still generate this error

```
  File "/home/your_username/.local/lib/python3.10/site-packages/ofscraper/utils/downloadbatch.py", line 385, in process_dicts_split
    pack = await coro
  File "/usr/lib/python3.10/asyncio/tasks.py", line 571, in _wait_for_one
    return f.result()  # May raise f.exception().
  File "/home/your_username/.local/lib/python3.10/site-packages/ofscraper/utils/downloadbatch.py", line 453, in download
    raise e
  File "/home/your_username/.local/lib/python3.10/site-packages/ofscraper/utils/downloadbatch.py", line 447, in download
    return await main_download_helper(c,ele,pathlib.Path(".").absolute(),username,model_id)
  File "/home/your_username/.local/lib/python3.10/site-packages/ofscraper/utils/downloadbatch.py", line 485, in main_download_helper
    raise Exception(f"{get_medialog(ele)} smaller then previous file")
Exception: Media:2992760478 Post:711455365 smaller then previous file
```

**Comment by datawhores** [comment]
Might be related to the fix in 3.3.13

**Comment by datawhores** [comment]
see @254

**Comment by OpenFieldsOfOz** [comment]
I just installed based on master, seeing many fewer errors. Thank you! I'm still ocasionally seeing

```
 2023-11-16 15:58:49:\[download.process_dicts:202]  Media:2978470280 Post:698004862 smaller then previous file
 2023-11-16 15:58:49:\[download.process_dicts:203]  Traceback (most recent call last):
  File "/home/your_username/.local/lib/python3.10/site-packages/ofscraper/utils/download.py", line 198, in process_dicts
    pack= await coro
  File "/usr/lib/python3.10/asyncio/tasks.py", line 571, in _wait_for_one
    return f.result()  # May raise f.exception().
  File "/home/your_username/.local/lib/python3.10/site-packages/ofscraper/utils/download.py", line 273, in download
    return await main_download_helper(c,ele,pathlib.Path(".").absolute(),username,model_id,progress)
  File "/home/your_username/.local/lib/python3.10/site-packages/ofscraper/utils/download.py", line 302, in main_download_helper
    raise Exception(f"{get_medialog(ele)} smaller then previous file")
Exception: Media:2978470280 Post:698004862 smaller then previous file
```
