### ISSUE TITLE
Updated to 3.3.11 and got this error ValueError: not enough values to unpack (expected 3, got 2)

### ISSUE THREAD

**Issue by HelpfulDucker** [datawhores/OF-Scraper#250]
**Describe the bug**
After updating to the latest version 3.3.11, video download fail.

When a new video has finished downloading, it couldn't be processed by the script and the download would restart. This results in a never ending loop.

**To Reproduce**
Run the script as per normal. 

**Screenshots/Logs**
```
2023-10-29 16:00:48:\[downloadbatch.check_forced_skip:440]  Media:2469057389 Post:332555500 under size min
 2023-10-29 16:00:48:\[downloadbatch.download:455]  Media:2469057389 Post:332555500 exception not enough values to unpack (expected 3, got 2)
 2023-10-29 16:00:48:\[downloadbatch.download:456]  Media:2469057389 Post:332555500 exception Traceback (most recent call last):
  File "/home/your_username/.local/pipx/venvs/ofscraper/lib/python3.11/site-packages/ofscraper/utils/downloadbatch.py", line 451, in download
    return await main_download_helper(c,ele,pathlib.Path(".").absolute(),username,model_id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/your_username/.local/pipx/venvs/ofscraper/lib/python3.11/site-packages/ofscraper/utils/downloadbatch.py", line 470, in main_download_helper
    total ,temp,path_to_file=result
    ^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: not enough values to unpack (expected 3, got 2)

 2023-10-29 16:00:48:\[paths._linux_truncateHelper:158]  path: /mnt/misc-download/OnlyFans/euyuridiaz/Posts/Free/Videos/0gpax7qyyldtrxk0t0u7f_source_2075857065.part filename bytesize: 44
 2023-10-29 16:00:48:\[paths._linux_truncateHelper:158]  path: /mnt/misc-download/OnlyFans/euyuridiaz/Posts/Free/Videos/0gyvxm341etdr04dlx30e_source_2346651349.part filename bytesize: 44
 2023-10-29 16:00:48:\[paths._linux_truncateHelper:158]  path: /mnt/misc-download/OnlyFans/euyuridiaz/Posts/Free/Videos/210407 0gpax7qyyldtrxk0t0u7f_source.mp4 filename bytesize: 39
 2023-10-29 16:00:48:\[paths._linux_truncateHelper:158]  path: /mnt/misc-download/OnlyFans/euyuridiaz/Posts/Free/Videos/220130 0gyvxm341etdr04dlx30e_source.mp4 filename bytesize: 39
 2023-10-29 16:00:48:\[downloadbatch.main_download_helper:465]  Media:2802405311 Post:539538797 Downloading with normal downloader
 2023-10-29 16:00:48:\[downloadbatch.check_forced_skip:440]  Media:2802405311 Post:539538797 under size min
 2023-10-29 16:00:48:\[paths._linux_truncateHelper:158]  path: /mnt/misc-download/OnlyFans/euyuridiaz/Posts/Free/Videos/0h1y44jv6do7acwga0uzh_source_2445913782.part filename bytesize: 44
 2023-10-29 16:00:48:\[downloadbatch.download:455]  Media:2802405311 Post:539538797 exception not enough values to unpack (expected 3, got 2)
 2023-10-29 16:00:48:\[downloadbatch.download:456]  Media:2802405311 Post:539538797 exception Traceback (most recent call last):
  File "/home/your_username/.local/pipx/venvs/ofscraper/lib/python3.11/site-packages/ofscraper/utils/downloadbatch.py", line 451, in download
    return await main_download_helper(c,ele,pathlib.Path(".").absolute(),username,model_id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/your_username/.local/pipx/venvs/ofscraper/lib/python3.11/site-packages/ofscraper/utils/downloadbatch.py", line 470, in main_download_helper
    total ,temp,path_to_file=result
    ^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: not enough values to unpack (expected 3, got 2)

 2023-10-29 16:00:48:\[downloadbatch.main_download_helper:465]  Media:2075857065 Post:131873020 Downloading with normal downloader
 2023-10-29 16:00:48:\[downloadbatch.check_forced_skip:440]  Media:2075857065 Post:131873020 under size min
 2023-10-29 16:00:48:\[downloadbatch.download:455]  Media:2075857065 Post:131873020 exception not enough values to unpack (expected 3, got 2)
 2023-10-29 16:00:48:\[downloadbatch.download:456]  Media:2075857065 Post:131873020 exception Traceback (most recent call last):
  File "/home/your_username/.local/pipx/venvs/ofscraper/lib/python3.11/site-packages/ofscraper/utils/downloadbatch.py", line 451, in download
    return await main_download_helper(c,ele,pathlib.Path(".").absolute(),username,model_id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/your_username/.local/pipx/venvs/ofscraper/lib/python3.11/site-packages/ofscraper/utils/downloadbatch.py", line 470, in main_download_helper
    total ,temp,path_to_file=result
    ^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: not enough values to unpack (expected 3, got 2)

```

**Desktop (please complete the following information):**
 - OS: Ubuntu 23.04
 - Browser: Chrome
 - Version: 3.3.11
- binary or python: Python
- python version if installed via pip or pypi: pipx

**Comment by cjb900** [comment]
There are some issues with the latest version. I use version 3.3.3 my self with no issues.

**Comment by HelpfulDucker** [comment]
> There are some issues with the latest version. I use version 3.3.3 my self with no issues.

Thanks! I reverted to 3.3.3 and it seems to be downloading normally again.

**Comment by datawhores** [comment]
This should be fixed in the newer version
3.4 for example 
If this issue persists open a new issue
