### ISSUE TITLE
Part files downloaded then immediately deleted

### ISSUE THREAD

**Issue by adamperez** [datawhores/OF-Scraper#254]
**Describe the bug**
Using cdrm2, I can download files from a profile; I see the `*.part` files downloaded, then immediately deleted from local disk.

**To Reproduce**
* Pull any model's profile and try to download

**Expected behavior**
Files should be downloaded as expected.

**Screenshots/Logs**
n/a

**Desktop (please complete the following information):**
 - OS: OS X, latest
 - Browser Chrome, latest
- binary or python 
- python version if installed via pip or pypi (installed via pip, ofscraper v3.3.10)

**Additional context**

**Comment by adamperez** [comment]
Update: ran with debug on and I see this error firing

```
TRACEBACK  [logger.inner:193]  Traceback (most recent call last):                                                                                                                                                                logger.py:193
            File "/Users/your_username/.pyenv/versions/3.11.1/lib/python3.11/contextlib.py", line 222, in __aexit__
              await self.gen.athrow(typ, value, traceback)
            File "/Users/your_username/.pyenv/versions/3.11.1/lib/python3.11/site-packages/ofscraper/classes/sessionbuilder.py", line 146, in _aio_funct_async
              yield r
            File "/Users/your_username/.pyenv/versions/3.11.1/lib/python3.11/site-packages/ofscraper/utils/download.py", line 401, in inner
              size_checker(temp,ele,total)
            File "/Users/your_username/.pyenv/versions/3.11.1/lib/python3.11/site-packages/ofscraper/utils/download.py", line 250, in size_checker
              raise Exception(s)
          Exception: Media:3004964113 Post:2168835679749 3024x4032_90f8a0d9632319752b6cf201dbb9b91b size mixmatch target: 1449702 vs current file: 1031622
```

**Comment by PsychoSid** [comment]
This has been seen in the latest version https://github.com/datawhores/OF-Scraper/issues/249 & https://github.com/datawhores/OF-Scraper/issues/246 also raised for this.

I downgraded to 3.3.7 to "resolve" it.

**Comment by adamperez** [comment]
@PsychoSid ah great idea, let me try that on my local ...

**Comment by adamperez** [comment]
@PsychoSid cool i think that worked! interestingly though, on v3.3.5, I can't see all models that I would be able to scrape paid content for; e.g.: I'm currently unsubbed to one profile, and would expect to be able to download messages from them, but that profile doesn't show up in the list.

**Comment by PsychoSid** [comment]
Yeah I think I see the same I explicitly set mine with `-u` but I only have 4 anyway so it's easy for me.

**Comment by Puk0** [comment]
Es porque el sitio donde hace la petición (cdrm2) para obtener las KID esta caido, solo te descargara los archivos encriptados (.part) y si en el programa le pones "partfileclean": true, te los borra 

Usa "key-mode-default" manual o keydb

**Comment by Jarsky** [comment]
Also getting this on 3.3.11:

`Progress: (0 photos, 0 videos, 0 audios, 0 skipped, 33 failed || 33/33||0 B/377.22 MB) ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 100% 0:02:41`

With this in the logs:
```
 2023-11-12 07:22:55:\[logger.inner:193]  Traceback (most recent call last):
  File "/usr/lib/python3.11/contextlib.py", line 222, in __aexit__
    await self.gen.athrow(typ, value, traceback)
  File "/home/your_username/app/your_username/classes/sessionbuilder.py", line 146, in _aio_funct_async
    yield r
  File "/home/your_username/app/your_username/utils/download.py", line 401, in inner
    size_checker(temp,ele,total)
  File "/home/your_username/app/your_username/utils/download.py", line 250, in size_checker
    raise Exception(s)
Exception: Media:3069412081 Post:789443662 0hjeacla2vsrmfywhmtc1_source size mixmatch target: 10785016 vs current file: 10026844

 2023-11-12 07:22:55:\[logger.inner:193]  Media:3069412081 Post:789443662 0hjeacla2vsrmfywhmtc1_source size mixmatch target: 10785016 vs current file: 10026844
```

Reverting back to 3.3.5 is working. 

`Progress: (5 photos, 28 videos, 0 audios, 0 skipped, 0 failed || 33/33||377.22 MB/377.22 MB) ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 100% 0:00:08`

**Comment by datawhores** [comment]
I think 3.3.13 might fix this 
there was a error in closing files
