### ISSUE TITLE
Getting content potentially duplicated raises `traceback` - v.3.4.3

### ISSUE THREAD

**Issue by PsychoSid** [datawhores/OF-Scraper#261]
**Describe the bug**
Get traceback when trying to pull content that is duplicated.

```
TRACEBACK  [logger.inner:192]  failed with exception: expected string or bytes-like object, got 'NoneType'                                                                                                                                                 logger.py:192
TRACEBACK  [logger.inner:192]  Traceback (most recent call last):                                                                                                                                                                                          logger.py:192
            File "/home/your_username/.local/pipx/venvs/ofscraper/lib/python3.11/site-packages/ofscraper/commands/scraper.py", line 185, in normal_post_process
              combined_urls=OF.process_areas( ele, model_id)
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
            File "/home/your_username/.local/pipx/venvs/ofscraper/lib/python3.11/site-packages/ofscraper/utils/of.py", line 282, in process_areas
              return filters.filterMedia(list(chain(*[profile_dicts  , timeline_posts_dicts ,pinned_post_dict,purchased_dict,
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
            File "/home/your_username/.local/pipx/venvs/ofscraper/lib/python3.11/site-packages/ofscraper/utils/filters.py", line 31, in filterMedia
              media=post_user_filter(media)
                    ^^^^^^^^^^^^^^^^^^^^^^^
            File "/home/your_username/.local/pipx/venvs/ofscraper/lib/python3.11/site-packages/ofscraper/utils/filters.py", line 117, in post_user_filter
              return list(filter(lambda x:re.search(userfilter,x.text)!=None,media))
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
            File "/home/your_username/.local/pipx/venvs/ofscraper/lib/python3.11/site-packages/ofscraper/utils/filters.py", line 117, in <lambda>
              return list(filter(lambda x:re.search(userfilter,x.text)!=None,media))
                                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
            File "/usr/lib/python3.11/re/__init__.py", line 176, in search
              return _compile(pattern, flags).search(string)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
          TypeError: expected string or bytes-like object, got 'NoneType'

 [scraper.scrape_context_manager:380]
```

**Comment by PsychoSid** [comment]
This was called via 

```
ofscraper --account-type paid -u <model> --posts all --action like --discord STATS --after 20231126 --dupe --output DEBUG
```

Post was from today with a bundle of videos, and photos.

**Comment by datawhores** [comment]
I removed something but I realize now this is why it was there
