### ISSUE TITLE
Error "No module named setproctitle" on script start

### ISSUE THREAD

**Issue by dia-val** [datawhores/OF-Scraper#281]
**Describe the bug**
ofscraper in docker unable to start due to error
Error "No module named setproctitle"

**To Reproduce**
run script "ofscraper" with arguments

Example

ofscraper --posts ALL --mediatype Videos --after 2000 --sub-status active --sort Subscribed --desc --log debug --username  MODELNAME

**Expected behavior**
normal operation

**Screenshots/Logs**
Traceback (most recent call last):
  File "/home/ofscraper/app/.venv/bin/ofscraper", line 3, in <module>
    from ofscraper.__main__ import main
  File "/home/ofscraper/app/ofscraper/__main__.py", line 4, in <module>
    import ofscraper.start as start
  File "/home/ofscraper/app/ofscraper/start.py", line 10, in <module>
    import ofscraper.commands.picker as picker
  File "/home/ofscraper/app/ofscraper/commands/picker.py", line 1, in <module>
    import ofscraper.commands.check as check
  File "/home/ofscraper/app/ofscraper/commands/check.py", line 12, in <module>
    import ofscraper.api.archive as archive
  File "/home/ofscraper/app/ofscraper/api/archive.py", line 24, in <module>
    import ofscraper.classes.sessionbuilder as sessionbuilder
  File "/home/ofscraper/app/ofscraper/classes/sessionbuilder.py", line 9, in <module>
    import ofscraper.utils.config as config_
  File "/home/ofscraper/app/ofscraper/utils/config.py", line 19, in <module>
    import ofscraper.prompts.prompts as prompts
  File "/home/ofscraper/app/ofscraper/prompts/prompts.py", line 25, in <module>
    import ofscraper.filters.models.selector as userselector
  File "/home/ofscraper/app/ofscraper/filters/models/selector.py", line 5, in <module>
    import ofscraper.filters.models.date as date_
  File "/home/ofscraper/app/ofscraper/filters/models/date.py", line 9, in <module>
    import ofscraper.utils.args as args_
  File "/home/ofscraper/app/ofscraper/utils/args.py", line 10, in <module>
    import ofscraper.utils.system as system
  File "/home/ofscraper/app/ofscraper/utils/system.py", line 11, in <module>
    from setproctitle import setproctitle
ModuleNotFoundError: No module named 'setproctitle'

**Desktop (please complete the following information):**

- OS: unraid
- Version: latest commit as of 23.12.23
- Docker

**Additional context**
Worked flawless before latest commit

**Comment by datawhores** [comment]
You probably just need to install the requirement 
How to install depends on how you installed the script

**Comment by Jarsky** [comment]
Getting the same error. You need to install the module. 


I use Docker; and setproctitle isnt part of the poetry.lock file. 

As a work around I did this:

Changed this:
`RUN curl -sSL https://install.python-poetry.org | python3.11 -`

To this:
```
RUN curl -sSL https://install.python-poetry.org | python3.11 -
RUN pip install setproctitle
RUN ln -s /home/ofscraper/.local/lib/python3.10/site-packages/setproctitle /home/ofscraper/.venv/lib/python3.11/site-packages/setproctitle
RUN ln -s /home/ofscraper/.local/lib/python3.10/site-packages/setproctitle-1.3.3.dist-info /home/ofscraper/.venv/lib/python3.11/site-packages/setproctitle-1.3.3.dist-info
```

**Comment by toddhow** [comment]
> You probably just need to install the requirement How to install depends on how you installed the script

You need to add `setproctitle` to `pyproject.toml` it's currently missing on the main branch.

**Comment by datawhores** [comment]
done
