### ISSUE TITLE
Auth Error V3.5.4 code":401,"message":"Please refresh the page

### ISSUE THREAD

**Issue by anthonyphua** [datawhores/OF-Scraper#283]
I am encountering an error since 26 Dec 2023 starting around 00:00 GMT hours.

Anyone encountering the same issue? 

The debug log is as follows :

 2023-12-27 21:05:18:\[start.startvalues:105]  Namespace(version='3.5.4', config=None, profile=None, log='DEBUG', discord='OFF', output='NORMAL', username=set(), excluded_username=set(), daemon=None, original=False, letter_count=False, action=None, dupe=False, posts=[], excluded_posts=[], filter='.*', neg_filter=None, scrape_paid=False, download_type=None, label=None, before=None, after=None, mediatype=[], size_max=None, size_min=None, mass_msg=None, timed_only=None, current_price=False, renewal_price=False, promo=False, all_promo=False, regular_price=False, promo_price=False, renewal=False, sub_status=False, user_list={'ofscraper.main'}, black_list=set(), sort='name', desc=False, users_first=False, no_cache=False, key_mode=None, dynamic_rules=None, part_cleanup=False, downloadbars=False, downloadsems=None, downloadthreads=None, metadata=False, command=None, excluded_post=[], dateformat='2023-12-27')
 2023-12-27 21:05:18:\[start.startvalues:106]  Windows-10-10.0.22631-SP0
 2023-12-27 21:05:18:\[start.startvalues:107]  {'main_profile': 'main_profile', 'save_location': 'I:\\Social Media\\Onlyfans', 'file_size_limit': 0, 'file_size_min': 0, 'dir_format': '{model_username}/{responsetype}/{mediatype}/', 'file_format': '{filename}.{ext}', 'textlength': 0, 'space-replacer': ' ', 'date': 'MM-DD-YYYY', 'metadata': '{configpath}/{profile}/.data/{model_username}_{model_id}', 'filter': ['Images', 'Audios', 'Videos'], 'threads': 2, 'code-execution': False, 'custom': 'null', 'mp4decrypt': 'C:\\Users\\antho\\.config\\ofscraper\\bin\\mp4decrypt.exe', 'ffmpeg': 'C:\\Users\\antho\\.config\\ofscraper\\bin\\ffmpeg.exe', 'discord': '', 'private-key': '', 'client-id': '', 'key-mode-default': 'keydb', 'keydb_api': '01cc04a1950c5d791a25311f58614732e7d65e17aaad30eb24a57dbe343402d1', 'dynamic-mode-default': 'digitalcriminals', 'partfileclean': False, 'backend': 'aio', 'download-sems': 6, 'maxfile-sem': 0, 'downloadbars': False, 'cache-mode': 'sqlite', 'appendlog': True, 'avatar': True, 'responsetype': {'timeline': 'Posts', 'message': 'Messages', 'archived': 'Archived', 'paid': 'Messages', 'stories': 'Stories', 'highlights': 'Stories', 'profile': 'Profile', 'pinned': 'Posts'}}
 2023-12-27 21:05:18:\[start.startvalues:108]  config path: C:\Users\antho\.config\ofscraper\config.json
 2023-12-27 21:05:18:\[start.startvalues:109]  profile path: C:\Users\antho\.config\ofscraper\main_profile
 2023-12-27 21:05:18:\[start.startvalues:110]  log folder: C:\Users\antho\.config\ofscraper\logging
 2023-12-27 21:05:18:\[start.startvalues:111]  ssl DefaultVerifyPaths(cafile=None, capath=None, openssl_cafile_env='SSL_CERT_FILE', openssl_cafile='C:\\Program Files\\Common Files\\SSL/cert.pem', openssl_capath_env='SSL_CERT_DIR', openssl_capath='C:\\Program Files\\Common Files\\SSL/certs')
 2023-12-27 21:05:18:\[start.startvalues:112]  python version 3.11.0
 2023-12-27 21:05:18:\[start.startvalues:113]  certifi C:\Users\antho\AppData\Local\Programs\Python\Python311\Lib\site-packages\certifi\cacert.pem
 2023-12-27 21:05:18:\[start.startvalues:114]  number of threads available on system 4
 2023-12-27 21:05:28:\[me._scraper_user_helper:54]  user request response status code:400
 2023-12-27 21:05:28:\[me._scraper_user_helper:55]  user request response: {"error":{"code":401,"message":"Please refresh the page"}}
 2023-12-27 21:05:28:\[me._scraper_user_helper:56]  user request headers: Headers({'date': 'Wed, 27 Dec 2023 13:05:29 GMT', 'content-type': 'application/json; charset=utf-8', 'content-length': '58', 'server': 'nginx', 'expires': 'Thu, 19 Nov 1981 08:52:00 GMT', 'cache-control': 'no-store, no-cache, must-revalidate', 'pragma': 'no-cache', 'set-cookie': 'sess=5iifmiit7palo5vrpg13bn6u79; expires=Sat, 06-Jan-2024 13:05:29 GMT; Max-Age=864000; path=/; domain=.onlyfans.com; secure; HttpOnly', 'access-control-allow-credentials': 'true', 'access-control-allow-methods': 'GET, PUT, POST, DELETE, OPTIONS, PATCH', 'access-control-allow-headers': 'Origin, Content-Type, Authorization, X-Requested-With, User-Agent, Access-Token, User-Id, Time, Sign, X-BC, App-Token, Csrf', 'access-control-expose-headers': 'Content-Length, Content-Range, Date, Access-Token, User-Id, X-OF-REV', 'allow': 'PUT, GET, DELETE, POST', 'x-of-rev': '202312261916-30670fa40e', 'user-id': '21433753', 'strict-transport-security': 'max-age=31536000; includeSubdomains; preload', 'x-frame-options': 'DENY'})
 2023-12-27 21:05:28:\[logger.inner:218]  Client error '400 Bad Request' for url 'https://onlyfans.com/api2/v2/users/me'
For more information check: https://httpstatuses.com/400
 2023-12-27 21:05:28:\[logger.inner:218]  Traceback (most recent call last):
  File "C:\Users\antho\AppData\Local\Programs\Python\Python311\Lib\site-packages\ofscraper\api\init.py", line 36, in getstatus
    me.scrape_user()
  File "C:\Users\antho\AppData\Local\Programs\Python\Python311\Lib\site-packages\ofscraper\api\me.py", line 28, in scrape_user
    return _scraper_user_helper(c)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\antho\AppData\Local\Programs\Python\Python311\Lib\site-packages\tenacity\__init__.py", line 289, in wrapped_f
    return self(f, *args, **kw)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\antho\AppData\Local\Programs\Python\Python311\Lib\site-packages\tenacity\__init__.py", line 379, in __call__
    do = self.iter(retry_state=retry_state)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\antho\AppData\Local\Programs\Python\Python311\Lib\site-packages\tenacity\__init__.py", line 325, in iter
    raise retry_exc.reraise()
          ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\antho\AppData\Local\Programs\Python\Python311\Lib\site-packages\tenacity\__init__.py", line 158, in reraise
    raise self.last_attempt.result()
          ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\antho\AppData\Local\Programs\Python\Python311\Lib\concurrent\futures\_base.py", line 449, in result
    return self.__get_result()
           ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\antho\AppData\Local\Programs\Python\Python311\Lib\concurrent\futures\_base.py", line 401, in __get_result
    raise self._exception
  File "C:\Users\antho\AppData\Local\Programs\Python\Python311\Lib\site-packages\tenacity\__init__.py", line 382, in __call__
    result = fn(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\antho\AppData\Local\Programs\Python\Python311\Lib\site-packages\ofscraper\api\me.py", line 57, in _scraper_user_helper
    r.raise_for_status()
  File "C:\Users\antho\AppData\Local\Programs\Python\Python311\Lib\site-packages\httpx\_models.py", line 749, in raise_for_status
    raise HTTPStatusError(message, request=request, response=self)
httpx.HTTPStatusError: Client error '400 Bad Request' for url 'https://onlyfans.com/api2/v2/users/me'
For more information check: https://httpstatuses.com/400

 2023-12-27 21:05:28:\[scraper.check_auth:390]  Auth Failed

**Comment by cjb900** [comment]
Clear your browsers cookies and cache. then enter the auth information into the auth.json file directly **NOT IN THE SCRAPER** and **DO NOT** use the browser extension. Also make sure your auth file is formatted correctly as the example below.

```
{
    "auth": {
        "app-token": "33d57ade8c02dbc5a333db99ff9ae26a",
        "sess": "",
        "auth_id": "",
        "auth_uid_": "",
        "user_agent": "",
        "x-bc": ""
    }
}
```

**Comment by anthonyphua** [comment]
Tried the above instruction with Firefox and Chrome. Still facing the same error
