### ISSUE TITLE
# A particular subscription cannot be scrapped

### ISSUE THREAD

**Issue by bogdanbdg** [datawhores/OF-Scraper#288]
**Describe the bug**
Among several subscriptions, there is one yielding no scrapping results, namely the `@<as in the logs>`. It goes through all the regular scanning steps, displays correct posts and media statistics, and after all that just simply falls through with no downloads whatsoever

**To Reproduce**
```
$ ofscraper --posts all --username <as in the logs>
```

**Expected behavior**
Downloading begins after the scanning process is complete

**Screenshots/Logs**
The only clue is in the debug output:
```
DEBUG     [labels.get_labelled_posts:211]  Labels count without Dupes 16 found                                        labels.py:211
TRACEBACK  [logger.inner:223]  failed with exception: UNIQUE constraint failed: labels.id, labels.post_id             logger.py:223
TRACEBACK  [logger.inner:223]  Traceback (most recent call last):                                                     logger.py:223
            File "/usr/local/lib/python3.11/site-packages/ofscraper/commands/scraper.py", line 208, in
          normal_post_process
              combined_urls = OF.process_areas(ele, model_id)
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
            File "/usr/local/lib/python3.11/site-packages/ofscraper/utils/of.py", line 534, in process_areas
              labels_dicts = process_labels(model_id, username)
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
            File "/usr/local/lib/python3.11/site-packages/ofscraper/utils/of.py", line 45, in inner
              return func(*args, **kwargs)
                     ^^^^^^^^^^^^^^^^^^^^^
            File "/usr/local/lib/python3.11/site-packages/ofscraper/utils/of.py", line 439, in process_labels
              operations.write_labels_table(
            File "/usr/local/lib/python3.11/site-packages/ofscraper/db/operations.py", line 122, in inner
              raise E
            File "/usr/local/lib/python3.11/site-packages/ofscraper/db/operations.py", line 105, in inner
              return func(*args, **kwargs, conn=conn)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
            File "/usr/local/lib/python3.11/site-packages/ofscraper/db/operations.py", line 533, in
          write_labels_table
              curr.executemany(queries.labelInsert, insertData)
          sqlite3.IntegrityError: UNIQUE constraint failed: labels.id, labels.post_id

 [scraper.scrape_context_manager:443]                                                                                scraper.py:443
===========================
 Script Finished
Run Time:  0:02:23
```
[ofscraper_main_profile_2024-01-02.log](https://github.com/datawhores/OF-Scraper/files/13810661/ofscraper_main_profile_2024-01-02.log)

**Desktop (please complete the following information):**

- OS: macos 13.5.2
- Browser N/A
- Version 3.6.3
- python 
- python version 3.11

**Additional context**
handling `dupes` doesn't change anything as nothing was ever downloaded

**Comment by datawhores** [comment]
This is issue is similar please use that one

https://github.com/datawhores/OF-Scraper/issues/287

**Comment by bogdanbdg** [comment]
Yes, it seems similar although at the time I checked there were not much information except "I can't" so I thought I'd start a new one with all (?) proper information. Anyway - I'll drop my log file to the other issue then

**Comment by datawhores** [comment]
I changed the name of the other issue to make the cause clearer

**Comment by bogdanbdg** [comment]
Roger. Kudos for the quick fix!
