### ISSUE TITLE
# Trying to login attempt:1/10  [scraper.check_auth:400]  Auth Failed

### ISSUE THREAD

**Issue by Blazekie** [datawhores/OF-Scraper#291]
The problem is on windows

**Comment by Puk0** [comment]
Sal de tu cuenta OF, vuelve a entrar para que genere otra cookie y le cambias los datos en el perfil/auth.json

**Comment by datawhores** [comment]
This may require a update

Hard to say without version info

**Comment by edcrfv0** [comment]
Same problem here...

```
$ ./ofscraper_linux_2aa90fd 
 [startvals.printStartValues:26]  config path: /home/your_username/.config/ofscraper/config.json                                                                               startvals.py:26
 [startvals.printStartValues:27]  profile path: /home/your_username/.config/ofscraper/main_profile                                                                             startvals.py:27
 [startvals.printStartValues:28]  log folder: /home/your_username/.config/ofscraper/logging                                                                                    startvals.py:28
 Welcome to OF-Scraper Version 0.0.0
 [paths.cleanup:62]  Cleaning up temp files                                                                                                                                        paths.py:62
                                                                                                                                                                                              
                                                                                                                                                                                              
Key Mode: manual


WARNING:Make sure you have all the correct settings for choosen cdm
https://of-scraper.gitbook.io/of-scraper/cdm-options


? What would you like to do? Download content from a user
Trying to login attempt:1/10
 [scraper.check_auth:408]  Auth Failed                                                                                                                                          scraper.py:408
 [paths.cleanup:62]  Cleaning up temp files                                                                                                                                        paths.py:62
                                                                                                                                                                                              
                                                                                                                                                                                              
Traceback (most recent call last):
  File "tenacity/__init__.py", line 382, in __call__
  File "utils/auth.py", line 307, in get_request_auth_deviint
  File "classes/sessionbuilder.py", line 96, in requests
  File "classes/sessionbuilder.py", line 82, in _create_cookies
  File "utils/auth.py", line 204, in add_cookies
KeyError: 'sess'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "__main__.py", line 15, in <module>
  File "__main__.py", line 10, in main
  File "start.py", line 85, in main
  File "start.py", line 82, in main
  File "start.py", line 42, in main
  File "commands/picker.py", line 20, in pick
  File "commands/scraper.py", line 493, in main
  File "commands/scraper.py", line 475, in main
  File "commands/scraper.py", line 514, in scrapper
  File "utils/exit.py", line 92, in inner
  File "utils/exit.py", line 85, in inner
  File "commands/scraper.py", line 59, in process_prompts
  File "commands/scraper.py", line 409, in check_auth
  File "utils/auth.py", line 64, in read_auth
  File "utils/auth.py", line 271, in make_request_auth
  File "utils/auth.py", line 293, in get_request_auth
  File "tenacity/__init__.py", line 289, in wrapped_f
  File "tenacity/__init__.py", line 379, in __call__
  File "tenacity/__init__.py", line 326, in iter
tenacity.RetryError: RetryError[<Future at 0x7f781134b1d0 state=finished raised KeyError>]
[3007788] Failed to execute script '__main__' due to unhandled exception!

```
