### ISSUE TITLE
TypeError: '>' not supported between instances of 'Arrow' and 'NoneType'

### ISSUE THREAD

**Issue by basketballhead6** [datawhores/OF-Scraper#292]
**Describe the bug**
Script fails occasionally with the following error in pipx version 3.6.3:
```
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "c:\users\x\.local\bin\ofscraper.exe\__main__.py", line 7, in <module>
  File "C:\Users\x\.local\pipx\venvs\ofscraper\Lib\site-packages\ofscraper\__main__.py", line 10, in main
    start.main()
  File "C:\Users\x\.local\pipx\venvs\ofscraper\Lib\site-packages\ofscraper\start.py", line 86, in main
    raise E
  File "C:\Users\x\.local\pipx\venvs\ofscraper\Lib\site-packages\ofscraper\start.py", line 83, in main
    raise E
  File "C:\Users\x\.local\pipx\venvs\ofscraper\Lib\site-packages\ofscraper\start.py", line 42, in main
    picker.pick()
  File "C:\Users\x\.local\pipx\venvs\ofscraper\Lib\site-packages\ofscraper\commands\picker.py", line 20, in pick
    scraper.main()
  File "C:\Users\x\.local\pipx\venvs\ofscraper\Lib\site-packages\ofscraper\commands\scraper.py", line 485, in main
    raise E
  File "C:\Users\x\.local\pipx\venvs\ofscraper\Lib\site-packages\ofscraper\commands\scraper.py", line 467, in main
    scrapper()
  File "C:\Users\x\.local\pipx\venvs\ofscraper\Lib\site-packages\ofscraper\commands\scraper.py", line 506, in scrapper
    process_prompts()
  File "C:\Users\x\.local\pipx\venvs\ofscraper\Lib\site-packages\ofscraper\utils\exit.py", line 92, in inner
    raise E
  File "C:\Users\x\.local\pipx\venvs\ofscraper\Lib\site-packages\ofscraper\utils\exit.py", line 85, in inner
    func(*args, **kwargs)
  File "C:\Users\x\.local\pipx\venvs\ofscraper\Lib\site-packages\ofscraper\commands\scraper.py", line 61, in process_prompts
    run(process_post)
  File "C:\Users\x\.local\pipx\venvs\ofscraper\Lib\site-packages\ofscraper\commands\scraper.py", line 328, in run
    run_helper(*functs)
  File "C:\Users\x\.local\pipx\venvs\ofscraper\Lib\site-packages\ofscraper\commands\scraper.py", line 389, in run_helper
    raise E
  File "C:\Users\x\.local\pipx\venvs\ofscraper\Lib\site-packages\ofscraper\commands\scraper.py", line 375, in run_helper
    job_func()
  File "C:\Users\x\.local\pipx\venvs\ofscraper\Lib\site-packages\ofscraper\utils\exit.py", line 92, in inner
    raise E
  File "C:\Users\x\.local\pipx\venvs\ofscraper\Lib\site-packages\ofscraper\utils\exit.py", line 85, in inner
    func(*args, **kwargs)
  File "C:\Users\x\.local\pipx\venvs\ofscraper\Lib\site-packages\ofscraper\commands\scraper.py", line 122, in process_post
    normal_post_process()
  File "C:\Users\x\.local\pipx\venvs\ofscraper\Lib\site-packages\ofscraper\utils\exit.py", line 92, in inner
    raise E
  File "C:\Users\x\.local\pipx\venvs\ofscraper\Lib\site-packages\ofscraper\utils\exit.py", line 85, in inner
    func(*args, **kwargs)
  File "C:\Users\x\.local\pipx\venvs\ofscraper\Lib\site-packages\ofscraper\commands\scraper.py", line 201, in normal_post_process
    f"Getting {','.join(args_.getargs().posts)} for [bold]{ele.name}[/bold]\n[bold]Subscription Active:[/bold] {ele.active}"
                                                                                                                ^^^^^^^^^^
  File "C:\Users\x\.local\pipx\venvs\ofscraper\Lib\site-packages\ofscraper\classes\models.py", line 133, in active
    elif arrow.get(self.expired) > args_.getargs().date_now:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: '>' not supported between instances of 'Arrow' and 'NoneType'
```

**To Reproduce**
Run the script and it will occasionally fail with the above TypeError

**Expected behavior**
Script completes sucuessfully wihtout any errors.

**Screenshots/Logs**
As above in the describe the bug section.

**Desktop (please complete the following information):**

- OS: Windows 11
- Browser: Chrome
- Version: 3.6.3
- Python
- Pipx

**Additional context**
N/A

**Comment by datawhores** [comment]
I push a commit to fix this

**Comment by basketballhead6** [comment]
I just got this exact same error again when using version 3.6.6 but a different file is causing the error this time:

```
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "c:\users\x\.local\bin\ofscraper.exe\__main__.py", line 7, in <module>
  File "C:\Users\x\.local\pipx\venvs\ofscraper\Lib\site-packages\ofscraper\__main__.py", line 10, in main
    start.main()
  File "C:\Users\x\.local\pipx\venvs\ofscraper\Lib\site-packages\ofscraper\start.py", line 85, in main
    raise E
  File "C:\Users\x\.local\pipx\venvs\ofscraper\Lib\site-packages\ofscraper\start.py", line 82, in main
    raise E
  File "C:\Users\x\.local\pipx\venvs\ofscraper\Lib\site-packages\ofscraper\start.py", line 42, in main
    picker.pick()
  File "C:\Users\x\.local\pipx\venvs\ofscraper\Lib\site-packages\ofscraper\commands\picker.py", line 20, in pick
    scraper.main()
  File "C:\Users\x\.local\pipx\venvs\ofscraper\Lib\site-packages\ofscraper\commands\scraper.py", line 485, in main
    raise E
  File "C:\Users\x\.local\pipx\venvs\ofscraper\Lib\site-packages\ofscraper\commands\scraper.py", line 467, in main
    scrapper()
  File "C:\Users\x\.local\pipx\venvs\ofscraper\Lib\site-packages\ofscraper\commands\scraper.py", line 506, in scrapper
    process_prompts()
  File "C:\Users\x\.local\pipx\venvs\ofscraper\Lib\site-packages\ofscraper\utils\exit.py", line 92, in inner
    raise E
  File "C:\Users\x\.local\pipx\venvs\ofscraper\Lib\site-packages\ofscraper\utils\exit.py", line 85, in inner
    func(*args, **kwargs)
  File "C:\Users\x\.local\pipx\venvs\ofscraper\Lib\site-packages\ofscraper\commands\scraper.py", line 61, in process_prompts
    run(process_post)
  File "C:\Users\x\.local\pipx\venvs\ofscraper\Lib\site-packages\ofscraper\commands\scraper.py", line 328, in run
    run_helper(*functs)
  File "C:\Users\x\.local\pipx\venvs\ofscraper\Lib\site-packages\ofscraper\commands\scraper.py", line 389, in run_helper
    raise E
  File "C:\Users\x\.local\pipx\venvs\ofscraper\Lib\site-packages\ofscraper\commands\scraper.py", line 372, in run_helper
    userselector.getselected_usernames(rescan=True, reset=True)
  File "C:\Users\x\.local\pipx\venvs\ofscraper\Lib\site-packages\ofscraper\filters\models\selector.py", line 36, in getselected_usernames
    parsed_subscriptions_helper()
  File "C:\Users\x\.local\pipx\venvs\ofscraper\Lib\site-packages\ofscraper\filters\models\selector.py", line 61, in parsed_subscriptions_helper
    selectedusers = retriver.get_model(filterNSort((ALL_SUBS)))
                                       ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\x\.local\pipx\venvs\ofscraper\Lib\site-packages\ofscraper\filters\models\selector.py", line 90, in filterNSort
    filterusername = subtype.subType(usernames)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\x\.local\pipx\venvs\ofscraper\Lib\site-packages\ofscraper\filters\models\subtype.py", line 17, in subType
    filterusername = list(filter(lambda x: x.active, filterusername))
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\x\.local\pipx\venvs\ofscraper\Lib\site-packages\ofscraper\filters\models\subtype.py", line 17, in <lambda>
    filterusername = list(filter(lambda x: x.active, filterusername))
                                           ^^^^^^^^
  File "C:\Users\x\.local\pipx\venvs\ofscraper\Lib\site-packages\ofscraper\classes\models.py", line 133, in active
    elif arrow.get(self.expired) > args_.getargs().date_now:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: '>' not supported between instances of 'Arrow' and 'NoneType'
```
