### ISSUE TITLE
TypeError: '>' not supported between instances of 'Arrow' and 'NoneType'

### ISSUE THREAD

**Issue by basketballhead6** [datawhores/OF-Scraper#296]
**Describe the bug**
Script fails occasionally with the following error in pipx version 3.6.8:

**Screenshots/Logs**
```
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "c:\users\x\.local\bin\ofscraper.exe\__main__.py", line 7, in <module>
  File "C:\Users\x\.local\pipx\venvs\ofscraper\Lib\site-packages\ofscraper\__main__.py", line 10, in main
    start.main()
  File "C:\Users\x\.local\pipx\venvs\ofscraper\Lib\site-packages\ofscraper\start.py", line 85, in main
    raise E
  File "C:\Users\x\.local\pipx\venvs\ofscraper\Lib\site-packages\ofscraper\start.py", line 82, in main
    raise E
  File "C:\Users\x\.local\pipx\venvs\ofscraper\Lib\site-packages\ofscraper\start.py", line 42, in main
    picker.pick()
  File "C:\Users\x\.local\pipx\venvs\ofscraper\Lib\site-packages\ofscraper\commands\picker.py", line 20, in pick
    scraper.main()
  File "C:\Users\x\.local\pipx\venvs\ofscraper\Lib\site-packages\ofscraper\commands\scraper.py", line 485, in main
    raise E
  File "C:\Users\x\.local\pipx\venvs\ofscraper\Lib\site-packages\ofscraper\commands\scraper.py", line 467, in main
    scrapper()
  File "C:\Users\x\.local\pipx\venvs\ofscraper\Lib\site-packages\ofscraper\commands\scraper.py", line 506, in scrapper
    process_prompts()
  File "C:\Users\x\.local\pipx\venvs\ofscraper\Lib\site-packages\ofscraper\utils\exit.py", line 92, in inner
    raise E
  File "C:\Users\x\.local\pipx\venvs\ofscraper\Lib\site-packages\ofscraper\utils\exit.py", line 85, in inner
    func(*args, **kwargs)
  File "C:\Users\x\.local\pipx\venvs\ofscraper\Lib\site-packages\ofscraper\commands\scraper.py", line 61, in process_prompts
    run(process_post)
  File "C:\Users\x\.local\pipx\venvs\ofscraper\Lib\site-packages\ofscraper\commands\scraper.py", line 328, in run
    run_helper(*functs)
  File "C:\Users\x\.local\pipx\venvs\ofscraper\Lib\site-packages\ofscraper\commands\scraper.py", line 389, in run_helper
    raise E
  File "C:\Users\x\.local\pipx\venvs\ofscraper\Lib\site-packages\ofscraper\commands\scraper.py", line 372, in run_helper
    userselector.getselected_usernames(rescan=True, reset=True)
  File "C:\Users\x\.local\pipx\venvs\ofscraper\Lib\site-packages\ofscraper\filters\models\selector.py", line 36, in getselected_usernames
    parsed_subscriptions_helper()
  File "C:\Users\x\.local\pipx\venvs\ofscraper\Lib\site-packages\ofscraper\filters\models\selector.py", line 61, in parsed_subscriptions_helper
    selectedusers = retriver.get_model(filterNSort((ALL_SUBS)))
                                       ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\x\.local\pipx\venvs\ofscraper\Lib\site-packages\ofscraper\filters\models\selector.py", line 90, in filterNSort
    filterusername = subtype.subType(usernames)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\x\.local\pipx\venvs\ofscraper\Lib\site-packages\ofscraper\filters\models\subtype.py", line 17, in subType
    filterusername = list(filter(lambda x: x.active, filterusername))
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\x\.local\pipx\venvs\ofscraper\Lib\site-packages\ofscraper\filters\models\subtype.py", line 17, in <lambda>
    filterusername = list(filter(lambda x: x.active, filterusername))
                                           ^^^^^^^^
  File "C:\Users\x\.local\pipx\venvs\ofscraper\Lib\site-packages\ofscraper\classes\models.py", line 133, in active
    elif arrow.get(self.expired) > args_.getargs().date_now:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: '>' not supported between instances of 'Arrow' and 'NoneType'
```

**To Reproduce**
Run the script and it will occasionally fail with the above TypeError

**Expected behavior**
Script completes sucuessfully wihtout any errors.

**Screenshots/Logs**
As above in the describe the bug section.

**Desktop (please complete the following information):**

- OS: Windows 11
- Version: 3.6.8
- Python
- Pipx

**Additional context**
N/A

**Comment by datawhores** [comment]
Can you do 
pipx uninstall ofscraper
pip uninstall ofscraper

restart the cmd line make sure that 
when running ofscraper the command **does not work**

then install in your preferred way
You still on some old version because the code in the error does not match with the repo

**Comment by basketballhead6** [comment]
Done, will see if that bring up the issue while running the script.

**Comment by basketballhead6** [comment]
@datawhores still getting the same error as above in the bug report after following your instructions

**Comment by datawhores** [comment]
alright I'll take another look

**Comment by datawhores** [comment]
Please show a full log if possible

**Comment by basketballhead6** [comment]
I think it might be something to do when trying to filter selected profiles after a run. I start the scrpt fresh for the first time, filter out expired subs and script works fine without errors. Then at the decision point when I get asked to rerun the script again, the error occurs.

https://paste.passtheheadphones.me/?822f401d588f8c9d#AgGKHiw17tfX9SHAoneDxaQjWPE6Vu2gxdbhXZC3Mu7v

**Comment by datawhores** [comment]
Did you install the zip or exe

**Comment by ckramer** [comment]
> I think it might be something to do when trying to filter selected profiles after a run. I start the scrpt fresh for the first time, filter out expired subs and script works fine without errors. Then at the decision point when I get asked to rerun the script again, the error occurs.
> 

Can confirm; I left ofscraper idle overnight on "continue with script?" and when continued next day got this error.
Restarted script and everything is fine!

While ofscraper was idle on "continue?" I purchased some video, and this error was on the account I purchased video at. (I may have also selected "Full scan of purchases" on previous run, not sure)
So this is some internal inconsistency when your purchases change while script is running you may get this error.

I'm on latest version, docker.

**Comment by datawhores** [comment]
@ckramer 
which docker tag did you use specifically, and when did you git pull last

**Comment by basketballhead6** [comment]
@datawhores since updating to 3.7.1 with the menu's overhaul this seems to have been fixed. I'll leave it up to you if you want to mark this as resolved.
