### ISSUE TITLE
Liking of all user-content not possible

### ISSUE THREAD

**Issue by Master-Austria** [datawhores/OF-Scraper#301]
Ofscraper version 3.6.8  is used with python 3.11.6 - installed via pipx!
After selecting a model to like all her user content following error message appears!
But I'm subscriped to here page!

-------------------------------------------------------------------------------------
? Which models do you want to scrape
: mrsskinnygoddess
 [scraper.scrape_context_manager:436]                                                                     scraper.py:436
==============================
 starting script
==============================

 [profiles.print_current_profile:146]  Using profile: main_profile                                       profiles.py:146
Status - UP
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "c:\users\anon-username\.local\bin\ofscraper.exe\__main__.py", line 7, in <module>
  File "C:\Users\anon-username\.local\pipx\venvs\ofscraper\Lib\site-packages\ofscraper\__main__.py", line 10, in main
    start.main()
  File "C:\Users\anon-username\.local\pipx\venvs\ofscraper\Lib\site-packages\ofscraper\start.py", line 85, in main
    raise E
  File "C:\Users\anon-username\.local\pipx\venvs\ofscraper\Lib\site-packages\ofscraper\start.py", line 82, in main
    raise E
  File "C:\Users\anon-username\.local\pipx\venvs\ofscraper\Lib\site-packages\ofscraper\start.py", line 42, in main
    picker.pick()
  File "C:\Users\anon-username\.local\pipx\venvs\ofscraper\Lib\site-packages\ofscraper\commands\picker.py", line 20, in pick
    scraper.main()
  File "C:\Users\anon-username\.local\pipx\venvs\ofscraper\Lib\site-packages\ofscraper\commands\scraper.py", line 487, in main
    raise E
  File "C:\Users\anon-username\.local\pipx\venvs\ofscraper\Lib\site-packages\ofscraper\commands\scraper.py", line 469, in main
    scrapper()
  File "C:\Users\anon-username\.local\pipx\venvs\ofscraper\Lib\site-packages\ofscraper\commands\scraper.py", line 508, in scrapper
    process_prompts()
  File "C:\Users\anon-username\.local\pipx\venvs\ofscraper\Lib\site-packages\ofscraper\utils\exit.py", line 92, in inner
    raise E
  File "C:\Users\anon-username\.local\pipx\venvs\ofscraper\Lib\site-packages\ofscraper\utils\exit.py", line 85, in inner
    func(*args, **kwargs)
  File "C:\Users\anon-username\.local\pipx\venvs\ofscraper\Lib\site-packages\ofscraper\commands\scraper.py", line 67, in process_prompts
    run(process_like)
  File "C:\Users\anon-username\.local\pipx\venvs\ofscraper\Lib\site-packages\ofscraper\commands\scraper.py", line 330, in run
    run_helper(*functs)
  File "C:\Users\anon-username\.local\pipx\venvs\ofscraper\Lib\site-packages\ofscraper\commands\scraper.py", line 391, in run_helper
    raise E
  File "C:\Users\anon-username\.local\pipx\venvs\ofscraper\Lib\site-packages\ofscraper\commands\scraper.py", line 377, in run_helper
    job_func()
  File "C:\Users\anon-username\.local\pipx\venvs\ofscraper\Lib\site-packages\ofscraper\utils\exit.py", line 92, in inner
    raise E
  File "C:\Users\anon-username\.local\pipx\venvs\ofscraper\Lib\site-packages\ofscraper\utils\exit.py", line 85, in inner
    func(*args, **kwargs)
  File "C:\Users\anon-username\.local\pipx\venvs\ofscraper\Lib\site-packages\ofscraper\commands\scraper.py", line 259, in process_like
    active = list(filter(lambda x: x["active"], userdata))
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\anon-username\.local\pipx\venvs\ofscraper\Lib\site-packages\ofscraper\commands\scraper.py", line 259, in <lambda>
    active = list(filter(lambda x: x["active"], userdata))
                                   ~^^^^^^^^^^
TypeError: 'Model' object is not subscriptable
-------------------------------------------------------------------------------------

**Comment by RaySajuuk** [comment]
same issue for awhile now.

**Comment by datawhores** [comment]
Getting fix in next release
