### ISSUE TITLE
Unable to download contents with latest ofscraper

### ISSUE THREAD

**Issue by RaySajuuk** [datawhores/OF-Scraper#304]
**Describe the bug**
Getting errors on sqlite disk IO error when download starts.

Reinstalled all dependencies via brew and pipx.

**To Reproduce**
1. Run script
2. Download video

**Expected behavior**
Download should start without error.

**Screenshots/Logs**
sqlite3.OperationalError: disk I[FF8101]  error
Traceback (most recent call last):
  File "/pipx/venvs/ofscraper/lib/python3.11/site-packages/multiprocess/process.py", line 314, in _bootstrap
    self.run()
  File "/pipx/venvs/ofscraper/lib/python3.11/site-packages/multiprocess/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/pipx/venvs/ofscraper/lib/python3.11/site-packages/ofscraper/download/downloadbatch.py", line 309, in process_dict_starter
    subProcessVariableInit(
  File "/pipx/venvs/ofscraper/lib/python3.11/site-packages/ofscraper/download/common.py", line 144, in subProcessVariableInit
    reset_globals()
  File "/pipx/venvs/ofscraper/lib/python3.11/site-packages/ofscraper/download/common.py", line 105, in reset_globals
    cache = Cache(
            ^^^^^^
  File "/pipx/venvs/ofscraper/lib/python3.11/site-packages/diskcache/core.py", line 456, in __init__
    sql = self._sql_retry
          ^^^^^^^^^^^^^^^
  File "/pipx/venvs/ofscraper/lib/python3.11/site-packages/diskcache/core.py", line 652, in _sql_retry
    sql = self._sql
          ^^^^^^^^^
  File "/pipx/venvs/ofscraper/lib/python3.11/site-packages/diskcache/core.py", line 648, in _sql
    return self._con.execute
           ^^^^^^^^^
  File "/pipx/venvs/ofscraper/lib/python3.11/site-packages/diskcache/core.py", line 623, in _con
    con = self._local.con = sqlite3.connect(

- OS: [macOS]
- Browser [Safari]
- Version [17.3]
- pipx ofscraper 3.6.8, Python 3.11.7

**Additional context**
Thanks

**Comment by RaySajuuk** [comment]
I tried to change "cache-mode": "json", but still getting sqlite error.

**Comment by RaySajuuk** [comment]
I was able to make it work by remove and reinstall python, pipx.
Noticed brew now install pipx with python@3.12, added PIPX_DEFAULT_PYTHON to make pipx use python@3.11 as default interpreter.
