### ISSUE TITLE
sys:1: RuntimeWarning: coroutine 'run_in_terminal.<locals>.run' was never awaited - Can't download from a user

### ISSUE THREAD

**Issue by Vancore** [datawhores/OF-Scraper#312]
Heyhey, tried the ofscraper for the first time on Windows 10 and Chrome.

I wen't with the standard procedure of adding my auth entries. After executing the "Download content from a user" I am confrontent with the following error:

```
Your `auth.json` file has been edited.
? Do you want to continue with script Yes
? What would you like to do? Download content from a user
 [paths.cleanup:175]  Cleaning up temp files                                                                                                                 paths.py:175


 [logger.discord_cleanup:84]  Pushing Discord Queue                                                                                                          logger.py:84
sys:1: RuntimeWarning: coroutine 'run_in_terminal.<locals>.run' was never awaited
RuntimeWarning: Enable tracemalloc to get the object allocation traceback
```

I also tried to download a specific URL from the user like so:
```

PS C:\Users\myUserName> ofscraper manual --url https://onlyfans.com/903788366/onlyFansUser --output debug
DEBUG     [start.main:17]  Namespace(version='2.6.4.1', config=None, profile=None, log='OFF',               start.py:17
         discord='OFF', output='DEBUG', username=set(), excluded_username=set(), daemon=None,
         original=False, letter_count=False, action=None, dupe=False, posts=[], skip_timed=None,
         filter='.*', scrape_paid=False, download_type=None, account_type=None, renewal=None,
         sub_status=None, before=None, after=None, sort='name', desc=False, users_first=False,
         no_cache=False, command='manual', file=None, url=['https://onlyfans.com/903788366/onlyFansUser'])
 [start.main:21]  config path: C:\Users\myUserName\.config\ofscraper\config.json                                 start.py:21
 [start.main:22]  profile path: C:\Users\myUserName\.config\ofscraper\main_profile                               start.py:22
 [start.main:23]  log folder: C:\Users\myUserName\.config\ofscraper\logging                                      start.py:23
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "c:\users\myUserName\.local\bin\ofscraper.exe\__main__.py", line 7, in <module>
  File "C:\Users\myUserName\AppData\Local\pipx\pipx\venvs\ofscraper\Lib\site-packages\ofscraper\start.py", line 35, in main
    manual.manual_download()
  File "C:\Users\myUserName\AppData\Local\pipx\pipx\venvs\ofscraper\Lib\site-packages\ofscraper\commands\manual.py", line 22, in manual_download
    media_dict=get_media_from_urls(urls)
               ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\myUserName\AppData\Local\pipx\pipx\venvs\ofscraper\Lib\site-packages\ofscraper\commands\manual.py", line 52, in get_media_from_urls
    model_id=user_name_dict.get(model) or profile.get_id( model)
                                          ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\myUserName\AppData\Local\pipx\pipx\venvs\ofscraper\Lib\site-packages\tenacity\__init__.py", line 289, in wrapped_f
    return self(f, *args, **kw)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\myUserName\AppData\Local\pipx\pipx\venvs\ofscraper\Lib\site-packages\tenacity\__init__.py", line 379, in __call__
    do = self.iter(retry_state=retry_state)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\myUserName\AppData\Local\pipx\pipx\venvs\ofscraper\Lib\site-packages\tenacity\__init__.py", line 325, in iter
    raise retry_exc.reraise()
          ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\myUserName\AppData\Local\pipx\pipx\venvs\ofscraper\Lib\site-packages\tenacity\__init__.py", line 158, in reraise
    raise self.last_attempt.result()
          ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\myUserName\AppData\Local\Programs\Python\Python312\Lib\concurrent\futures\_base.py", line 449, in result
    return self.__get_result()
           ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\myUserName\AppData\Local\Programs\Python\Python312\Lib\concurrent\futures\_base.py", line 401, in __get_result
    raise self._exception
  File "C:\Users\myUserName\AppData\Local\pipx\pipx\venvs\ofscraper\Lib\site-packages\tenacity\__init__.py", line 382, in __call__
    result = fn(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\myUserName\AppData\Local\pipx\pipx\venvs\ofscraper\Lib\site-packages\ofscraper\api\profile.py", line 113, in get_id
    r.raise_for_status()
  File "C:\Users\myUserName\AppData\Local\pipx\pipx\venvs\ofscraper\Lib\site-packages\httpx\_models.py", line 749, in raise_for_status
    raise HTTPStatusError(message, request=request, response=self)
httpx.HTTPStatusError: Client error '400 Bad Request' for url 'https://onlyfans.com/api2/v2/users/onlyFansUser'
For more information check: https://httpstatuses.com/400
```

Maybe I am missing some setup pieces, not sure tho. Appreciate the help!

**Comment by datawhores** [comment]
You should make sure your on the latest version
or 3.5.4

**Comment by Vancore** [comment]
Thanks for the quick reply!

trying

`pipx upgrade ofscraper
⚠️  Overwriting file C:\Users\myUserName\.local\bin\ofscraper.exe with C:\Users\myUserName\AppData\Local\pipx\pipx\venvs\ofscraper\Scripts\ofscraper.exe
ofscraper is already at latest version 2.6.4.1 (location: C:\Users\myUserName\AppData\Local\pipx\pipx\venvs\ofscraper)`

Sorry for having me walking through, not sure how to fetch the latest version like this.

**Comment by datawhores** [comment]
Try this
pipx install ofscraper=='3.5.4' --force --pip-args="--no-cache"  --verbose

**Comment by Vancore** [comment]
Got this:

```
PS C:\Users\myUserName> pipx install ofscraper=='3.5.4' --force --pip-args="--no-cache" --verbose
pipx >(setup:860): pipx version is 1.4.3
pipx >(setup:861): Default python interpreter is 'C:\Users\myUserName\AppData\Local\Programs\Python\Python312\python.exe'
pipx >(package_name_from_spec:370): Determined package name: ofscraper
pipx >(package_name_from_spec:371): Package name determined in 0.0s
pipx >(run_subprocess:168): running <checking pip's availability>
pipx >(needs_upgrade:78): Time since last upgrade of shared libs, in seconds: 2521. Upgrade will be run by pipx if greater than 2592000.
pipx >(run_subprocess:168): running <checking pip's availability>
Installing to existing venv 'ofscraper'
creating virtual environment...
pipx >(run_subprocess:168): running C:\Users\myUserName\AppData\Local\Programs\Python\Python312\python.exe -m venv --without-pip C:\Users\myUserName\AppData\Local\pipx\pipx\venvs\ofscraper
pipx >(run_subprocess:168): running <checking pip's availability>
pipx >(run_subprocess:168): running C:\Users\myUserName\AppData\Local\pipx\pipx\venvs\ofscraper\Scripts\python.exe -c import sysconfig; print(sysconfig.get_path('purelib'))
pipx >(run_subprocess:168): running C:\Users\myUserName\AppData\Local\pipx\pipx\shared\Scripts\python.exe -c import sysconfig; print(sysconfig.get_path('purelib'))
pipx >(run_subprocess:168): running C:\Users\myUserName\AppData\Local\pipx\pipx\venvs\ofscraper\Scripts\python.exe --version
pipx >(_parsed_package_to_package_or_url:137): cleaned package spec: ofscraper==3.5.4
installing ofscraper from spec 'ofscraper==3.5.4'...
pipx >(run_subprocess:168): running C:\Users\myUserName\AppData\Local\pipx\pipx\venvs\ofscraper\Scripts\python.exe -m pip --no-input install --force-reinstall --no-cache ofscraper==3.5.4
pipx >(subprocess_post_check_handle_pip_error:327): 'C:\\Users\\myUserName\\AppData\\Local\\pipx\\pipx\\venvs\\ofscraper\\Scripts\\python.exe -m pip --no-input install --force-reinstall --no-cache ofscraper==3.5.4' failed
pipx >(subprocess_post_check_handle_pip_error:342): Fatal error from pip prevented installation. Full pip output in file:
    C:\Users\myUserName\AppData\Local\pipx\pipx\Logs\cmd_2024-01-25_00.50.56_pip_errors.log

Some possibly relevant errors from pip install:
    ERROR: Ignored the following yanked versions: 1.82, 1.83
    ERROR: Ignored the following versions that require a different python version: 1.4.1 Requires-Python >=3.9.0,<3.11.0; 1.4.2 Requires-Python >=3.9.0,<3.11.0; 2.7.1 Requires-Python >=3.7.0,<3.12; 2.7.10 Requires-Python >=3.7.0,<3.12; 2.7.11 Requires-Python >=3.7.0,<3.12; 2.7.12 Requires-Python >3.7.0,<3.12; 2.7.13 Requires-Python >=3.7.0,<3.12; 2.7.14 Requires-Python >=3.7.0,<3.12; 2.7.2 Requires-Python >=3.7.0,<3.12; 2.7.3 Requires-Python >=3.7.0,<3.12; 2.7.4 Requires-Python >=3.7.0,<3.12; 2.7.5 Requires-Python >=3.7.0,<3.12; 2.7.6 Requires-Python >=3.7.0,<3.12; 2.7.7 Requires-Python >=3.7.0,<3.12; 2.7.8 Requires-Python >=3.7.0,<3.12; 2.7.9 Requires-Python >=3.7.0,<3.12; 3.0 Requires-Python >3.7.0,<3.12; 3.0.1 Requires-Python >3.7.0,<3.12; 3.0.10 Requires-Python >3.7.0,<3.12; 3.0.11 Requires-Python >3.7.0,<3.12; 3.0.12 Requires-Python >3.7.0,<3.12; 3.0.2 Requires-Python >3.7.0,<3.12; 3.0.3 Requires-Python >3.7.0,<3.12; 3.0.4 Requires-Python >3.7.0,<3.12; 3.0.5 Requires-Python >3.7.0,<3.12; 3.0.6 Requires-Python >3.7.0,<3.12; 3.0.7 Requires-Python >3.7.0,<3.12; 3.0.8 Requires-Python >3.7.0,<3.12; 3.0.9 Requires-Python >3.7.0,<3.12; 3.1.1 Requires-Python >=3.8.0,<3.12; 3.1.2 Requires-Python >=3.10.0,<3.12; 3.2 Requires-Python >=3.10.0,<3.12; 3.2.1 Requires-Python >=3.10.0,<3.12; 3.2.2 Requires-Python >=3.10.0,<3.12; 3.2.3 Requires-Python >=3.10.0,<3.12; 3.2.4 Requires-Python >=3.10.0,<3.12; 3.2.5 Requires-Python >=3.10.11,<3.12; 3.3 Requires-Python >=3.10.11,<3.12; 3.3.1 Requires-Python >=3.10.11,<3.12; 3.3.10 Requires-Python >=3.10.11,<3.12; 3.3.12 Requires-Python >=3.10.11,<3.12; 3.3.2 Requires-Python >=3.10.11,<3.12; 3.3.3 Requires-Python >=3.10.11,<3.12; 3.3.3.1 Requires-Python >=3.10.11,<3.12; 3.3.3.2 Requires-Python >=3.10.11,<3.12; 3.3.4 Requires-Python >=3.10.11,<3.12; 3.3.5 Requires-Python >=3.10.11,<3.12; 3.3.6 Requires-Python >=3.10.11,<3.12; 3.3.7 Requires-Python >=3.10.11,<3.12; 3.3.8 Requires-Python >=3.10.11,<3.12; 3.4 Requires-Python >=3.10.11,<3.12; 3.4.1 Requires-Python >=3.10.11,<3.12; 3.4.2 Requires-Python >=3.10.11,<=3.12; 3.4.3 Requires-Python >=3.10.11,<=3.12; 3.4.4 Requires-Python >=3.10.11,<=3.12; 3.5 Requires-Python >=3.10.11,<=3.12; 3.5.1 Requires-Python >=3.10.11,<=3.12; 3.5.2 Requires-Python >=3.10.11,<=3.12; 3.5.3 Requires-Python >=3.10.11,<=3.12; 3.5.4 Requires-Python >=3.10.11,<=3.12; 3.6.0 Requires-Python >=3.10.11,<=3.12; 3.6.1 Requires-Python >=3.10.11,<=3.12; 3.6.2 Requires-Python >=3.10.11,<=3.12; 3.6.3 Requires-Python >=3.10.11,<=3.12; 3.6.4 Requires-Python >=3.10.11,<=3.12; 3.6.5 Requires-Python >=3.10.11,<=3.12; 3.6.6 Requires-Python >=3.10.11,<=3.12; 3.6.7 Requires-Python >=3.10.11,<=3.12; 3.6.8 Requires-Python >=3.10.11,<=3.12
    ERROR: Could not find a version that satisfies the requirement ofscraper==3.5.4 (from versions: 0.0.0, 1.4.3, 1.4.4, 1.4.5, 1.5, 1.51, 1.60, 1.61, 1.62, 1.63, 1.65, 1.70, 1.71, 1.72, 1.73, 1.74, 1.75, 1.80, 1.81, 1.86, 1.87, 1.95, 1.95.1, 1.95.2, 2.0, 2.0.1, 2.1, 2.4, 2.4.1, 2.4.3, 2.4.4, 2.4.5, 2.4.6, 2.5, 2.6, 2.6.1, 2.6.3, 2.6.4, 2.6.4.1)
    ERROR: No matching distribution found for ofscraper==3.5.4

pipx >(remove_venv:187): ⚠️  Not removing existing venv C:\Users\myUserName\AppData\Local\pipx\pipx\venvs\ofscraper because it was not created in
    this session
```

**Comment by datawhores** [comment]
Yeah I must be on exactly 3.12 on my system
But I don't think this will work unless you downgrade to 3.11 or got to exactly 3.12

I made a change in the package so hopefully it will work when the next version comes

**Comment by datawhores** [comment]
You have to uninstall pipx 
install python3.11
and install pipx with python3.11

**Comment by Vancore** [comment]
I went to exactly python3.12(.0).

Running ofscraper now gives me:

```
PS C:\WINDOWS\system32> ofscraper
 [startvals.printStartValues:26]  config path: C:\Users\your_username\.config\ofscraper\config.json                                                     startvals.py:26
 [startvals.printStartValues:27]  profile path: C:\Users\your_username\.config\ofscraper\main_profile                                                   startvals.py:27
 [startvals.printStartValues:28]  log folder: C:\Users\your_username\.config\ofscraper\logging                                                          startvals.py:28
 Welcome to OF-Scraper Version 3.6.8
Key Mode: cdrm2


CDM service cdrm2 has an issue RetryError[<Future at 0x27775ed06e0 state=finished raised KeyError>]
This may cause a lot of failed downloads
Please confirm by checking the url:http://172.106.17.134:8080/wv
 Consider switching
https://of-scraper.gitbook.io/of-scraper/cdm-options


? What would you like to do? Download content from a user
Trying to login attempt:1/10
 [scraper.check_auth:402]  Auth Failed                                                                                                                                                                                                                                 scraper.py:402
Traceback (most recent call last):
  File "C:\Users\myUserName\AppData\Local\pipx\pipx\venvs\ofscraper\Lib\site-packages\tenacity\__init__.py", line 382, in __call__
    result = fn(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\myUserName\AppData\Local\pipx\pipx\venvs\ofscraper\Lib\site-packages\ofscraper\utils\auth.py", line 307, in get_request_auth_deviint
    with c.requests(DEVIINT)() as r:
         ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\myUserName\AppData\Local\pipx\pipx\venvs\ofscraper\Lib\site-packages\ofscraper\classes\sessionbuilder.py", line 96, in requests
    cookies = cookies or self._create_cookies()
                         ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\myUserName\AppData\Local\pipx\pipx\venvs\ofscraper\Lib\site-packages\ofscraper\classes\sessionbuilder.py", line 82, in _create_cookies
    return auth.add_cookies()
           ^^^^^^^^^^^^^^^^^^
  File "C:\Users\myUserName\AppData\Local\pipx\pipx\venvs\ofscraper\Lib\site-packages\ofscraper\utils\auth.py", line 204, in add_cookies
    cookies.update({"sess": auth["auth"]["sess"]})
                            ~~~~~~~~~~~~^^^^^^^^
KeyError: 'sess'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "c:\users\myUserName\.local\bin\ofscraper.exe\__main__.py", line 7, in <module>
  File "C:\Users\myUserName\AppData\Local\pipx\pipx\venvs\ofscraper\Lib\site-packages\ofscraper\start.py", line 85, in main
    raise E
  File "C:\Users\myUserName\AppData\Local\pipx\pipx\venvs\ofscraper\Lib\site-packages\ofscraper\start.py", line 82, in main
    raise E
  File "C:\Users\myUserName\AppData\Local\pipx\pipx\venvs\ofscraper\Lib\site-packages\ofscraper\start.py", line 42, in main
    picker.pick()
  File "C:\Users\myUserName\AppData\Local\pipx\pipx\venvs\ofscraper\Lib\site-packages\ofscraper\commands\picker.py", line 20, in pick
    scraper.main()
  File "C:\Users\myUserName\AppData\Local\pipx\pipx\venvs\ofscraper\Lib\site-packages\ofscraper\commands\scraper.py", line 487, in main
    raise E
  File "C:\Users\myUserName\AppData\Local\pipx\pipx\venvs\ofscraper\Lib\site-packages\ofscraper\commands\scraper.py", line 469, in main
    scrapper()
  File "C:\Users\myUserName\AppData\Local\pipx\pipx\venvs\ofscraper\Lib\site-packages\ofscraper\commands\scraper.py", line 508, in scrapper
    process_prompts()
  File "C:\Users\myUserName\AppData\Local\pipx\pipx\venvs\ofscraper\Lib\site-packages\ofscraper\utils\exit.py", line 92, in inner
    raise E
  File "C:\Users\myUserName\AppData\Local\pipx\pipx\venvs\ofscraper\Lib\site-packages\ofscraper\utils\exit.py", line 85, in inner
    func(*args, **kwargs)
  File "C:\Users\myUserName\AppData\Local\pipx\pipx\venvs\ofscraper\Lib\site-packages\ofscraper\commands\scraper.py", line 59, in process_prompts
    check_auth()
  File "C:\Users\myUserName\AppData\Local\pipx\pipx\venvs\ofscraper\Lib\site-packages\ofscraper\commands\scraper.py", line 403, in check_auth
    auth.make_auth(auth=auth.read_auth())
                        ^^^^^^^^^^^^^^^^
  File "C:\Users\myUserName\AppData\Local\pipx\pipx\venvs\ofscraper\Lib\site-packages\ofscraper\utils\auth.py", line 64, in read_auth
    make_request_auth()
  File "C:\Users\myUserName\AppData\Local\pipx\pipx\venvs\ofscraper\Lib\site-packages\ofscraper\utils\auth.py", line 271, in make_request_auth
    result = get_request_auth()
             ^^^^^^^^^^^^^^^^^^
  File "C:\Users\myUserName\AppData\Local\pipx\pipx\venvs\ofscraper\Lib\site-packages\ofscraper\utils\auth.py", line 293, in get_request_auth
    return get_request_auth_deviint()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\myUserName\AppData\Local\pipx\pipx\venvs\ofscraper\Lib\site-packages\tenacity\__init__.py", line 289, in wrapped_f
    return self(f, *args, **kw)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\myUserName\AppData\Local\pipx\pipx\venvs\ofscraper\Lib\site-packages\tenacity\__init__.py", line 379, in __call__
    do = self.iter(retry_state=retry_state)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\myUserName\AppData\Local\pipx\pipx\venvs\ofscraper\Lib\site-packages\tenacity\__init__.py", line 326, in iter
    raise retry_exc from fut.exception()
tenacity.RetryError: RetryError[<Future at 0x2777606dd00 state=finished raised KeyError>]
```

Not entirely sure whats the problem, I am using the copy extension from the OF Cookie Helper with Firefox now. Thanks for the fast support! Writing from europe, hence the delay.

**Comment by cjb900** [comment]
Uninstall everything, the scraper, pipx, python. Then install python 3.11.6, then pipx, then version 3.5.4 of the scraper (if using pipx install it with `pipx install ofscraper==3.5.4`). Then **DO NOT** use the browser extension and enter your auth information directly into the auth.json file directly **NOT** into the scraper. That should get you all up and running.

**Comment by datawhores** [comment]
Your auth file must be incorrect
You can not paste from cookie helper directly please follow the template in the dics
