### ISSUE TITLE
Minimum size format error when provided in human readable format

### ISSUE THREAD

**Issue by ckramer** [datawhores/OF-Scraper#317]
**Describe the bug**
Entering human-readable format file size in Edit config mode causes crash.

Docker version.

**To Reproduce**

```
? What would you like to do? Edit config.json file
 [config.edit_config:189]  config path: /home/your_username/.config/your_username/config.json                                           config.py:189
? What would you like your main profile to be? main_profile
? save_location:  /home/ofscraper
? file_size_limit:  0
? file_size_min:  10mb


File size min
Input can be int representing bytes
or human readable such as 10mb

Enter 0 for no minimum
```
I entered literally what it suggested: `10mb`. (Also tried `10MB` , `10 MB`, `10 mb`)

```
Traceback (most recent call last):
  File "/venv/bin/ofscraper", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/venv/lib/python3.11/site-packages/ofscraper/__main__.py", line 10, in main
    start.main()
  File "/venv/lib/python3.11/site-packages/ofscraper/start.py", line 85, in main
    raise E
  File "/venv/lib/python3.11/site-packages/ofscraper/start.py", line 82, in main
    raise E
  File "/venv/lib/python3.11/site-packages/ofscraper/start.py", line 42, in main
    picker.pick()
  File "/venv/lib/python3.11/site-packages/ofscraper/commands/picker.py", line 20, in pick
    scraper.main()
  File "/venv/lib/python3.11/site-packages/ofscraper/commands/scraper.py", line 487, in main
    raise E
  File "/venv/lib/python3.11/site-packages/ofscraper/commands/scraper.py", line 469, in main
    scrapper()
  File "/venv/lib/python3.11/site-packages/ofscraper/commands/scraper.py", line 508, in scrapper
    process_prompts()
  File "/venv/lib/python3.11/site-packages/ofscraper/utils/exit.py", line 92, in inner
    raise E
  File "/venv/lib/python3.11/site-packages/ofscraper/utils/exit.py", line 85, in inner
    func(*args, **kwargs)
  File "/venv/lib/python3.11/site-packages/ofscraper/commands/scraper.py", line 81, in process_prompts
    config.edit_config()
  File "/venv/lib/python3.11/site-packages/ofscraper/utils/config.py", line 194, in edit_config
    updated_config = prompts.config_prompt(config["config"])
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/venv/lib/python3.11/site-packages/ofscraper/prompts/prompts.py", line 571, in config_prompt
    answer = promptClasses.batchConverter(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/venv/lib/python3.11/site-packages/ofscraper/prompts/promptConvert.py", line 222, in batchConverter
    outDict.update(list(map(lambda x: batchConverterHelper(x), args)))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/venv/lib/python3.11/site-packages/ofscraper/prompts/promptConvert.py", line 222, in <lambda>
    outDict.update(list(map(lambda x: batchConverterHelper(x), args)))
                                      ^^^^^^^^^^^^^^^^^^^^^^^
  File "/venv/lib/python3.11/site-packages/ofscraper/prompts/promptConvert.py", line 217, in batchConverterHelper
    return name, getType(ele_type)(**ele)
                 ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/venv/lib/python3.11/site-packages/ofscraper/prompts/promptConvert.py", line 57, in inner
    out = prompt_.execute()
          ^^^^^^^^^^^^^^^^^
  File "/venv/lib/python3.11/site-packages/InquirerPy/base/simple.py", line 339, in execute
    return self._filter(result)
           ^^^^^^^^^^^^^^^^^^^^
ValueError: invalid literal for int() with base 10: '10mb'
````

**Comment by datawhores** [comment]
should be fixed in repo
