### ISSUE TITLE
There is a problem that has troubled me for a long time, the problem of being unable to log in.

### ISSUE THREAD

**Issue by DVLM** [datawhores/OF-Scraper#322]
Every time I choose to download from the user, I get a verification failure [402], and the following code:
Traceback (most recent call last):
  File "C:\Users\chenyongcong\AppData\Local\pipx\pipx\venvs\ofscraper\Lib\site-packages\httpcore\_exceptions.py", line 10, in map_exceptions
    yield
  File "C:\Users\chenyongcong\AppData\Local\pipx\pipx\venvs\ofscraper\Lib\site-packages\httpcore\backends\sync.py", line 94, in connect_tcp
    sock = socket.create_connection(
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\chenyongcong\AppData\Local\Programs\Python\Python311\Lib\socket.py", line 827, in create_connection
    for res in getaddrinfo(host, port, 0, SOCK_STREAM):
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\chenyongcong\AppData\Local\Programs\Python\Python311\Lib\socket.py", line 962, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
socket.gaierror: [Errno 11004] getaddrinfo failed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\chenyongcong\AppData\Local\pipx\pipx\venvs\ofscraper\Lib\site-packages\httpx\_transports\default.py", line 60, in map_httpcore_exceptions
    yield
  File "C:\Users\chenyongcong\AppData\Local\pipx\pipx\venvs\ofscraper\Lib\site-packages\httpx\_transports\default.py", line 218, in handle_request
    resp = self._pool.handle_request(req)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\chenyongcong\AppData\Local\pipx\pipx\venvs\ofscraper\Lib\site-packages\httpcore\_sync\connection_pool.py", line 253, in handle_request
    raise exc
  File "C:\Users\chenyongcong\AppData\Local\pipx\pipx\venvs\ofscraper\Lib\site-packages\httpcore\_sync\connection_pool.py", line 237, in handle_request
    response = connection.handle_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\chenyongcong\AppData\Local\pipx\pipx\venvs\ofscraper\Lib\site-packages\httpcore\_sync\connection.py", line 86, in handle_request
    raise exc
  File "C:\Users\chenyongcong\AppData\Local\pipx\pipx\venvs\ofscraper\Lib\site-packages\httpcore\_sync\connection.py", line 63, in handle_request
    stream = self._connect(request)
             ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\chenyongcong\AppData\Local\pipx\pipx\venvs\ofscraper\Lib\site-packages\httpcore\_sync\connection.py", line 111, in _connect
    stream = self._network_backend.connect_tcp(**kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\chenyongcong\AppData\Local\pipx\pipx\venvs\ofscraper\Lib\site-packages\httpcore\backends\sync.py", line 93, in connect_tcp
    with map_exceptions(exc_map):
  File "C:\Users\chenyongcong\AppData\Local\Programs\Python\Python311\Lib\contextlib.py", line 155, in __exit__
    self.gen.throw(typ, value, traceback)
  File "C:\Users\chenyongcong\AppData\Local\pipx\pipx\venvs\ofscraper\Lib\site-packages\httpcore\_exceptions.py", line 14, in map_exceptions
    raise to_exc(exc)
httpcore.ConnectError: [Errno 11004] getaddrinfo failed

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\chenyongcong\AppData\Local\pipx\pipx\venvs\ofscraper\Lib\site-packages\tenacity\__init__.py", line 382, in __call__
    result = fn(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\chenyongcong\AppData\Local\pipx\pipx\venvs\ofscraper\Lib\site-packages\ofscraper\utils\auth.py", line 307, in get_request_auth_deviint
    with c.requests(DEVIINT)() as r:
  File "C:\Users\chenyongcong\AppData\Local\Programs\Python\Python311\Lib\contextlib.py", line 137, in __enter__
    return next(self.gen)
           ^^^^^^^^^^^^^^
  File "C:\Users\chenyongcong\AppData\Local\pipx\pipx\venvs\ofscraper\Lib\site-packages\ofscraper\classes\sessionbuilder.py", line 163, in _httpx_funct
    raise E
  File "C:\Users\chenyongcong\AppData\Local\pipx\pipx\venvs\ofscraper\Lib\site-packages\ofscraper\classes\sessionbuilder.py", line 161, in _httpx_funct
    t = self._session.request(method.upper(), **kwargs)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\chenyongcong\AppData\Local\pipx\pipx\venvs\ofscraper\Lib\site-packages\httpx\_client.py", line 821, in request
    return self.send(request, auth=auth, follow_redirects=follow_redirects)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\chenyongcong\AppData\Local\pipx\pipx\venvs\ofscraper\Lib\site-packages\httpx\_client.py", line 908, in send
    response = self._send_handling_auth(
               ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\chenyongcong\AppData\Local\pipx\pipx\venvs\ofscraper\Lib\site-packages\httpx\_client.py", line 936, in _send_handling_auth
    response = self._send_handling_redirects(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\chenyongcong\AppData\Local\pipx\pipx\venvs\ofscraper\Lib\site-packages\httpx\_client.py", line 973, in _send_handling_redirects
    response = self._send_single_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\chenyongcong\AppData\Local\pipx\pipx\venvs\ofscraper\Lib\site-packages\httpx\_client.py", line 1009, in _send_single_request
    response = transport.handle_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\chenyongcong\AppData\Local\pipx\pipx\venvs\ofscraper\Lib\site-packages\httpx\_transports\default.py", line 217, in handle_request
    with map_httpcore_exceptions():
  File "C:\Users\chenyongcong\AppData\Local\Programs\Python\Python311\Lib\contextlib.py", line 155, in __exit__
    self.gen.throw(typ, value, traceback)
  File "C:\Users\chenyongcong\AppData\Local\pipx\pipx\venvs\ofscraper\Lib\site-packages\httpx\_transports\default.py", line 77, in map_httpcore_exceptions
    raise mapped_exc(message) from exc
httpx.ConnectError: [Errno 11004] getaddrinfo failed

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "c:\users\chenyongcong\.local\bin\ofscraper.exe\__main__.py", line 7, in <module>
  File "C:\Users\chenyongcong\AppData\Local\pipx\pipx\venvs\ofscraper\Lib\site-packages\ofscraper\__main__.py", line 10, in main
    start.main()
  File "C:\Users\chenyongcong\AppData\Local\pipx\pipx\venvs\ofscraper\Lib\site-packages\ofscraper\start.py", line 85, in main
    raise E
  File "C:\Users\chenyongcong\AppData\Local\pipx\pipx\venvs\ofscraper\Lib\site-packages\ofscraper\start.py", line 82, in main
    raise E
  File "C:\Users\chenyongcong\AppData\Local\pipx\pipx\venvs\ofscraper\Lib\site-packages\ofscraper\start.py", line 42, in main
    picker.pick()
  File "C:\Users\chenyongcong\AppData\Local\pipx\pipx\venvs\ofscraper\Lib\site-packages\ofscraper\commands\picker.py", line 20, in pick
    scraper.main()
  File "C:\Users\chenyongcong\AppData\Local\pipx\pipx\venvs\ofscraper\Lib\site-packages\ofscraper\commands\scraper.py", line 487, in main
    raise E
  File "C:\Users\chenyongcong\AppData\Local\pipx\pipx\venvs\ofscraper\Lib\site-packages\ofscraper\commands\scraper.py", line 469, in main
    scrapper()
  File "C:\Users\chenyongcong\AppData\Local\pipx\pipx\venvs\ofscraper\Lib\site-packages\ofscraper\commands\scraper.py", line 508, in scrapper
    process_prompts()
  File "C:\Users\chenyongcong\AppData\Local\pipx\pipx\venvs\ofscraper\Lib\site-packages\ofscraper\utils\exit.py", line 92, in inner
    raise E
  File "C:\Users\chenyongcong\AppData\Local\pipx\pipx\venvs\ofscraper\Lib\site-packages\ofscraper\utils\exit.py", line 85, in inner
    func(*args, **kwargs)
  File "C:\Users\chenyongcong\AppData\Local\pipx\pipx\venvs\ofscraper\Lib\site-packages\ofscraper\commands\scraper.py", line 59, in process_prompts
    check_auth()
  File "C:\Users\chenyongcong\AppData\Local\pipx\pipx\venvs\ofscraper\Lib\site-packages\ofscraper\commands\scraper.py", line 403, in check_auth
    auth.make_auth(auth=auth.read_auth())
                        ^^^^^^^^^^^^^^^^
  File "C:\Users\chenyongcong\AppData\Local\pipx\pipx\venvs\ofscraper\Lib\site-packages\ofscraper\utils\auth.py", line 64, in read_auth
    make_request_auth()
  File "C:\Users\chenyongcong\AppData\Local\pipx\pipx\venvs\ofscraper\Lib\site-packages\ofscraper\utils\auth.py", line 271, in make_request_auth
    result = get_request_auth()
             ^^^^^^^^^^^^^^^^^^
  File "C:\Users\chenyongcong\AppData\Local\pipx\pipx\venvs\ofscraper\Lib\site-packages\ofscraper\utils\auth.py", line 293, in get_request_auth
    return get_request_auth_deviint()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\chenyongcong\AppData\Local\pipx\pipx\venvs\ofscraper\Lib\site-packages\tenacity\__init__.py", line 289, in wrapped_f
    return self(f, *args, **kw)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\chenyongcong\AppData\Local\pipx\pipx\venvs\ofscraper\Lib\site-packages\tenacity\__init__.py", line 379, in __call__
    do = self.iter(retry_state=retry_state)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\chenyongcong\AppData\Local\pipx\pipx\venvs\ofscraper\Lib\site-packages\tenacity\__init__.py", line 326, in iter
    raise retry_exc from fut.exception()
tenacity.RetryError: RetryError[<Future at 0x1506fd23690 state=finished raised ConnectError>]

what's wrong with this,ofscraper version is 3.6.8

**Comment by datawhores** [comment]
Try switching dynamic mode

**Comment by datawhores** [comment]
You can come to the discord for troubleshooting
