### ISSUE TITLE
Liking All Posts Throws Error : 'Model' object is not subscriptable

### ISSUE THREAD

**Issue by dodecaphone** [datawhores/OF-Scraper#332]
**Describe the bug**
Choosing "like all of a user's posts" creates a number of errors.

**To Reproduce**
Attempt to utilize "like all user's posts" function of the updated program/

**Expected behavior**
All posts of the chosen model would be "liked"

**Screenshots/Logs**
Status - UP
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\Sam\AppData\Local\Programs\Python\Python311\Scripts\ofscraper.exe\__main__.py", line 7, in <module>
  File "C:\Users\Sam\AppData\Local\Programs\Python\Python311\Lib\site-packages\ofscraper\__main__.py", line 10, in main
    start.main()
  File "C:\Users\Sam\AppData\Local\Programs\Python\Python311\Lib\site-packages\ofscraper\start.py", line 85, in main
    raise E
  File "C:\Users\Sam\AppData\Local\Programs\Python\Python311\Lib\site-packages\ofscraper\start.py", line 82, in main
    raise E
  File "C:\Users\Sam\AppData\Local\Programs\Python\Python311\Lib\site-packages\ofscraper\start.py", line 42, in main
    picker.pick()
  File "C:\Users\Sam\AppData\Local\Programs\Python\Python311\Lib\site-packages\ofscraper\commands\picker.py", line 20, in pick
    scraper.main()
  File "C:\Users\Sam\AppData\Local\Programs\Python\Python311\Lib\site-packages\ofscraper\commands\scraper.py", line 487, in main
    raise E
  File "C:\Users\Sam\AppData\Local\Programs\Python\Python311\Lib\site-packages\ofscraper\commands\scraper.py", line 469, in main
    scrapper()
  File "C:\Users\Sam\AppData\Local\Programs\Python\Python311\Lib\site-packages\ofscraper\commands\scraper.py", line 508, in scrapper
    process_prompts()
  File "C:\Users\Sam\AppData\Local\Programs\Python\Python311\Lib\site-packages\ofscraper\utils\exit.py", line 92, in inner
    raise E
  File "C:\Users\Sam\AppData\Local\Programs\Python\Python311\Lib\site-packages\ofscraper\utils\exit.py", line 85, in inner
    func(*args, **kwargs)
  File "C:\Users\Sam\AppData\Local\Programs\Python\Python311\Lib\site-packages\ofscraper\commands\scraper.py", line 67, in process_prompts
    run(process_like)
  File "C:\Users\Sam\AppData\Local\Programs\Python\Python311\Lib\site-packages\ofscraper\commands\scraper.py", line 330, in run
    run_helper(*functs)
  File "C:\Users\Sam\AppData\Local\Programs\Python\Python311\Lib\site-packages\ofscraper\commands\scraper.py", line 391, in run_helper
    raise E
  File "C:\Users\Sam\AppData\Local\Programs\Python\Python311\Lib\site-packages\ofscraper\commands\scraper.py", line 377, in run_helper
    job_func()
  File "C:\Users\Sam\AppData\Local\Programs\Python\Python311\Lib\site-packages\ofscraper\utils\exit.py", line 92, in inner
    raise E
  File "C:\Users\Sam\AppData\Local\Programs\Python\Python311\Lib\site-packages\ofscraper\utils\exit.py", line 85, in inner
    func(*args, **kwargs)
  File "C:\Users\Sam\AppData\Local\Programs\Python\Python311\Lib\site-packages\ofscraper\commands\scraper.py", line 259, in process_like
    active = list(filter(lambda x: x["active"], userdata))
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Sam\AppData\Local\Programs\Python\Python311\Lib\site-packages\ofscraper\commands\scraper.py", line 259, in <lambda>
    active = list(filter(lambda x: x["active"], userdata))
                                   ~^^^^^^^^^^
TypeError: 'Model' object is not subscriptable

**Desktop (please complete the following information):**

- OS: Windows 10
- Browser: Chrome
- Version: 121.0.6167.185
- python
- Python 3.11.4

**Comment by datawhores** [comment]
Please make sure you update to 3.7.1 or the dev version
