### ISSUE TITLE
Pipx Upgrade Command from 3.8.5 to 3.8.7 Fails and Displays Error

### ISSUE THREAD

**Issue by basketballhead6** [datawhores/OF-Scraper#348]
**Describe the bug**
When running pipx upgrade ofscraper the script errors out and fials to update.

**To Reproduce**
Run the upgrade command on a pipx environment

**Expected behavior**
Update scripts works and upgrades ofscraper to the latest release.

**Screenshots/Logs**  
```
error: subprocess-exited-with-error

  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [18 lines of output]
      Traceback (most recent call last):
        File "C:\Users\user\.local\pipx\shared\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 353, in <module>
          main()
        File "C:\Users\user\.local\pipx\shared\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\user\.local\pipx\shared\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
                 ^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\user\AppData\Local\Temp\pip-build-env-gw4tsykx\overlay\Lib\site-packages\setuptools\build_meta.py", line 325, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=['wheel'])
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\user\AppData\Local\Temp\pip-build-env-gw4tsykx\overlay\Lib\site-packages\setuptools\build_meta.py", line 295, in _get_build_requires
          self.run_setup()
        File "C:\Users\user\AppData\Local\Temp\pip-build-env-gw4tsykx\overlay\Lib\site-packages\setuptools\build_meta.py", line 311, in run_setup
          exec(code, locals())
        File "<string>", line 8, in <module>
      RuntimeError: uvloop does not support Windows at the moment
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.
'C:\\Users\\user\\.local\\pipx\\venvs\\ofscraper\\Scripts\\python.exe -m pip install --upgrade ofscraper -q' failed
```

**Desktop**

- OS: Windows
- Version: 3.8.5 upgrading to latest verion (3.8.7 as of submitting)
- Python - pipx

**Comment by Earthrot** [comment]
This seems to have been fixed in 3.8.7, installing with pipx gets the latest version from pypi which is 3.8.6 at this moment. You can update directly from the github release using:
`pipx install git+https://github.com/datawhores/OF-Scraper.git@180f291bfda0e24583fc8d9d81cd870b67d7cd8e`

**Comment by datawhores** [comment]
pypi has been updated

**Comment by basketballhead6** [comment]
> pypi has been updated

That fixed it. Thanks!
