### ISSUE TITLE
 Error: Cannot parse single argument of type <class 'tuple'>

### ISSUE THREAD

**Issue by axsddlr** [datawhores/OF-Scraper#363]
## Error: Cannot parse single argument of type <class 'tuple'>

**Description:**
While running the `ofscraper` package, an error occurs when trying to parse a tuple argument in the `arrow.get()` function, which is called from `ofscraper.api.timeline.get_timeline_media()`. The full traceback is as follows:

```
 2024-04-03 01:03:39:\[helpers.inner:9]  failed with exception: Cannot parse single argument of type <class 'tuple'>.
 2024-04-03 01:03:39:\[helpers.inner:9]  Traceback (most recent call last):
  File "C:\Users\AndreGPC\AppData\Local\Programs\Python\Python311\Lib\site-packages\ofscraper\actions\process.py", line 167, in normal_post_process
    combined_urls = OF.process_areas(ele, model_id)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\AndreGPC\AppData\Local\Programs\Python\Python311\Lib\site-packages\ofscraper\actions\scraper.py", line 479, in process_areas
    timeline_posts_dicts = process_timeline_posts(model_id, username)
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\AndreGPC\AppData\Local\Programs\Python\Python311\Lib\site-packages\ofscraper\utils\system\free.py", line 16, in inner
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\AndreGPC\AppData\Local\Programs\Python\Python311\Lib\site-packages\ofscraper\actions\scraper.py", line 184, in process_timeline_posts
    timeline.get_timeline_media(
  File "C:\Users\AndreGPC\AppData\Local\Programs\Python\Python311\Lib\site-packages\ofscraper\utils\context\run_async.py", line 26, in inner
    raise E
  File "C:\Users\GPC\AppData\Local\Programs\Python\Python311\Lib\site-packages\ofscraper\utils\context\run_async.py", line 14, in inner
    tasks = loop.run_until_complete(coro(*args, **kwargs))
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\GPC\AppData\Local\Programs\Python\Python311\Lib\asyncio\base_events.py", line 653, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "C:\Users\GPC\AppData\Local\Programs\Python\Python311\Lib\site-packages\ofscraper\api\timeline.py", line 208, in get_timeline_media
    Setting initial timeline scan date for {username} to {arrow.get(after).format('YYYY.MM.DD')}
                                                          ^^^^^^^^^^^^^^^^
  File "C:\Users\GPC\AppData\Local\Programs\Python\Python311\Lib\site-packages\arrow\api.py", line 91, in get
    return _factory.get(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\GPC\AppData\Local\Programs\Python\Python311\Lib\site-packages\arrow\factory.py", line 267, in get
    raise TypeError(f"Cannot parse single argument of type {type(arg)!r}.")
TypeError: Cannot parse single argument of type <class 'tuple'>.

 2024-04-03 01:03:39:\[process.scrape_context_manager:58] 
 ```
 **Steps to Reproduce:**
1. Run the `ofscraper` package with the provided configurations.
2. The error occurs when calling `ofscraper.api.timeline.get_timeline_media()`.

**Expected Behavior:**
The `arrow.get()` function should be able to parse the provided argument(s) correctly, without raising a `TypeError`.

**Environment:**
- Python version: Python 3.11
- `ofscraper` package version: Version 0.0.0+main.6f8df0c - ofscraper-3.8.12
- Key Mode: manual
- Operating System: Windows 11

**Comment by datawhores** [comment]
Thanks this was fixed in
3.8.13
