### ISSUE TITLE
AttributeError: module 'ofscraper.download.common.globals' has no attribute 'desc'

### ISSUE THREAD

**Issue by knoxitus** [datawhores/OF-Scraper#369]
**Describe the bug**
The download script is failing because of a script error, it tries to access some missing attributes.

**Screenshots/Logs**
error log:

``` log
...
 2024-04-14 16:41:38:\[text.textDownloader:19]  Skipping Downloading of Text Files
 2024-04-14 16:41:38:\[downloadbatch.process_dicts:61]  Number of process 4
 2024-04-14 16:41:38:\[helpers.inner:9]  failed with exception: module 'ofscraper.download.common.globals' has no attribute 'desc'
 2024-04-14 16:41:38:\[helpers.inner:9]  Traceback (most recent call last):
  File "/venv/lib/python3.11/site-packages/ofscraper/actions/process.py", line 165, in normal_post_process
    download.download_process(
  File "/venv/lib/python3.11/site-packages/ofscraper/download/download.py", line 55, in download_process
    download_picker(username, model_id, medialist)
  File "/venv/lib/python3.11/site-packages/ofscraper/download/download.py", line 73, in download_picker
    return batchdownloader.process_dicts(username, model_id, medialist)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/venv/lib/python3.11/site-packages/ofscraper/download/downloadbatch.py", line 211, in process_dicts
    raise E
  File "/venv/lib/python3.11/site-packages/ofscraper/download/downloadbatch.py", line 205, in process_dicts
    raise E
  File "/venv/lib/python3.11/site-packages/ofscraper/download/downloadbatch.py", line 102, in process_dicts
    common_globals.desc.format(
    ^^^^^^^^^^^^^^^^^^^
AttributeError: module 'ofscraper.download.common.globals' has no attribute 'desc'

 2024-04-14 16:41:38:\[process.scrape_context_manager:59]  
```

**System Info**

- running docker image in docker on linux

**Additional context**
In the file [download/downloadbatch.py](https://github.com/datawhores/OF-Scraper/blob/fecdcbedb37be1dee419abec9cc62a2088417537/ofscraper/download/downloadbatch.py#L102) the attribute `common_globals.desc` is used but it was removed in [download/common/globals.py](https://github.com/datawhores/OF-Scraper/commit/c0e2b98eb862cdadec96b26a4d7fae2ac7a5dcd7#diff-60fd56b343a1ee82e5c5128668c9f3e6f60a0799dc56f247af9ea4d550ea4ead) in a commit.

**Comment by datawhores** [comment]
This should be fixed

**Comment by datawhores** [comment]
No response in a month please open new issue if needed
