### ISSUE TITLE
Not enough placeholders when writing to database

### ISSUE THREAD

**Issue by blade2005** [datawhores/OF-Scraper#373]
https://github.com/datawhores/OF-Scraper/blob/main/ofscraper/db/operations_/media.py#L419
https://github.com/datawhores/OF-Scraper/blob/main/ofscraper/db/operations_/media.py#L124C5-L128C57

16 placeholders, 17 fields.

The odd one out is `unlocked`

``` 2024-04-22 15:46:19:\[helpers.inner:11]  failed with exception: Incorrect number of bindings supplied. The current statement uses 16, and there are 17 supplied.
 2024-04-22 15:46:19:\[helpers.inner:11]  Traceback (most recent call last):
  File "/home/your_username/.pyenv/versions/3.11.7/lib/python3.11/site-packages/ofscraper/actions/process.py", line 163, in normal_post_process
    operations.table_init_create(model_id=model_id, username=ele.name)
  File "/home/your_username/.pyenv/versions/3.11.7/lib/python3.11/site-packages/ofscraper/utils/context/run_async.py", line 29, in inner
    raise E
  File "/home/your_username/.pyenv/versions/3.11.7/lib/python3.11/site-packages/ofscraper/utils/context/run_async.py", line 15, in inner
    tasks = loop.run_until_complete(coro(*args, **kwargs))
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "uvloop/loop.pyx", line 1517, in uvloop.loop.Loop.run_until_complete
  File "/home/your_username/.pyenv/versions/3.11.7/lib/python3.11/site-packages/ofscraper/db/operations.py", line 260, in table_init_create
    await modify_tables(model_id, username)
  File "/home/your_username/.pyenv/versions/3.11.7/lib/python3.11/site-packages/ofscraper/db/operations.py", line 82, in modify_tables
    raise E
  File "/home/your_username/.pyenv/versions/3.11.7/lib/python3.11/site-packages/ofscraper/db/operations.py", line 77, in modify_tables
    await modify_tables_constraints_and_columns(
  File "/home/your_username/.pyenv/versions/3.11.7/lib/python3.11/site-packages/ofscraper/db/operations.py", line 175, in modify_tables_constraints_and_columns
    await modify_unique_constriant_media(model_id=model_id, username=username)
  File "/home/your_username/.pyenv/versions/3.11.7/lib/python3.11/site-packages/ofscraper/db/operations_/media.py", line 579, in modify_unique_constriant_media
    await write_media_table_transition(data, model_id=model_id, username=username)
  File "/home/your_username/.pyenv/versions/3.11.7/lib/python3.11/site-packages/ofscraper/db/operations_/wrapper.py", line 69, in inner
    raise E
  File "/home/your_username/.pyenv/versions/3.11.7/lib/python3.11/site-packages/ofscraper/db/operations_/wrapper.py", line 51, in inner
    return await loop.run_in_executor(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/your_username/.pyenv/versions/3.11.7/lib/python3.11/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/your_username/.pyenv/versions/3.11.7/lib/python3.11/site-packages/ofscraper/db/operations_/media.py", line 422, in write_media_table_transition
    curr.executemany(mediaInsertTransition, insertData)
sqlite3.ProgrammingError: Incorrect number of bindings supplied. The current statement uses 16, and there are 17 supplied.```

Even though I gave the current code references I am on on v 3.9.0

**Comment by datawhores** [comment]
I'll push a fix soon
