### ISSUE TITLE
Error before downloading content which leads to same content being redownloaded each scrape

### ISSUE THREAD

**Issue by basketballhead6** [datawhores/OF-Scraper#379]
## Describe the bug

An error message occurs before the downloading of scraped content begins. It appears like the database is not marking that it is downloaded and this is leading to the same content being redownloaded again each scrape.

## To Reproduce

Run the script using verion 3.9.8, and download a model's content.

## Expected behavior

No error occurs and content is not redownloaded on each scrape.

## Screenshots/Logs
Error when using --log debug
 ```
 File "C:\Users\user\.local\pipx\venvs\ofscraper\Lib\site-packages\ofscraper\api\paid.py", line 68, in process_tasks
    result, new_tasks_batch = await task
                              ^^^^^^^^^^
  File "C:\Python311\Lib\asyncio\tasks.py", line 605, in _wait_for_one
    return f.result()  # May raise f.exception().
           ^^^^^^^^^^
  File "C:\Users\user\.local\pipx\venvs\ofscraper\Lib\site-packages\ofscraper\api\paid.py", line 170, in scrape_paid
    job_progress.remove_task(task) if task and job_progress else None
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\.local\pipx\venvs\ofscraper\Lib\site-packages\rich\progress.py", line 1634, in remove_task
    del self._tasks[task_id]
        ~~~~~~~~~~~^^^^^^^^^
KeyError: 1
```

Error in Powershell Output
```
Task exception was never retrieved
future: <Task finished name='Task-647' coro=<scrape_paid() done, defined at C:\Users\user\.local\pipx\venvs\ofscraper\Lib\site-packages\ofscraper\api\paid.py:115> exception=KeyError(2)>
Traceback (most recent call last):
  File "C:\Users\user\.local\pipx\venvs\ofscraper\Lib\site-packages\ofscraper\api\paid.py", line 170, in scrape_paid
    job_progress.remove_task(task) if task and job_progress else None
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\.local\pipx\venvs\ofscraper\Lib\site-packages\rich\progress.py", line 1634, in remove_task
    del self._tasks[task_id]
        ~~~~~~~~~~~^^^^^^^^^
KeyError: 2
Task exception was never retrieved
future: <Task finished name='Task-738' coro=<scrape_paid() done, defined at C:\Users\user\.local\pipx\venvs\ofscraper\Lib\site-packages\ofscraper\api\paid.py:115> exception=KeyError(3)>
Traceback (most recent call last):
  File "C:\Users\user\.local\pipx\venvs\ofscraper\Lib\site-packages\ofscraper\api\paid.py", line 170, in scrape_paid
    job_progress.remove_task(task) if task and job_progress else None
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\.local\pipx\venvs\ofscraper\Lib\site-packages\rich\progress.py", line 1634, in remove_task
    del self._tasks[task_id]
        ~~~~~~~~~~~^^^^^^^^^
KeyError: 3
```

## Config

https://pastebin.com/bb2TX5Ae

## System Info

- OS: Windows 11
- Version: 3.9.8
- Pipx installation

**Comment by datawhores** [comment]
Please try 3.10dev3
 and see if that fixes the issue

**Comment by basketballhead6** [comment]
> Please try 3.10dev3 and see if that fixes the issue

I can't install 3.10dev3 pre release via pipx as it doesn't have it. Only shows dev versions 1 & 2

**Comment by basketballhead6** [comment]
I get the following error when I use the 3.10 dev 4 prerelease. This happens just after you select what models you want to scrape.

```
[WinError 6] The handle is invalid
Traceback (most recent call last):
  File "C:\Users\user\.local\pipx\venvs\ofscraper\Lib\site-packages\ofscraper\utils\logs\stdout.py", line 37, in logger_process
    messages = funct(timeout=constants.getattr("LOGGER_TIMEOUT"))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\multiprocessing\queues.py", line 113, in get
    if not self._poll(timeout):
           ^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\multiprocessing\connection.py", line 256, in poll
    return self._poll(timeout)
           ^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\multiprocessing\connection.py", line 329, in _poll
    return bool(wait([self], timeout))
                ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\multiprocessing\connection.py", line 882, in wait
    ov.cancel()
OSError: [WinError 6] The handle is invalid

Queue <multiprocessing.queues.Queue object at 0x0000012FCBB9B910> is closed
Traceback (most recent call last):
  File "C:\Users\user\.local\pipx\venvs\ofscraper\Lib\site-packages\ofscraper\utils\logs\stdout.py", line 37, in logger_process
    messages = funct(timeout=constants.getattr("LOGGER_TIMEOUT"))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\multiprocessing\queues.py", line 100, in get
    raise ValueError(f"Queue {self!r} is closed")
ValueError: Queue <multiprocessing.queues.Queue object at 0x0000012FCBB9B910> is closed

Queue <multiprocessing.queues.Queue object at 0x0000012FCBB9B910> is closed
Traceback (most recent call last):
  File "C:\Users\user\.local\pipx\venvs\ofscraper\Lib\site-packages\ofscraper\utils\logs\stdout.py", line 37, in logger_process
    messages = funct(timeout=constants.getattr("LOGGER_TIMEOUT"))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\multiprocessing\queues.py", line 100, in get
    raise ValueError(f"Queue {self!r} is closed")
ValueError: Queue <multiprocessing.queues.Queue object at 0x0000012FCBB9B910> is closed

Queue <multiprocessing.queues.Queue object at 0x0000012FCBB9B910> is closed
Traceback (most recent call last):
  File "C:\Users\user\.local\pipx\venvs\ofscraper\Lib\site-packages\ofscraper\utils\logs\stdout.py", line 37, in logger_process
    messages = funct(timeout=constants.getattr("LOGGER_TIMEOUT"))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\multiprocessing\queues.py", line 100, in get
    raise ValueError(f"Queue {self!r} is closed")
ValueError: Queue <multiprocessing.queues.Queue object at 0x0000012FCBB9B910> is closed

Queue <multiprocessing.queues.Queue object at 0x0000012FCBB9B910> is closed
Traceback (most recent call last):
  File "C:\Users\user\.local\pipx\venvs\ofscraper\Lib\site-packages\ofscraper\utils\logs\stdout.py", line 37, in logger_process
    messages = funct(timeout=constants.getattr("LOGGER_TIMEOUT"))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\multiprocessing\queues.py", line 100, in get
    raise ValueError(f"Queue {self!r} is closed")
ValueError: Queue <multiprocessing.queues.Queue object at 0x0000012FCBB9B910> is closed

Queue <multiprocessing.queues.Queue object at 0x0000012FCBB9B910> is closed
Traceback (most recent call last):
  File "C:\Users\user\.local\pipx\venvs\ofscraper\Lib\site-packages\ofscraper\utils\logs\stdout.py", line 37, in logger_process
    messages = funct(timeout=constants.getattr("LOGGER_TIMEOUT"))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\multiprocessing\queues.py", line 100, in get
    raise ValueError(f"Queue {self!r} is closed")
ValueError: Queue <multiprocessing.queues.Queue object at 0x0000012FCBB9B910> is closed

Queue <multiprocessing.queues.Queue object at 0x0000012FCBB9B910> is closed
Traceback (most recent call last):
  File "C:\Users\user\.local\pipx\venvs\ofscraper\Lib\site-packages\ofscraper\utils\logs\stdout.py", line 37, in logger_process
    messages = funct(timeout=constants.getattr("LOGGER_TIMEOUT"))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\multiprocessing\queues.py", line 100, in get
    raise ValueError(f"Queue {self!r} is closed")
ValueError: Queue <multiprocessing.queues.Queue object at 0x0000012FCBB9B910> is closed

Queue <multiprocessing.queues.Queue object at 0x0000012FCBB9B910> is closed
Traceback (most recent call last):
  File "C:\Users\user\.local\pipx\venvs\ofscraper\Lib\site-packages\ofscraper\utils\logs\stdout.py", line 37, in logger_process
    messages = funct(timeout=constants.getattr("LOGGER_TIMEOUT"))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\multiprocessing\queues.py", line 100, in get
    raise ValueError(f"Queue {self!r} is closed")
ValueError: Queue <multiprocessing.queues.Queue object at 0x0000012FCBB9B910> is closed

Queue <multiprocessing.queues.Queue object at 0x0000012FCBB9B910> is closed
Traceback (most recent call last):
  File "C:\Users\user\.local\pipx\venvs\ofscraper\Lib\site-packages\ofscraper\utils\logs\stdout.py", line 37, in logger_process
    messages = funct(timeout=constants.getattr("LOGGER_TIMEOUT"))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\multiprocessing\queues.py", line 100, in get
    raise ValueError(f"Queue {self!r} is closed")
ValueError: Queue <multiprocessing.queues.Queue object at 0x0000012FCBB9B910> is closed
```

**Comment by basketballhead6** [comment]
> Please try 3.10dev3 and see if that fixes the issue

Can confirm runing 3.10dev4 fixes the issue and model's content is not redownloaded anymore.
