### ISSUE TITLE
Download Content from User doesn't work after script used once

### ISSUE THREAD

**Issue by basketballhead6** [datawhores/OF-Scraper#390]
## Describe the bug

The script does not download content again after it has been run once. It tries to start again but instanly finishes going back to the context menu with the error being thrown into the log file. 

## To Reproduce

1. Run the script and let it complete.
2. Select 'perform actions'
3. Confirm choices to download your content

## Expected behavior

Script restarts as normal

## Screenshots/Logs

```
 2024-05-30 16:04:45:[helpers.inner:11]  failed with exception: 'NoneType' object has no attribute 'completed'
 2024-05-30 16:04:45:[helpers.inner:11]  Traceback (most recent call last):
  File "C:\Users\user\.local\pipx\venvs\ofscraper\Lib\site-packages\ofscraper\commands\helpers\normal.py", line 24, in wrapper
    data_helper(ele)
  File "C:\Users\user\.local\pipx\venvs\ofscraper\Lib\site-packages\ofscraper\commands\helpers\data.py", line 23, in data_helper
    count = progress_utils.get_user_task_obj().completed
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'completed'

 2024-05-30 16:04:45:[helpers.inner:11]  failed with exception: 'NoneType' object has no attribute 'completed'
 2024-05-30 16:04:45:[helpers.inner:11]  Traceback (most recent call last):
  File "C:\Users\user\.local\pipx\venvs\ofscraper\Lib\site-packages\ofscraper\commands\helpers\normal.py", line 24, in wrapper
    data_helper(ele)
  File "C:\Users\user\.local\pipx\venvs\ofscraper\Lib\site-packages\ofscraper\commands\helpers\data.py", line 23, in data_helper
    count = progress_utils.get_user_task_obj().completed
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'completed'

 2024-05-30 16:04:45:[helpers.inner:11]  failed with exception: 'NoneType' object has no attribute 'completed'
 2024-05-30 16:04:45:[helpers.inner:11]  Traceback (most recent call last):
  File "C:\Users\user\.local\pipx\venvs\ofscraper\Lib\site-packages\ofscraper\commands\helpers\normal.py", line 24, in wrapper
    data_helper(ele)
  File "C:\Users\user\.local\pipx\venvs\ofscraper\Lib\site-packages\ofscraper\commands\helpers\data.py", line 23, in data_helper
    count = progress_utils.get_user_task_obj().completed
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'completed'

 2024-05-30 16:04:45:[helpers.inner:11]  failed with exception: 'NoneType' object has no attribute 'completed'
 2024-05-30 16:04:45:[helpers.inner:11]  Traceback (most recent call last):
  File "C:\Users\user\.local\pipx\venvs\ofscraper\Lib\site-packages\ofscraper\commands\helpers\normal.py", line 24, in wrapper
    data_helper(ele)
  File "C:\Users\user\.local\pipx\venvs\ofscraper\Lib\site-packages\ofscraper\commands\helpers\data.py", line 23, in data_helper
    count = progress_utils.get_user_task_obj().completed
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'completed'

 2024-05-30 16:04:45:[scrape_context.scrape_context_manager:37]  
===========================
 Script Finished 
Run Time:  0:00:05
===========================
```

## Config

https://pastebin.com/bb2TX5Ae

## System Info

- OS: Windows 11
- Version: 3.10dev7
- Pipx installation

**Comment by basketballhead6** [comment]
Can confirm this fixes the issue.
