### ISSUE TITLE
Traceback on NoneType for Content-Length

### ISSUE THREAD

**Issue by Jules-WinnfieldX** [datawhores/OF-Scraper#392]
## Describe the bug

Assuming this happens while being ratelimited

## To Reproduce

Happens during repeated/large scrapes

## Screenshots/Logs
```
TRACEBACK_  [helpers.inner:11]  Media:2518764803 Post:359706587  int() argument must be a string, a bytes-like object or a real number, not    helpers.py:11
           'NoneType'
 [downloadnormal.download:200]  Media:2518764803 Post:359706587 exception int() argument must be a string, a bytes-like object or a    downloadnormal.py:200
real number, not 'NoneType'
 [downloadnormal.download:201]  Media:2518764803 Post:359706587 exception Traceback (most recent call last):                           downloadnormal.py:201
  File "C:\Users\your_username\Desktop\OFScraper\venv3.10\Lib\site-packages\ofscraper\download\downloadnormal.py", line 183, in
download
    return await main_download(
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\your_username\Desktop\OFScraper\venv3.10\Lib\site-packages\ofscraper\download\main_download.py", line 56, in
main_download
    result = await main_download_downloader(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\your_username\Desktop\OFScraper\venv3.10\Lib\site-packages\ofscraper\download\main_download.py", line 75, in
main_download_downloader
    async for _ in download_retry():
  File "C:\Users\your_username\Desktop\OFScraper\venv3.10\Lib\site-packages\tenacity\_asyncio.py", line 123, in __anext__
    do = await self.iter(retry_state=self._retry_state)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\your_username\Desktop\OFScraper\venv3.10\Lib\site-packages\tenacity\_asyncio.py", line 110, in iter
    result = await action(retry_state)
             ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\your_username\Desktop\OFScraper\venv3.10\Lib\site-packages\tenacity\_asyncio.py", line 78, in inner
    return fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\your_username\Desktop\OFScraper\venv3.10\Lib\site-packages\tenacity\__init__.py", line 410, in exc_check
    raise retry_exc.reraise()
          ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\your_username\Desktop\OFScraper\venv3.10\Lib\site-packages\tenacity\__init__.py", line 183, in reraise
    raise self.last_attempt.result()
          ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\your_username\AppData\Local\Programs\Python\Python311\Lib\concurrent\futures\_base.py", line 449, in result
    return self.__get_result()
           ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\your_username\AppData\Local\Programs\Python\Python311\Lib\concurrent\futures\_base.py", line 401, in __get_result
    raise self._exception
  File "C:\Users\your_username\Desktop\OFScraper\venv3.10\Lib\site-packages\ofscraper\download\main_download.py", line 108, in
main_download_downloader
    raise E
  File "C:\Users\your_username\Desktop\OFScraper\venv3.10\Lib\site-packages\ofscraper\download\main_download.py", line 86, in
main_download_downloader
    return await main_data_handler(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\your_username\Desktop\OFScraper\venv3.10\Lib\site-packages\ofscraper\download\main_download.py", line 124, in
main_data_handler
    total = int(data.get("content-length"))
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: int() argument must be a string, a bytes-like object or a real number, not 'NoneType'

 [downloadnormal.process_dicts:99]  unpack ('skipped', 0) count 2                                                                       downloadnormal.py:99
TRACEBACK_  [helpers.inner:11]  Media:2171225054 Post:173537588  Traceback (most recent call last):                                            helpers.py:11
             File "C:\Users\your_username\Desktop\OFScraper\venv3.10\Lib\site-packages\ofscraper\download\main_download.py", line 86, in
           main_download_downloader
               return await main_data_handler(
                      ^^^^^^^^^^^^^^^^^^^^^^^^
             File "C:\Users\your_username\Desktop\OFScraper\venv3.10\Lib\site-packages\ofscraper\download\main_download.py", line 124, in
           main_data_handler
               total = int(data.get("content-length"))
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
           TypeError: int() argument must be a string, a bytes-like object or a real number, not 'NoneType'
```

## Config

https://privatebin.io/?9c1fd4c97a5465e0#8mXDDaQYYzkwMaKHWGBMaSBRQV853Lheyj2gD3pH4s7A

## System Info

- OS: Win 11
- Browser: Firefox
- Python: 3.11.4
- Latest Commit

**Comment by datawhores** [comment]
does this happen with the latest dev release

**Comment by Jules-WinnfieldX** [comment]
> does this happen with the latest dev release

It was happening yes. It's been a min since I've used it, and it's a very intermittent issue
