### ISSUE TITLE
files with .part extension

### ISSUE THREAD

**Issue by bezaaas** [datawhores/OF-Scraper#394]
Thank you for your work!

Some files downloaded and everything okay, but some files has .part extension and I think these are DRM files but they don’t open, tried with 3.9.9 and 3.9.10, the same problem.
![1233](https://github.com/datawhores/OF-Scraper/assets/120327768/e6170764-35d0-4320-b7f3-9dad3d4c31d0)

**Comment by datawhores** [comment]
please add the required materials

**Comment by bezaaas** [comment]
now i have another issue

 2024-06-02 19:04:38:\[main.filterPost:92]  filter 1-> initial posts no filter count: 386
 2024-06-02 19:04:38:\[main.filterPost:97]  filter 2->  post date sort filter count: 386
 2024-06-02 19:04:38:\[main.filterPost:102]  filter 3-> post dupe filter count: 386
 2024-06-02 19:04:38:\[main.filterPost:106]  filter 4-> timed posts filter count: 386
 2024-06-02 19:04:38:\[main.filterPost:111]  filter 5->  post text filter count: 386
 2024-06-02 19:04:38:\[main.filterPost:116]  filter 6->  post excluded text filter count 386
 2024-06-02 19:04:38:\[main.filterPost:121]  filter 7->  mass msg filter count 386
 2024-06-02 19:04:38:\[helpers.final_post_sort:219]  Using download sort None
 2024-06-02 19:04:38:\[main.post_filter_for_like:132]  Number of unlikable posts left after filtering for likeable posts 0
 2024-06-02 19:04:38:\[helpers.final_post_sort:219]  Using download sort None
 2024-06-02 19:04:38:\[main.post_filter_for_like:137]  Final Number of open and unlikable post 0
 2024-06-02 19:04:38:\[download.downloader:33]  Performing Downloading Action on laeticia.versa
 2024-06-02 19:04:38:\[text.textDownloader:18]  Skipping Downloading of Text Files
 2024-06-02 19:04:38:\[helpers.inner:11]  failed with exception: name 'metadata_mode' is not defined
 2024-06-02 19:04:38:\[helpers.inner:11]  Traceback (most recent call last):
  File "commands\scraper\runner.py", line 84, in process_actions_for_user
  File "commands\helpers\context.py", line 36, in wrapper
  File "commands\scraper\runner.py", line 100, in execute_user_action
  File "commands\scraper\actions\download.py", line 34, in downloader
  File "download\download.py", line 22, in download_process
  File "download\download.py", line 41, in download_picker
  File "download\downloadbatch.py", line 54, in process_dicts
NameError: name 'metadata_mode' is not defined

 2024-06-02 19:04:38:\[scrape_context.scrape_context_manager:37]  
===========================
 Script Finished 
Run Time:  0:01:00

**Comment by j-ktz** [comment]
I'm having the same issue, was this ever resolved?
