### ISSUE TITLE
[3.9.10] Missing models

### ISSUE THREAD

**Issue by CannotTouch** [datawhores/OF-Scraper#395]
Retriving the models using

`ofscraper_windows_3.9.10.exe -a download -ts --after 20240516 -o all -ul LIST1,LIST2,LIST3`

there are several models missing.

In the log i found this error:

 2024-06-02 14:35:00:\[helpers.inner:11]  3
 2024-06-02 14:35:00:\[helpers.inner:11]  Traceback (most recent call last):
  File "ofscraper\api\subscriptions\lists.py", line 212, in get_list_users
    with ThreadPoolExecutor(
                    ^^^^^^^^
  File "rich\progress.py", line 1425, in update
KeyError: 3

 2024-06-02 14:35:00:\[helpers.inner:11]  3
 2024-06-02 14:35:00:\[helpers.inner:11]  Traceback (most recent call last):
  File "ofscraper\api\subscriptions\lists.py", line 212, in get_list_users
    with ThreadPoolExecutor(
                    ^^^^^^^^
  File "rich\progress.py", line 1425, in update
KeyError: 3

 2024-06-02 14:35:00:\[helpers.inner:11]  3
 2024-06-02 14:35:00:\[helpers.inner:11]  Traceback (most recent call last):
  File "ofscraper\api\subscriptions\lists.py", line 212, in get_list_users
    with ThreadPoolExecutor(
                    ^^^^^^^^
  File "rich\progress.py", line 1425, in update
KeyError: 3

this error is repeated after every list.
THe result is just that the list is not complete, but for models on the list all works fine.

**Comment by datawhores** [comment]
Please update to the latest dev release

**Comment by CannotTouch** [comment]
with the https://github.com/datawhores/OF-Scraper/commit/d68a25cdf6118da8cedfdae761cc62a3d48a03fe I have still the issue:

2024-06-02 20:03:39:[request.get_request_auth:49]  getting new signature
 2024-06-02 20:03:42:[request.get_request_auth:49]  getting new signature
 2024-06-02 20:03:44:[request.get_request_auth:49]  getting new signature
 2024-06-02 20:03:47:[helpers.inner:11]  3
 2024-06-02 20:03:47:[helpers.inner:11]  Traceback (most recent call last):
  File "ofscraper\api\subscriptions\lists.py", line 212, in get_list_users
    with ThreadPoolExecutor(
                    ^^^^^^^^
  File "rich\progress.py", line 1425, in update
KeyError: 3

 2024-06-02 20:03:47:[helpers.inner:11]  3
 2024-06-02 20:03:47:[helpers.inner:11]  Traceback (most recent call last):
  File "ofscraper\api\subscriptions\lists.py", line 212, in get_list_users
    with ThreadPoolExecutor(
                    ^^^^^^^^
  File "rich\progress.py", line 1425, in update
KeyError: 3

 2024-06-02 20:03:47:[helpers.inner:11]  3
 2024-06-02 20:03:47:[helpers.inner:11]  Traceback (most recent call last):
  File "ofscraper\api\subscriptions\lists.py", line 212, in get_list_users
    with ThreadPoolExecutor(
                    ^^^^^^^^
  File "rich\progress.py", line 1425, in update
KeyError: 3




with the https://github.com/datawhores/OF-Scraper/releases/tag/3.10.dev10 still model missing and this error in the log:
2024-06-02 20:12:48:[helpers.inner:11]  3
 2024-06-02 20:12:48:[helpers.inner:11]  Traceback (most recent call last):
  File "ofscraper\api\subscriptions\lists.py", line 212, in get_list_users
    with ThreadPoolExecutor(
                    ^^^^^^^^
  File "rich\progress.py", line 1425, in update
KeyError: 3

**Comment by datawhores** [comment]
https://pypi.org/project/ofscraper/3.10.dev10/

**Comment by CannotTouch** [comment]
same issue with the regular install too.

Python 3.12.1

`pip install ofscraper==3.10.dev10` (all installed correctly requirements included)

`ofscraper -a download -ts --after 20240516 -o all -ul LISTNAME,LISTNAME2,LISTNAME3`

2024-06-03 17:48:41:[helpers.inner:11]  3
 2024-06-03 17:48:41:[helpers.inner:11]  Traceback (most recent call last):
  File "C:\Users\BlaBla\AppData\Local\Programs\Python\Python312\Lib\site-packages\ofscraper\api\subscriptions\lists.py", line 212, in get_list_users
    progress_utils.userlist_overall_progress.update(
  File "C:\Users\BlaBla\AppData\Local\Programs\Python\Python312\Lib\site-packages\rich\progress.py", line 1425, in update
    task = self._tasks
           ~~~~~~~~~~~^^^^^^^^^
KeyError: 3

**Comment by datawhores** [comment]
Are you still having issues

**Comment by CannotTouch** [comment]
with the https://github.com/datawhores/OF-Scraper/commit/b3048ee0e2911a0c98fd852c331548d518c3bfa9 is fixed on both the versions (windows and normal).
thanks for the support
