### ISSUE TITLE
ValueError: expected ':' after conversion specifier

### ISSUE THREAD

**Issue by guyhurst90** [datawhores/OF-Scraper#396]
## Describe the bug

Downloads fail with the following error:

```
2024-06-02 13:38:37:[helpers.inner:11]  Media:3317893614 Post:1068586380  expected ':' after conversion specifier
 2024-06-02 13:38:37:[downloadnormal.download:210]  Media:3317893614 Post:1068586380 exception expected ':' after conversion specifier
 2024-06-02 13:38:37:[downloadnormal.download:211]  Media:3317893614 Post:1068586380 exception Traceback (most recent call last):
  File "/home/your_username/.local/pipx/venvs/ofscraper/lib/python3.12/site-packages/ofscraper/download/downloadnormal.py", line 195, in download
    return await main_download(
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/your_username/.local/pipx/venvs/ofscraper/lib/python3.12/site-packages/ofscraper/download/main_download.py", line 66, in main_download
    result = await main_download_downloader(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/your_username/.local/pipx/venvs/ofscraper/lib/python3.12/site-packages/ofscraper/download/main_download.py", line 84, in main_download_downloader
    async for _ in download_retry():
  File "/home/your_username/.local/pipx/venvs/ofscraper/lib/python3.12/site-packages/tenacity/_asyncio.py", line 123, in __anext__
    do = await self.iter(retry_state=self._retry_state)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/your_username/.local/pipx/venvs/ofscraper/lib/python3.12/site-packages/tenacity/_asyncio.py", line 110, in iter
    result = await action(retry_state)
             ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/your_username/.local/pipx/venvs/ofscraper/lib/python3.12/site-packages/tenacity/_asyncio.py", line 78, in inner
    return fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^
  File "/home/your_username/.local/pipx/venvs/ofscraper/lib/python3.12/site-packages/tenacity/__init__.py", line 410, in exc_check
    raise retry_exc.reraise()
          ^^^^^^^^^^^^^^^^^^^
  File "/home/your_username/.local/pipx/venvs/ofscraper/lib/python3.12/site-packages/tenacity/__init__.py", line 183, in reraise
    raise self.last_attempt.result()
          ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/concurrent/futures/_base.py", line 449, in result
    return self.__get_result()
           ^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/concurrent/futures/_base.py", line 401, in __get_result
    raise self._exception
  File "/home/your_username/.local/pipx/venvs/ofscraper/lib/python3.12/site-packages/ofscraper/download/main_download.py", line 113, in main_download_downloader
    raise E
  File "/home/your_username/.local/pipx/venvs/ofscraper/lib/python3.12/site-packages/ofscraper/download/main_download.py", line 95, in main_download_downloader
    return await resume_data_handler(data, c, tempholderObj, ele)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/your_username/.local/pipx/venvs/ofscraper/lib/python3.12/site-packages/ofscraper/download/main_download.py", line 135, in resume_data_handler
    placeholderObj = await placeholder.Placeholders(ele, content_type).init()
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/your_username/.local/pipx/venvs/ofscraper/lib/python3.12/site-packages/ofscraper/classes/placeholder.py", line 190, in init
    file = await self.createfilename()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/your_username/.local/pipx/venvs/ofscraper/lib/python3.12/site-packages/ofscraper/classes/placeholder.py", line 64, in inner
    return await f(args[0], *args[1:], **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/your_username/.local/pipx/venvs/ofscraper/lib/python3.12/site-packages/ofscraper/classes/placeholder.py", line 337, in createfilename
    out = self._addcount(ele, out)
          ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/your_username/.local/pipx/venvs/ofscraper/lib/python3.12/site-packages/ofscraper/classes/placeholder.py", line 345, in _addcount
    elif not ele.needs_count:
             ^^^^^^^^^^^^^^^
  File "/home/your_username/.local/pipx/venvs/ofscraper/lib/python3.12/site-packages/ofscraper/classes/media.py", line 411, in needs_count
    for text, name, spec, conv in list(
                                  ^^^^^
ValueError: expected ':' after conversion specifier
```

## To Reproduce

Download using commit d68a25c , i.e. `pipx install --force https://github.com/datawhores/OF-Scraper/archive/refs/tags/d68a25c.zip`

## Expected behavior

Download to succeed

## Config

https://privatebin.io/?2877d76d3df43038#9Xe6a4xqK1GcMdK4YQspm8AxpzhbgASXjBJgJAaA1hSs

## System Info

- Ubuntu 24.04
- Chrome
- Dev commit d68a25c
- Python 3.12.3

**Comment by guyhurst90** [comment]
Fwiw, installing commit c7566ea (`pipx install --force https://github.com/datawhores/OF-Scraper/archive/c7566ea9b72e9fb52d81371ea46b7c9138151c6c.zip`) returns the same error:


```

2024-06-03 13:44:08:[helpers.inner:11]  Media:3321253965 Post:1072573459  Traceback (most recent call last):
  File "/home/your_username/.local/pipx/venvs/ofscraper/lib/python3.12/site-packages/ofscraper/download/main_download.py", line 97, in main_download_downloader
    return await fresh_data_handler(c, tempholderObj, ele)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/your_username/.local/pipx/venvs/ofscraper/lib/python3.12/site-packages/ofscraper/download/main_download.py", line 126, in fresh_data_handler
    raise E
  File "/home/your_username/.local/pipx/venvs/ofscraper/lib/python3.12/site-packages/ofscraper/download/main_download.py", line 122, in fresh_data_handler
    result = await main_download_sendreq(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/your_username/.local/pipx/venvs/ofscraper/lib/python3.12/site-packages/ofscraper/download/main_download.py", line 183, in main_download_sendreq
    raise E
  File "/home/your_username/.local/pipx/venvs/ofscraper/lib/python3.12/site-packages/ofscraper/download/main_download.py", line 174, in main_download_sendreq
    return await send_req_inner(
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/your_username/.local/pipx/venvs/ofscraper/lib/python3.12/site-packages/ofscraper/download/main_download.py", line 238, in send_req_inner
    raise E
  File "/home/your_username/.local/pipx/venvs/ofscraper/lib/python3.12/site-packages/ofscraper/download/main_download.py", line 215, in send_req_inner
    placeholderObj = await placeholder.Placeholders(
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/your_username/.local/pipx/venvs/ofscraper/lib/python3.12/site-packages/ofscraper/classes/placeholder.py", line 190, in init
    file = await self.createfilename()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/your_username/.local/pipx/venvs/ofscraper/lib/python3.12/site-packages/ofscraper/classes/placeholder.py", line 64, in inner
    return await f(args[0], *args[1:], **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/your_username/.local/pipx/venvs/ofscraper/lib/python3.12/site-packages/ofscraper/classes/placeholder.py", line 337, in createfilename
    out = self._addcount(ele, out)
          ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/your_username/.local/pipx/venvs/ofscraper/lib/python3.12/site-packages/ofscraper/classes/placeholder.py", line 345, in _addcount
    elif not ele.needs_count:
             ^^^^^^^^^^^^^^^
  File "/home/your_username/.local/pipx/venvs/ofscraper/lib/python3.12/site-packages/ofscraper/classes/media.py", line 411, in needs_count
    for text, name, spec, conv in list(
                                  ^^^^^
ValueError: expected ':' after conversion specifier

 2024-06-03 13:44:08:[helpers.inner:11]  Media:3321253965 Post:1072573459  expected ':' after conversion specifier

```

Newer commits return a different fatal error attempting to download:

```

2024-06-03 13:56:07:[helpers.inner:11]  failed with exception: name 'modify_unique_constraint_media' is not defined
 2024-06-03 13:56:07:[helpers.inner:11]  Traceback (most recent call last):
  File "/home/luser/.local/pipx/venvs/ofscraper/lib/python3.12/site-packages/ofscraper/commands/helpers/normal.py", line 25, in wrapper
    all_media, posts, like_posts = await post_media_process(ele, c=c)
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/luser/.local/pipx/venvs/ofscraper/lib/python3.12/site-packages/ofscraper/commands/scraper/post.py", line 63, in post_media_process
    await operations.table_init_create(model_id=model_id, username=username)
  File "/home/luser/.local/pipx/venvs/ofscraper/lib/python3.12/site-packages/ofscraper/db/operations.py", line 429, in table_init_create
    await modify_tables(model_id, username)
  File "/home/luser/.local/pipx/venvs/ofscraper/lib/python3.12/site-packages/ofscraper/db/operations.py", line 129, in modify_tables
    raise E
  File "/home/luser/.local/pipx/venvs/ofscraper/lib/python3.12/site-packages/ofscraper/db/operations.py", line 124, in modify_tables
    await modify_tables_constraints_and_columns(
  File "/home/luser/.local/pipx/venvs/ofscraper/lib/python3.12/site-packages/ofscraper/db/operations.py", line 367, in modify_tables_constraints_and_columns
    await modify_unique_constraint_media(
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
NameError: name 'modify_unique_constraint_media' is not defined

```

**Comment by datawhores** [comment]
Yeah the merge had some issues 
I've been able to  do a few successful runs on my end

**Comment by guyhurst90** [comment]
Looks to be fixed in 3.10 release 👍

**Comment by guyhurst90** [comment]
Thought it was done in 3.10 but it only works sporadically now 🤷‍♂️

Downloading single models seems to work more often than downloading the entire model list at once, if that helps.

**Comment by datawhores** [comment]
Can you show the error that happens now

**Comment by guyhurst90** [comment]
```
 2024-06-05 02:07:52:[main_download.main_download_sendreq:171]  Media:3347441154 Post:3241167379964  download temp path /media/helium/onlyfans/censored/Messages/Videos/censored_source_3347441154.part
 2024-06-05 02:07:52:[main_download.send_req_inner:191]  Media:3347441154 Post:3241167379964  Downloading media with url https://cdn2.onlyfans.com/files/6/6f/censored/censored.mp4?Tag=2&Policy={hidden}&Signature={hidden}&Key-Pair-Id={hidden}
 2024-06-05 02:07:52:[downloadnormal.download:210]  Media:3347151585 Post:3240512550539 exception expected ':' after conversion specifier
 2024-06-05 02:07:52:[downloadnormal.download:211]  Media:3347151585 Post:3240512550539 exception Traceback (most recent call last):
  File "/home/your_username/.local/pipx/venvs/ofscraper/lib/python3.12/site-packages/ofscraper/download/downloadnormal.py", line 202, in download
    return await alt_download(
           ^^^^^^^^^^^^^^^^^^^
  File "/home/your_username/.local/pipx/venvs/ofscraper/lib/python3.12/site-packages/ofscraper/download/alt_download.py", line 72, in alt_download
    async for _ in download_retry():
  File "/home/your_username/.local/pipx/venvs/ofscraper/lib/python3.12/site-packages/tenacity/_asyncio.py", line 123, in __anext__
    do = await self.iter(retry_state=self._retry_state)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/your_username/.local/pipx/venvs/ofscraper/lib/python3.12/site-packages/tenacity/_asyncio.py", line 110, in iter
    result = await action(retry_state)
             ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/your_username/.local/pipx/venvs/ofscraper/lib/python3.12/site-packages/tenacity/_asyncio.py", line 78, in inner
    return fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^
  File "/home/your_username/.local/pipx/venvs/ofscraper/lib/python3.12/site-packages/tenacity/__init__.py", line 410, in exc_check
    raise retry_exc.reraise()
          ^^^^^^^^^^^^^^^^^^^
  File "/home/your_username/.local/pipx/venvs/ofscraper/lib/python3.12/site-packages/tenacity/__init__.py", line 183, in reraise
    raise self.last_attempt.result()
          ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/concurrent/futures/_base.py", line 449, in result
    return self.__get_result()
           ^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/concurrent/futures/_base.py", line 401, in __get_result
    raise self._exception
  File "/home/your_username/.local/pipx/venvs/ofscraper/lib/python3.12/site-packages/ofscraper/download/alt_download.py", line 80, in alt_download
    raise e
  File "/home/your_username/.local/pipx/venvs/ofscraper/lib/python3.12/site-packages/ofscraper/download/alt_download.py", line 75, in alt_download
    sharedPlaceholderObj = await placeholder.Placeholders(ele, "mp4").init()
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/your_username/.local/pipx/venvs/ofscraper/lib/python3.12/site-packages/ofscraper/classes/placeholder.py", line 190, in init
    file = await self.createfilename()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/your_username/.local/pipx/venvs/ofscraper/lib/python3.12/site-packages/ofscraper/classes/placeholder.py", line 64, in inner
    return await f(args[0], *args[1:], **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/your_username/.local/pipx/venvs/ofscraper/lib/python3.12/site-packages/ofscraper/classes/placeholder.py", line 337, in createfilename
    out = self._addcount(ele, out)
          ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/your_username/.local/pipx/venvs/ofscraper/lib/python3.12/site-packages/ofscraper/classes/placeholder.py", line 345, in _addcount
    elif not ele.needs_count:
             ^^^^^^^^^^^^^^^
  File "/home/your_username/.local/pipx/venvs/ofscraper/lib/python3.12/site-packages/ofscraper/classes/media.py", line 411, in needs_count
    for text, name, spec, conv in list(
                                  ^^^^^
ValueError: expected ':' after conversion specifier

 2024-06-05 02:07:52:[downloadnormal.consumer:48]  unpack ('skipped', 0) count 2
 ```

**Comment by datawhores** [comment]
I was honestly never able to recreate this issue
It might be coming from somewhere unexpected

**Comment by guyhurst90** [comment]
```
{
    "main_profile": "main_profile",
    "metadata": "{configpath}/{profile}/.data/{model_username}_{model_id}",
    "discord": "",
    "file_options": {
        "save_location": "/media/helium/onlyfans",
        "dir_format": "{model_username}/{responsetype}/{mediatype}/",
        "file_format": "{filename}.{ext if ext!='jpeg' else 'jpg'}",
        "textlength": 0,
        "space_replacer": " ",
        "date": "MM-DD-YYYY",
        "text_type_default": "letter",
        "truncation_default": true
    },
    "download_options": {
        "file_size_max": 0,
        "file_size_min": 0,
        "filter": [
            "Images",
            "Audios",
            "Videos"
        ],
        "auto_resume": true,
        "system_free_min": 0,
        "max_post_count": 0
    },
    "binary_options": {
        "mp4decrypt": "/usr/local/bin/mp4decrypt",
        "ffmpeg": "/usr/bin/ffmpeg"
    },
    "cdm_options": {
        "private-key": null,
        "client-id": null,
        "key-mode-default": "keydb",
        "keydb_api": "censored"
    },
    "performance_options": {
        "download-sem": 6,
        "threads": 5
    },
    "advanced_options": {
        "code-execution": true,
        "dynamic-mode-default": "deviint",
        "backend": "aio",
        "downloadbars": false,
        "cache-mode": "sqlite",
        "appendlog": true,
        "custom_values": null,
        "sanitize_text": false,
        "temp_dir": null,
        "remove_hash_match": false,
        "infinite_loop_action_mode": false,
        "post_download_script": null,
        "disable_auto_after": false,
        "default_user_list": "main",
        "default_black_list": ""
    },
    "responsetype": {
        "timeline": "Posts",
        "message": "Messages",
        "archived": "Archived",
        "paid": "Messages",
        "stories": "Stories",
        "highlights": "Stories",
        "profile": "Profile",
        "pinned": "Posts"
    },
    "overwrites": {
        "audios": {},
        "videos": {},
        "images": {},
    }
}
```

**Comment by datawhores** [comment]
fixed
please update via the 3.10b branch
