### ISSUE TITLE
New generated config syntax error

### ISSUE THREAD

**Issue by lordoffools** [datawhores/OF-Scraper#409]
Running v3.10.1. Decided to start fresh given the auth errors from yesterday.

After going through the steps to auto-generate the config.json, I'm now hitting a syntax error after setting the Download Options:

Your config.json has a syntax error
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/ofscraper/utils/config/context.py", line 16, in config_context
    json.load(f)
  File "/usr/local/Cellar/python@3.11/3.11.4_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/json/__init__.py", line 293, in load
    return loads(fp.read(),
           ^^^^^^^^^^^^^^^^
  File "/usr/local/Cellar/python@3.11/3.11.4_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/Cellar/python@3.11/3.11.4_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/Cellar/python@3.11/3.11.4_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

Expecting value: line 1 column 1 (char 0)

## System Info

- OS: MacOS
- Version: 3.10.1
- binary or python: binary
- python version if installed via pip or pypi: Python 3.11.4

**Comment by cjb900** [comment]
https://gist.github.com/datawhores/8e8be131fb1b190b50c5324ab2ca5f89

**Comment by lordoffools** [comment]
> https://gist.github.com/datawhores/8e8be131fb1b190b50c5324ab2ca5f89

I'm not sure that's for the syntax error I'm hitting above, though, is it? Because I did change the auth setting and I can authenticate just fine now.

**Comment by datawhores** [comment]
can you show the config?

**Comment by lordoffools** [comment]
> can you show the config?

Thanks. No need -- I re-did the config, and it seems to parse just fine now. Wish I knew what was wrong. Closing this bug.

Appreciate the help, always!
