### ISSUE TITLE
unsupported operand type(s) for -: 'set' and 'list'

### ISSUE THREAD

**Issue by merqwury** [datawhores/OF-Scraper#424]
## Describe the bug

Seeing some error in the log files pertaining to some Python types. I believe this is non-fatal (i.e. scraping/downloading still works) as this traceback seems to happen in a log.info().

## To Reproduce

I don't have to do anything in particular to reproduce. Happens consistently.

## Expected behavior

Not expected to see this tracebacks

## Screenshots/Logs

```
2024-06-19 16:19:02:[helpers.inner:11]  unsupported operand type(s) for -: 'set' and 'list'
 2024-06-19 16:19:02:[helpers.inner:11]  Traceback (most recent call last):
  File "/venv/lib/python3.11/site-packages/ofscraper/commands/scraper/post.py", line 71, in process_messages
    messages_ = await messages.get_messages(model_id, username, c=c)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/venv/lib/python3.11/site-packages/ofscraper/api/messages.py", line 54, in get_messages
    after = await get_after(model_id, username, forced_after)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/venv/lib/python3.11/site-packages/ofscraper/api/messages.py", line 410, in get_after
    log.info(f"Number of messages marked as downloaded {curr_downloaded-missing_items}")
                                                        ~~~~~~~~~~~~~~~^~~~~~~~~~~~~~
TypeError: unsupported operand type(s) for -: 'set' and 'list'

 2024-06-19 16:19:02:[post.process_tasks:594]  cannot unpack non-iterable NoneType object
 ```

## Config

Please provide details about your correct config
This is required for all reports

```
{
    "main_profile": "main_profile",
    "metadata": "/metadata/{model_username}/Metadata",
    "discord": "",
    "file_options": {
        "save_location": "/data",
        "dir_format": "{model_username}/{responsetype}/{value}/{mediatype}/",
        "file_format": "{filename}.{ext}",
        "textlength": 0,
        "space_replacer": " ",
        "date": "MM-DD-YYYY",
        "text_type_default": "letter",
        "truncation_default": true
    },
    "download_options": {
        "file_size_max": 0,
        "file_size_min": 0,
        "filter": [
            "Images",
            "Audios",
            "Videos"
        ],
        "auto_resume": true,
        "system_free_min": 0,
        "max_post_count": 0
    },
    "binary_options": {
        "mp4decrypt": "/config/bin/mp4decrypt",
        "ffmpeg": "/config/bin/ffmpeg"
    },
    "cdm_options": {
        "private-key": "/config/bin/private_key.pem",
        "client-id": "/config/bin/client_id.bin",
        "key-mode-default": "manual",
        "keydb_api": ""
    },
    "performance_options": {
        "download-sem": 6,
        "threads": 1
    },
    "advanced_options": {
        "code-execution": true,
        "dynamic-mode-default": "deviint",
        "backend": "aio",
        "downloadbars": false,
        "cache-mode": "sqlite",
        "appendlog": true,
        "sanitize_text": false,
        "temp_dir": null,
        "remove_hash_match": false,
        "infinite_loop_action_mode": false,
        "post_download_script": null,
        "disable_auto_after": false,
        "default_user_list": "main",
        "default_black_list": "",
        "custom_values": {
            "DEVIINT": "https://raw.githubusercontent.com/datawhores/onlyfans-dynamic-rules/new/dynamicRules.json"
        }},
    "responsetype": {
        "timeline": "Posts",
        "message": "Messages",
        "archived": "Archived",
        "paid": "Messages",
        "stories": "Stories",
        "highlights": "Stories",
        "profile": "Profile",
        "pinned": "Posts",
        "streams": "Streams"
    },
    "overwrites": {
        "audios": {},
        "videos": {},
        "images": {},
        "text": {}
    }
}
```

## System Info

- OS: Docker
- Browser: N/A
- Version: 3.10b

**Comment by datawhores** [comment]
This should have been fixed
