### ISSUE TITLE
KeyError: "TYPE" 

### ISSUE THREAD

**Issue by Bum211** [datawhores/OF-Scraper#427]
Hello, I'm running on the latest commit and the Auth Loop is running just fine. I can select the model I want to scrape and the script would run as normal. After the script is finished, nothing is downloaded. Please see the logging below: 

 File "ofscraper\commands\scraper\post.py", line 433, in process_areas
  File "ofscraper\filters\media\main.py", line 70, in filtermediaAreas
  File "ofscraper\filters\media\helpers\helpers.py", line 73, in mediatype_type_filter
  File "ofscraper\filters\media\helpers\helpers.py", line 73, in <lambda>
  File "ofscraper\classes\media.py", line 61, in mediatype
KeyError: 'type'

 2024-06-21 13:08:15:[helpers.inner:11]  failed with exception: cannot unpack non-iterable NoneType object
 2024-06-21 13:08:15:[helpers.inner:11]  Traceback (most recent call last):
  File "ofscraper\commands\helpers\normal.py", line 29, in wrapper
TypeError: cannot unpack non-iterable NoneType object

**Comment by datawhores** [comment]
Fixed it was a typo
