### ISSUE TITLE
Can't install

### ISSUE THREAD

**Issue by MaH-s9UFaXPEKdLafMHkSGgWUAupTA1xj78S9C7** [datawhores/OF-Scraper#43]
Hey

First off, thank you for making this.

Second, I cannot seem to install this at all. Admittedly I am very new to git and python, so the problem is definitely on my end not knowing how to do it. Still, I hope you can help me out.
This is what I get, after running pip install ofscraper
D:\OFScraper 1.8>pip install ofscraper
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\User\AppData\Local\Programs\Python\Python311\Scripts\pip.exe\__main__.py", line 4, in <module>
  File "C:\Users\User\AppData\Local\Programs\Python\Python311\Lib\site-packages\pip\_internal\cli\main.py", line 9, in <module>
    from pip._internal.cli.autocompletion import autocomplete
  File "C:\Users\User\AppData\Local\Programs\Python\Python311\Lib\site-packages\pip\_internal\cli\autocompletion.py", line 10, in <module>
    from pip._internal.cli.main_parser import create_main_parser
  File "C:\Users\User\AppData\Local\Programs\Python\Python311\Lib\site-packages\pip\_internal\cli\main_parser.py", line 9, in <module>
    from pip._internal.build_env import get_runnable_pip
  File "C:\Users\User\AppData\Local\Programs\Python\Python311\Lib\site-packages\pip\_internal\build_env.py", line 20, in <module>
    from pip._internal.cli.spinners import open_spinner
  File "C:\Users\User\AppData\Local\Programs\Python\Python311\Lib\site-packages\pip\_internal\cli\spinners.py", line 9, in <module>
    from pip._internal.utils.logging import get_indentation
  File "C:\Users\User\AppData\Local\Programs\Python\Python311\Lib\site-packages\pip\_internal\utils\logging.py", line 29, in <module>
    from pip._internal.utils.misc import ensure_dir
  File "C:\Users\User\AppData\Local\Programs\Python\Python311\Lib\site-packages\pip\_internal\utils\misc.py", line 37, in <module>
    from pip._vendor.pep517 import Pep517HookCaller
ImportError: cannot import name 'Pep517HookCaller' from 'pip._vendor.pep517' (unknown location)

I've tried with both git clone and taking the zip from the releases. Done both with what you released yesterday.
I've gotten the newest python installed.

**Comment by datawhores** [comment]
This issue looks like it is out of scope

Can you maybe try to uninstall and reinstall pip
