### ISSUE TITLE
--metadata-update argument not recognized

### ISSUE THREAD

**Issue by DADESUPER** [datawhores/OF-Scraper#441]
## Describe the bug

Using the --metadata-update argument leads to immediate crashing due to "unrecognized argument"

## To Reproduce

ofscraper_windows_a42cfee.exe --metadata-update

## Expected behavior

Per docs: "This will update files on system based on config, if a file does not exist on system it will be marked as not downloaded in data"

## Screenshots/Logs

Traceback (most recent call last):
  File "__main__.py", line 4, in <module>
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 419, in exec_module
  File "ofscraper\runner\load.py", line 6, in <module>
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 419, in exec_module
  File "ofscraper\runner\run.py", line 5, in <module>
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 419, in exec_module
  File "ofscraper\commands\picker\picker.py", line 1, in <module>
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 419, in exec_module
  File "ofscraper\commands\commands\check.py", line 13, in <module>
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 419, in exec_module
  File "ofscraper\api\archive.py", line 23, in <module>
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 419, in exec_module
  File "ofscraper\utils\constants.py", line 3, in <module>
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 419, in exec_module
  File "ofscraper\utils\config\custom.py", line 3, in <module>
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 419, in exec_module
  File "ofscraper\utils\config\file.py", line 7, in <module>
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 419, in exec_module
  File "ofscraper\utils\config\utils\context.py", line 5, in <module>
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 419, in exec_module
  File "ofscraper\prompts\prompts.py", line 14, in <module>
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 419, in exec_module
  File "ofscraper\prompts\prompt_groups\actions.py", line 4, in <module>
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 419, in exec_module
  File "ofscraper\prompts\promptConvert.py", line 10, in <module>
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 419, in exec_module
  File "ofscraper\utils\live\empty.py", line 4, in <module>
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 419, in exec_module
  File "ofscraper\utils\console.py", line 16, in <module>
  File "ofscraper\utils\args\accessors\output.py", line 4, in low_output
  File "ofscraper\utils\args\accessors\read.py", line 23, in retriveArgs
  File "ofscraper\utils\args\main.py", line 46, in parse_args
  File "click\core.py", line 1157, in __call__
  File "click\core.py", line 1077, in main
  File "click\core.py", line 943, in make_context
  File "cloup\constraints\_support.py", line 183, in parse_args
  File "click\core.py", line 1644, in parse_args
  File "click\core.py", line 1405, in parse_args
  File "click\parser.py", line 337, in parse_args
  File "click\parser.py", line 364, in _process_args_for_options
  File "click\parser.py", line 514, in _process_opts
  File "click\parser.py", line 398, in _match_long_opt
click.exceptions.NoSuchOption: No such option: --metadata-update
[11452] Failed to execute script '__main__' due to unhandled exception!

## System Info

- OS: Windows 10
- Browser: Chrome
- Binary version 2024.07.28_201807_dev/3.11_a42cfee_package

**Comment by datawhores** [comment]
It is because it is a subcommand it does not have the same arguments as the main ofscraper command, and it has special arguments only for the ofscraper metadata comand
```
ofscaper metadata -h
```
to list possible options

```
ofscraper metadata --metadata-update
```

**Comment by DADESUPER** [comment]
> It is because it is a subcommand it does not have the same arguments as the main ofscraper command, and it has special arguments only for the ofscraper metadata comand
> 
> ```
> ofscaper metadata -h
> ```
> 
> to list possible options
> 
> ```
> ofscraper metadata --metadata-update
> ```

Alright, thank you. Please note that [this page](https://of-scraper.gitbook.io/of-scraper/using-the-scraper/recipes/redownload-deleted-downloads) in the docs does not specify the corrext syntax for the command. It omits that it is a subcommand. It should get corrected when possible
