### ISSUE TITLE
# ModuleNotFoundError: No Module name 'pkg_resources.extern'

### ISSUE THREAD

**Issue by exe22** [datawhores/OF-Scraper#450]
## Describe the bug

I'm using ofscraper_windows_3.11.4.exe

The script crashes during start-up with the following error.

Traceback (most recent call last):
  File "PyInstaller\hooks\rthooks\pyi_rth_pkgres.py", line 158, in <module>
  File "PyInstaller\hooks\rthooks\pyi_rth_pkgres.py", line 36, in _pyi_rthook
  File "PyInstaller\loader\pyimod02_importers.py", line 419, in exec_module
  File "pkg_resources\__init__.py", line 90, in <module>
ModuleNotFoundError: No module named 'pkg_resources.extern'
[40196] Failed to execute script 'pyi_rth_pkgres' due to unhandled exception!

## Troubleshooting

I tried to install setuptools via pip install setuptools but it didn't help.

## System Info

- OS: Windows 11
- Version: 3.11.4
- python
- python version 3.12.4

**Comment by Puk0** [comment]
in windows, since "setuptools" was updated they no longer open the exes

use the pip version:

`pip install ofscraper`

**Comment by exe22** [comment]
Thanks, I just tried this but it shows me Welcome to OF-Scraper Version 3.7.0.dev2.

Will there be the latest version available? Can I update it manually?

**Comment by datawhores** [comment]
I'll make an announcement once these are working again

**Comment by mwald84** [comment]
I tried the pip version but it reset my config file. Did the format change?

**Comment by Puk0** [comment]
> I tried the pip version but it reset my config file. Did the format change? I was using 3.11.1 before. It's removing the cdm options (I use my own keys).

in some versions it changes; just put "manual" and the paths of your two files

**Comment by mwald84** [comment]
> > I tried the pip version but it reset my config file. Did the format change? I was using 3.11.1 before. It's removing the cdm options (I use my own keys).
> 
> in some versions it changes; just put "manual" and the paths of your two files, and ffmpeg

But manual isn't to download specific posts (with URL)? Or do you mean in the config file?

**Comment by Puk0** [comment]
> But manual isn't to download specific posts (with URL)? Or do you mean in the config file?

"key-mode-default": "manual",
and
"private-key":
"client-id":

**Comment by datawhores** [comment]
This was broken on Linux when I tested as well 
I'm not sure when, I don't use the execs

I recommend just using pipx if you really want multiple version of the script
