### ISSUE TITLE
mp4decrypt issue

### ISSUE THREAD

**Issue by misterscraper** [datawhores/OF-Scraper#82]
`mp4decrypt not found would you like to auto install? Yes

You need to select path for mp4decrypt

[Errno 8] Exec format error: '/Users/XXX/.config/ofscraper/bin/mp4decrypt'
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/ofscraper/utils/paths.py", line 197, in mp4decryptexecutecheck
    t=subprocess.run([x],stdout=subprocess.PIPE,stderr=subprocess.PIPE)
      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/subprocess.py", line 548, in run
    with Popen(*popenargs, **kwargs) as process:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/subprocess.py", line 1026, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/subprocess.py", line 1950, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
OSError: [Errno 8] Exec format error: '/Users/XXX/.config/ofscraper/bin/mp4decrypt'
`

Any fix for this? it downloads mp4decrypt but then gives me this constant error

**Comment by datawhores** [comment]
Can you confirm mp4decrypt runs from the command line

**Comment by datawhores** [comment]
Also what operating system are you on
Is it 64 bits?

**Comment by misterscraper** [comment]
> Can you confirm mp4decrypt runs from the command line

I get the following message when i choose "no" for auto install;

`mp4decrypt not found would you like to auto install? No
[Errno 8] Exec format error: '/Users/XXX/.config/ofscraper/bin/mp4decrypt'
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/ofscraper/utils/paths.py", line 197, in mp4decryptexecutecheck
    t=subprocess.run([x],stdout=subprocess.PIPE,stderr=subprocess.PIPE)
      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/subprocess.py", line 548, in run
    with Popen(*popenargs, **kwargs) as process:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/subprocess.py", line 1026, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/subprocess.py", line 1950, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
OSError: [Errno 8] Exec format error: '/Users/XXX/.config/ofscraper/bin/mp4decrypt'

[Errno 8] Exec format error: '/Users/XXX/.config/ofscraper/bin/mp4decrypt'
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/InquirerPy/prompts/input.py", line 189, in _handle_enter
    self._session.validator.validate(self._session.default_buffer)  # type: ignore
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/ofscraper/prompts/prompt_validators.py", line 33, in validate
    raise E
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/ofscraper/prompts/prompt_validators.py", line 31, in validate
    input.validate(document)
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/prompt_toolkit/validation.py", line 127, in validate
    raise ValidationError(cursor_position=index, message=self.error_message)
prompt_toolkit.validation.ValidationError: Path is valid but the given path could not be verified to be mp4decrypt

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/ofscraper/utils/paths.py", line 197, in mp4decryptexecutecheck
    t=subprocess.run([x],stdout=subprocess.PIPE,stderr=subprocess.PIPE)
      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/subprocess.py", line 548, in run
    with Popen(*popenargs, **kwargs) as process:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/subprocess.py", line 1026, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/subprocess.py", line 1950, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
OSError: [Errno 8] Exec format error: '/Users/XXX/.config/ofscraper/bin/mp4decrypt'

? mp4decrypt path:  /Users/thegoat/.config/ofscraper/bin/mp4decrypt






 
Path is valid but the given path could not be verified to be mp4decrypt
 
Certain content requires decryption to process please provide the full path to mp4decrypt
Linux version [mp4decrypt] and windows version [mp4decrypt.exe] are provided in the repo
 
https://www.bento4.com/documentation/mp4decrypt/
`

I'm also using the latest python update and Mac OS

**Comment by datawhores** [comment]
Oh yeah it's the wrong version I need to add a fix

**Comment by misterscraper** [comment]
> Oh yeah it's the wrong version I need to add a fix

the wrong python version?

**Comment by datawhores** [comment]
There is a mp4decrypt version for Mac, but another one is getting downloaded

**Comment by misterscraper** [comment]
> There is a mp4decrypt version for Mac, but another one is getting downloaded

I'm with you now, hopefully you can fix this :)

**Comment by datawhores** [comment]
It should be fix
It was downloading the linux version previously

**Comment by misterscraper** [comment]
Now I get an issue with ffmpeg

`ofscraper
Welcome to OF-Scraper Version 2.4.5
? What would you like to do? Download content from a user
You need to select path for ffmpeg


[Errno 8] Exec format error: '/Users/XXX/.config/ofscraper/bin/ffmpeg'
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/ofscraper/utils/paths.py", line 218, in ffmpegexecutecheck
    t=subprocess.run([x],stdout=subprocess.PIPE,stderr=subprocess.PIPE)
      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/subprocess.py", line 548, in run
    with Popen(*popenargs, **kwargs) as process:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/subprocess.py", line 1026, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/subprocess.py", line 1950, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
OSError: [Errno 8] Exec format error: '/Users/XXX/.config/ofscraper/bin/ffmpeg'

? ffmpeg not found would you like to auto install? Yes

You need to select path for ffmpeg


[Errno 8] Exec format error: '/Users/XXX/.config/ofscraper/bin/ffmpeg'
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/ofscraper/utils/paths.py", line 218, in ffmpegexecutecheck
    t=subprocess.run([x],stdout=subprocess.PIPE,stderr=subprocess.PIPE)
      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/subprocess.py", line 548, in run
    with Popen(*popenargs, **kwargs) as process:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/subprocess.py", line 1026, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/subprocess.py", line 1950, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
OSError: [Errno 8] Exec format error: '/Users/XXX/.config/ofscraper/bin/ffmpeg'

? ffmpeg not found would you like to auto install? No
[Errno 8] Exec format error: '/Users/XXX/.config/ofscraper/bin/ffmpeg'
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/ofscraper/utils/paths.py", line 218, in ffmpegexecutecheck
    t=subprocess.run([x],stdout=subprocess.PIPE,stderr=subprocess.PIPE)
      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/subprocess.py", line 548, in run
    with Popen(*popenargs, **kwargs) as process:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/subprocess.py", line 1026, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/subprocess.py", line 1950, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
OSError: [Errno 8] Exec format error: '/Users/XXX/.config/ofscraper/bin/ffmpeg'

[Errno 8] Exec format error: '/Users/XXX/.config/ofscraper/bin/ffmpeg'
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/InquirerPy/prompts/input.py", line 189, in _handle_enter
    self._session.validator.validate(self._session.default_buffer)  # type: ignore
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/ofscraper/prompts/prompt_validators.py", line 33, in validate
    raise E
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/ofscraper/prompts/prompt_validators.py", line 31, in validate
    input.validate(document)
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/prompt_toolkit/validation.py", line 127, in validate
    raise ValidationError(cursor_position=index, message=self.error_message)
prompt_toolkit.validation.ValidationError: Path is valid but the given path could not be verified to be ffmpeg

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/ofscraper/utils/paths.py", line 218, in ffmpegexecutecheck
    t=subprocess.run([x],stdout=subprocess.PIPE,stderr=subprocess.PIPE)
      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/subprocess.py", line 548, in run
    with Popen(*popenargs, **kwargs) as process:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/subprocess.py", line 1026, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/subprocess.py", line 1950, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
OSError: [Errno 8] Exec format error: '/Users/XXX/.config/ofscraper/bin/ffmpeg'

? ffmpeg path:  /Users/XXX/.config/ofscraper/bin/ffmpeg






 
Path is valid but the given path could not be verified to be ffmpeg
 
Certain content requires decryption to process please provide the full path to ffmpeg
Linux version [ffmpeg] and windows version [ffmpeg.exe] are provided in the repo 
 
https://ffmpeg.org/download.html`

**Comment by misterscraper** [comment]
I managed to fix it by downloading the mac version and control + click the downloaded file so Mac OS could verify it's valid :).

Is the issue with playing DRM protected files that have downloaded normal?

**Comment by datawhores** [comment]
No they should play fine
I don't have access to a mac for testing

This is the link I used for mac
https://evermeet.cx/ffmpeg/ffmpeg-111111-gc44fe10160.zip

From 
https://evermeet.cx/ffmpeg/

**Comment by datawhores** [comment]
the file needs to be rename to .mkv
I pushed a fix adding a script to make this process easier
