### ISSUE TITLE
Downloading stops after about 6 minutes

### ISSUE THREAD

**Issue by Predatir** [datawhores/OF-Scraper#93]
After that I get this error:
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\Preda\AppData\Local\Programs\Python\Python311\Scripts\ofscraper.exe\__main__.py", line 7, in <module>
  File "C:\Users\Preda\AppData\Local\Programs\Python\Python311\Lib\site-packages\ofscraper\start.py", line 26, in main
    scraper.main()
  File "C:\Users\Preda\AppData\Local\Programs\Python\Python311\Lib\site-packages\ofscraper\commands\scraper.py", line 336, in main
    scrapper()
  File "C:\Users\Preda\AppData\Local\Programs\Python\Python311\Lib\site-packages\ofscraper\commands\scraper.py", line 382, in scrapper
    run(*functs)
    ^^^^^^^^^^^^
  File "C:\Users\Preda\AppData\Local\Programs\Python\Python311\Lib\site-packages\ofscraper\commands\scraper.py", line 259, in run
    run_helper(*functs)
  File "C:\Users\Preda\AppData\Local\Programs\Python\Python311\Lib\site-packages\ofscraper\commands\scraper.py", line 264, in run_helper
    [funct() for funct in functs]
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Preda\AppData\Local\Programs\Python\Python311\Lib\site-packages\ofscraper\commands\scraper.py", line 264, in <listcomp>
    [funct() for funct in functs]
     ^^^^^^^
  File "C:\Users\Preda\AppData\Local\Programs\Python\Python311\Lib\site-packages\ofscraper\commands\scraper.py", line 127, in process_post
    normal_post_process()
  File "C:\Users\Preda\AppData\Local\Programs\Python\Python311\Lib\site-packages\ofscraper\commands\scraper.py", line 180, in normal_post_process
    asyncio.run(download.process_dicts(
  File "C:\Users\Preda\AppData\Local\Programs\Python\Python311\Lib\asyncio\runners.py", line 190, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "C:\Users\Preda\AppData\Local\Programs\Python\Python311\Lib\asyncio\runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Preda\AppData\Local\Programs\Python\Python311\Lib\asyncio\base_events.py", line 653, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "C:\Users\Preda\AppData\Local\Programs\Python\Python311\Lib\site-packages\ofscraper\utils\download.py", line 110, in process_dicts
    media_type, num_bytes_downloaded = await coro
                                       ^^^^^^^^^^
  File "C:\Users\Preda\AppData\Local\Programs\Python\Python311\Lib\asyncio\tasks.py", line 605, in _wait_for_one
    return f.result()  # May raise f.exception().
           ^^^^^^^^^^
  File "C:\Users\Preda\AppData\Local\Programs\Python\Python311\Lib\site-packages\tenacity\_asyncio.py", line 88, in async_wrapped
    return await fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Preda\AppData\Local\Programs\Python\Python311\Lib\site-packages\tenacity\_asyncio.py", line 47, in __call__
    do = self.iter(retry_state=retry_state)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Preda\AppData\Local\Programs\Python\Python311\Lib\site-packages\tenacity\__init__.py", line 314, in iter
    return fut.result()
           ^^^^^^^^^^^^
  File "C:\Users\Preda\AppData\Local\Programs\Python\Python311\Lib\concurrent\futures\_base.py", line 449, in result
    return self.__get_result()
           ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Preda\AppData\Local\Programs\Python\Python311\Lib\concurrent\futures\_base.py", line 401, in __get_result
    raise self._exception
  File "C:\Users\Preda\AppData\Local\Programs\Python\Python311\Lib\site-packages\tenacity\_asyncio.py", line 50, in __call__
    result = await fn(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Preda\AppData\Local\Programs\Python\Python311\Lib\site-packages\ofscraper\utils\download.py", line 144, in download
    return await alt_download_helper(ele,path,file_size_limit,username,model_id,progress)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Preda\AppData\Local\Programs\Python\Python311\Lib\site-packages\ofscraper\utils\download.py", line 207, in alt_download_helper
    mpd=await ele.parse_mpd
        ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Preda\AppData\Local\Programs\Python\Python311\Lib\site-packages\ofscraper\api\posts.py", line 376, in parse_mpd
    r = await c.get(self.mpd, timeout=None)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Preda\AppData\Local\Programs\Python\Python311\Lib\site-packages\httpx\_client.py", line 1757, in get
    return await self.request(
           ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Preda\AppData\Local\Programs\Python\Python311\Lib\site-packages\httpx\_client.py", line 1533, in request
    return await self.send(request, auth=auth, follow_redirects=follow_redirects)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Preda\AppData\Local\Programs\Python\Python311\Lib\site-packages\httpx\_client.py", line 1620, in send
    response = await self._send_handling_auth(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Preda\AppData\Local\Programs\Python\Python311\Lib\site-packages\httpx\_client.py", line 1648, in _send_handling_auth
    response = await self._send_handling_redirects(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Preda\AppData\Local\Programs\Python\Python311\Lib\site-packages\httpx\_client.py", line 1685, in _send_handling_redirects
    response = await self._send_single_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Preda\AppData\Local\Programs\Python\Python311\Lib\site-packages\httpx\_client.py", line 1722, in _send_single_request
    response = await transport.handle_async_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Preda\AppData\Local\Programs\Python\Python311\Lib\site-packages\httpx\_transports\default.py", line 353, in handle_async_request
    resp = await self._pool.handle_async_request(req)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Preda\AppData\Local\Programs\Python\Python311\Lib\site-packages\httpcore\_async\connection_pool.py", line 253, in handle_async_request
    raise exc
  File "C:\Users\Preda\AppData\Local\Programs\Python\Python311\Lib\site-packages\httpcore\_async\connection_pool.py", line 237, in handle_async_request
    response = await connection.handle_async_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Preda\AppData\Local\Programs\Python\Python311\Lib\site-packages\httpcore\_async\connection.py", line 63, in handle_async_request
    stream = await self._connect(request)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Preda\AppData\Local\Programs\Python\Python311\Lib\site-packages\httpcore\_async\connection.py", line 111, in _connect
    stream = await self._network_backend.connect_tcp(**kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Preda\AppData\Local\Programs\Python\Python311\Lib\site-packages\httpcore\backends\auto.py", line 29, in connect_tcp
    return await self._backend.connect_tcp(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Preda\AppData\Local\Programs\Python\Python311\Lib\site-packages\httpcore\backends\asyncio.py", line 111, in connect_tcp
    stream: anyio.abc.ByteStream = await anyio.connect_tcp(
                                   ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Preda\AppData\Local\Programs\Python\Python311\Lib\site-packages\anyio\_core\_sockets.py", line 221, in connect_tcp
    await event.wait()
  File "C:\Users\Preda\AppData\Local\Programs\Python\Python311\Lib\site-packages\anyio\_backends\_asyncio.py", line 1778, in wait
    if await self._event.wait():
       ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Preda\AppData\Local\Programs\Python\Python311\Lib\asyncio\locks.py", line 213, in wait
    await fut
asyncio.exceptions.CancelledError

**Comment by ctrlcmdshft** [comment]
What version are you on? Run this to check `ofscraper -v`

**Comment by Predatir** [comment]
2.5

**Comment by ctrlcmdshft** [comment]
Update to newest and try `pip uninstall ofscraper` then run `pip install ofscraper` and it will install newest pip release

**Comment by ctrlcmdshft** [comment]
Ahh sorry you were on newest my mixup

**Comment by Predatir** [comment]
Yeah i did that anyway. I just noticed that videos don't download fully even before it give that error. It seems like videos just stop downloading at 80%, 81% and then it starts downloading next one until it gives that error

**Comment by ctrlcmdshft** [comment]
Can you uninstall again and try running a prior version `pip install ofscraper==2.4.5` and test if your issue is present there

**Comment by bluman181** [comment]
Im having a similar issue on 2.5 as well on mac os but it doesn't start at all, the progress status comes up and stay @ 0% then it just skips. I went back to 2.4.5 and it works.

**Comment by Predatir** [comment]
2.4.5 works well thanks

**Comment by datawhores** [comment]
The issue might be timing out 

I'm going to push a commit after this comment to try to fix this issue

**Comment by avekifes** [comment]
I don't know if this is the same issue, but I'm noticing a problem where the script will seemingly stall (all progress indicators go into a standstill), but if I check my Task Manager, the script is clearly still using bandwidth/downloading.

**Comment by datawhores** [comment]
does this still happen?
